### ISSUE TITLE
chore(ios): test build artifact did not show correct version string in-app

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#10078]
# Test Results

* **TEST_PICKER_SELECTION_IOS (PASSED):** Retested in iOS 16.6 - iPhone 13 mobile device and here is my observation: 1. Installed the attached TestFlight internal PR build and noticed that it is showing keyman 17.0.215 version instead of showing keyman 17.0.216 version. However, I tried to test with this build. [...]

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/16f94716-eeb8-4b47-bdd3-0ba2c58befa8">

_Originally posted by @bharanidharanj in https://github.com/keymanapp/keyman/issues/10061#issuecomment-1823979040_

**Comment by darcywong00** [comment]
Screenshot looks like iOS app and not Android?

**Comment by mcdurdin** [comment]
I think this is related to having to select a specific build within testflight, because the default build will not necessarily be the one in the PR.

1. Note the build number details from the PR, for example: 

   ![image](https://github.com/keymanapp/keyman/assets/4498365/2e0d0ec4-d445-4d0b-ae75-4bddb949efe1)

2. Open TestFlight
3. Select the app to install (Keyman alpha)
4. Select Previous Builds
5. Locate the build number from the PR and select it to install that version.

**Comment by jahorton** [comment]
Fair enough.  I just double-checked by installing that PR's specified artifact on my personal iOS device, and the issue did not reproduce.  Thus, your explanation likely is what happened.
