### ISSUE TITLE
bug(web): modifier keys on OSK don't track correctly for armenian keyboard

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10224]
The armenian keyboard is a legacy keyboard, but the modifier keys _should_ track. However, holding <kbd>Shift</kbd> seems to have no effect, and pressing and releasing <Ctrl> leaves the Ctrl key/layer depressed on the OSK.

The <Kbd>Ctrl</kbd> behaviour is similar for the <kbd>Alt</kbd> key. Using combinations results in other stuck layers but no more than one layer remains stuck.

Hard to see here, but Shift pressed (and released) around 4 second mark; Ctrl pressed at 5 seconds and released at 6 seconds:

https://github.com/keymanapp/keyman/assets/4498365/df115d43-ab0c-4b86-9d74-0a6df87250d0

Repro on various versions:
* https://keymanweb.com/?version=17.0.228#hy,Keyboard_armenian
* https://keymanweb.com/?version=16.0.144#hy,Keyboard_armenian
* https://keymanweb.com/?version=12.0.106#hy,Keyboard_armenian

**Comment by ermshiperete** [comment]
I can't reproduce this with Firefox 120.0.1 and Google Chrome 120.0.6099.71 on Ubuntu 22.04, nor with Microsoft Edge 120.0.2210.61 on Windows 10. Things work as expected.

**Comment by mcdurdin** [comment]
I can still repro here :grin: 

I can look at this in A17S30 if you like.

**Comment by bharanidharanj** [comment]
Tested this issue as per @ermshiperete suggestion and here is my observation: 1. Tested in Firefox Browser version 120.0.1 (64-bit) and Google Chrome 120.0.6099.71 browser (64-bit) with the giving links (as mentioned in the issue). 2. An empty layer appear If I press Control or Alt button in the OSK. 

..in Firefox browser 
   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/30b982e5-a305-4e0f-9ac0-9013427834e3">


..in Chrome browser
 
   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/fa5b82e9-4b96-48b0-80e2-719a9eb5ef16">

**Comment by ermshiperete** [comment]
@mcdurdin Wait, do you use the hardware keyboard to press the modifier keys? With that I see the behavior you describe, but I'm getting the same for all keyboards, not just armenian.

**Comment by mcdurdin** [comment]
> Wait, do you use the hardware keyboard to press the modifier keys?

Yes. Sorry that I wasn't clear about that! Do you get that for Khmer Angkor? (https://keymanweb.com/?version=17.0.228#km,Keyboard_khmer_angkor) For me, I don't get that behaviour on Khmer Angkor; it works correctly.

**Comment by ermshiperete** [comment]
I think there are two issues here.

- With armenian, pressing <kbd>Shift</kbd> on the hardware keyboard doesn't do anything.
- With all Keyman keyboards, pressing any of the modifier keys like <kbd>Ctrl</kbd>, <kbd>Alt</kbd> etc on the hardware keyboard, switches to the corresponding layer, but there is no way to turn off that layer (except clicking on the OSK). There are two options how it could behave: 
  - a) Switching to the layer only while the modifier key is pressed. Releasing the key switches back to the default layer (This is the behavior you normally get from a hardware keyboard). Or 
  - b) Pressing the same modifier key again switches back to the default layer (this would match the way things work when clicking on the OSK).

**Comment by mcdurdin** [comment]
So this is a release-blocking regression -- not sure when it arose. I am not seeing the exact same behaviour you describe on other keyboards.

Expected behaviour (and old behaviour):
1. By default, the desktop OSK matches the hardware keyboard state -- if the user is holding one or more modifier keys on the hardware keyboard, then the OSK will show the resulting state.
2. When the user releases any hardware modifier key, then that modifier state is removed from the OSK immediately.
3. If the user clicks on one or more modifier keys on the OSK, then the OSK moves to the resulting state and remains there, until _any_ modifier key is clicked again -- or the corresponding modifier key on the hardware keyboard is touched.

See https://keymanweb.com/?version=12.0.106#hy,Keyboard_basic_kbdarmw for working example.

This is close to the Keyman for Windows OSK behaviour, but not identical. (The difference: On Keyman for Windows, you can see that a clicked modifier on the OSK is only released if that specific modifier is clicked again, or the corresponding hardware modifier key is touched, unlike KMW where any modifier key touch on the hardware keyboard resets it.)

**Comment by mcdurdin** [comment]
Note: I am not seeing wrong behaviour on https://keymanweb.com/?version=17.0.228#km,Keyboard_khmer_angkor on Chrome/Win10?

**Comment by ermshiperete** [comment]
https://keymanweb.com/?version=17.0.228#km,Keyboard_khmer_angkor works on Chrome/Win10, Firefox/Win10, and Chrome/Ubuntu22.04. It doesn't work correctly on Firefox/Ubuntu22.04 (nor does [12.0.106](https://keymanweb.com/?version=12.0.106#hy,Keyboard_basic_kbdarmw)).

**Comment by ermshiperete** [comment]
I created #10261 to track the problem in Firefox.

**Comment by jahorton** [comment]
I decided to do some investigation here and found one possible avenue forward.

https://github.com/keymanapp/keyman/blob/f6e87ef7986b79d8bf17efbc838641d427d6e488/web/src/app/browser/src/hardwareEventKeyboard.ts#L211-L216

Changing `& 0x60` to `s.isModifier` is sufficient to get the modifier keys tracking again.  That said, I don't know if this breaks other things - only that it does get the keys tracking.

With the tracking restored, there _is_ something else that seems... odd... but quite possibly intentional.

CTRL + K_A acts as if the CTRL isn't there - same for ALT.  Of course, we _are_ setting the `Lmodifiers` entry to 0 in the bit seen above, but even when the original value of `s.Lmodifiers` is preserved, CTRL and ALT are _still_ ignored.

Something important to note:  for these _old_, 1.0 keyboards, the virtual-key flag (0x4000) is generally missing from keyboard rules... and the `LisVirtualKey` flag above is set to false, whereas I think it's nearly always true in modern KMW.

https://github.com/keymanapp/keyman/blob/f6e87ef7986b79d8bf17efbc838641d427d6e488/common/web/keyboard-processor/src/text/codes.ts#L26

This fact is a major conditional in the main key-matching method that comprises keyboard rules:

https://github.com/keymanapp/keyman/blob/f6e87ef7986b79d8bf17efbc838641d427d6e488/common/web/keyboard-processor/src/text/kbdInterface.ts#L592

https://github.com/keymanapp/keyman/blob/f6e87ef7986b79d8bf17efbc838641d427d6e488/common/web/keyboard-processor/src/text/kbdInterface.ts#L606-L613

With `LisVirtualKey` set to `false`, the expectation is that the virtual-key flag's bit in key-match data specs for the rules, matching our legacy-1.0 event structure.  Note how no attempts are made to match modifier or state-key states - it's as if they're not _supposed_ to be handled.  Only the actual key-code matters.

Of course, I wasn't around back in the KMW 1.0 days, so I'm no authority on what was intended at the time... but my inference is that the behavior of CTRL+ALT being ignored may actually be correct, based on the evidence I could find in existing code.

**Comment by jahorton** [comment]
The `keyMatch` section above has been unchanged since the stable-10.0 days:

https://github.com/keymanapp/keyman/blob/f16872a99896a2fc208c68ac92a827820ab07e3f/web/source/kmwcallback.ts#L576-L583

The release-2.0 comparison:

https://github.com/keymanapp/keyman/blob/75864966f480c2773980faefe3d35021165d6d53/web/source/kmwcallback.js#L295-L305

(State-key matching [for CAPS, etc] was added in 10.0)

---

From KMW 2.0, for the first code block mentioned in my prior comment:

https://github.com/keymanapp/keyman/blob/75864966f480c2773980faefe3d35021165d6d53/web/source/keymanweb.js#L2676-L2681

Comparison:

https://github.com/keymanapp/keyman/blob/f6e87ef7986b79d8bf17efbc838641d427d6e488/web/src/app/browser/src/hardwareEventKeyboard.ts#L211-L225

That's as far back as I know how to dig.

**Comment by jahorton** [comment]
> I decided to do some investigation here and found one possible avenue forward.
> 
> https://github.com/keymanapp/keyman/blob/f6e87ef7986b79d8bf17efbc838641d427d6e488/web/src/app/browser/src/hardwareEventKeyboard.ts#L211-L216
> 
> Changing `& 0x60` to `s.isModifier` is sufficient to get the modifier keys tracking again.  That said, I don't know if this breaks other things - only that it does get the keys tracking.  (It works by ensuring we don't actually legacy-map ALT, CTRL, and SHIFT.)
> 
> With the tracking restored, there _is_ something else that seems... odd... but quite possibly intentional.

Now, for one argument toward this being _not_ intentional:  the original logic would _not_ remap any keys with a CTRL or ALT state to something the legacy keyboards would be compatible with.  That `0x60` check?

https://github.com/keymanapp/keyman/blob/f6e87ef7986b79d8bf17efbc838641d427d6e488/common/web/keyboard-processor/src/text/codes.ts#L14-L16

An active `CTRL` or `ALT` modifier would fail the conditional, meaning that the key events would not be in a format that the legacy-compiled keyboard could handle.  Now, there's no comment saying this was intended as a modifier kill-switch... it's just an alternate interpretation of the original logic and what it may have actually intended.

So... perhaps both the old and the new condition should exist?
