### ISSUE TITLE
bug(android): An error message is shown on the screen after changing the keyboard during typing

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10286]
### Describe the bug

I observed an error message appearing on the screen when I switched keyboards while typing.

### Reproduce the bug

1. Install Keyman 17.0.232-alpha.
2. Open Keyman In-App.
3. Download and install Cameroon QWERTY, Khmer_Angkor, and Tamil99Basic keyboards. 
4. Set any keyboard. (eg., Cameroon QWERTY).
5. Start typing rapidly. 
6. Click the globe key to change the keyboard. 
7. Continue typing rapidly. 

I noticed that an error message was displayed on the screen after changing the keyboard. 

I have attached the Video file as well as the Screenshot for reference. 

..keyboard error message1

https://github.com/keymanapp/keyman/assets/19683143/fc99fab2-7ac4-4adb-8eea-ad1bb0e75997

..keyboard error message2

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/296d5763-2d11-4b4c-9818-72333b65c05d">

### Expected behavior

No error message should appear during this process.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.232-alpha

### Operating system

Android 12, 13

### Device

Samsung Galaxy A23 5G Mobile

**Comment by jahorton** [comment]
Hmm, so the error triggered twice in that video, both times near the end - once for `khmer_angkor` (with pred text) and once for `sil_cameroon_qwerty` (without pred text).  In both cases... it seems that the error did _not_ occur immediately on switching keyboards, but after a moment instead.  (Could this be due to animation fade-in delay?  There's definitely fade-out delay.)

Note that 8 or 9 Khmer characters were output before the keyboard was swapped to the Cameroon keyboard, with at least one of these characters being typed either on the first error or after it.  Also, I believe that the first post-Khmer Latin-script letter was output completely before the error appeared, though I'm not sure about the second.

Just noting down these details for now in case they prove to be useful leads.  I can't say for certain yet whether they are or are not useful.
