### ISSUE TITLE
feat: Android 5th row number keys enable/disable

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#10303]
### Is your feature request related to a problem? Please describe.

In Android, there should be a way to enable/disable 5th row number keys in Keyman.
Keyboard height should promptly change with this settings.

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

**Comment by mcdurdin** [comment]
Thank you for the suggestion.

Unfortunately, this is not something that can be generic across keyboards, because it depends on the way each keyboard is designed. Some keyboards have 5 rows already, some have 4. I can't see a clean way forward in implementing this feature request without causing other limitations or problems.
