### ISSUE TITLE
chore(windows): Update the call stack of functions that end with RegSetValueExW to have const string 

### ISSUE THREAD

**Issue by rc-swag** [keymanapp/keyman#10625]
This issue originally questioned why the `value` of the option was being copied (wscpy_s). instead of passed through to `SaveKeyboardOptionCoretoRegistry`. On inspection the reason is that it would require casting away const, which should never be done.

**Comment by mcdurdin** [comment]
> On inspection the reason is that it would require casting away const, which should never be done.

I took a look at the function chain here:

1. `SaveKeyboardOptionCoretoRegistry` calls 
2. `IntSaveKeyboardOptionCoretoRegistry` which calls 
3. `RegistryFullAccess::WriteString` which calls 
4. [`RegSetValueExW`](https://learn.microsoft.com/en-us/windows/win32/api/winreg/nf-winreg-regsetvalueexw), which takes a const `data` parameter.

So the problem is that we are losing the const early in the chain. I think we should add const to those parameters in the functions referenced above, and then we should be able to avoid the alloc+copy+free pattern in `processPersistOpt`. :grin:
