### ISSUE TITLE
bug(android): typing a character when text is selected deletes past the end of the selection

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#10645]
Keyman 17.0.256-alpha on Android, Samsung A53/5G phone, Android 14

If you make a text selection (all apps that I've tried), and then type a character, Keyman deletes the selection, and then continues past and deletes too much.

https://github.com/keymanapp/keyman/assets/4498365/11129486-5a8f-48d1-a140-3126d27da29a

**Comment by jahorton** [comment]
For contrast:

![selected deletion](https://github.com/keymanapp/keyman/assets/25213402/e7ffcc4b-b5f6-43d2-b30b-536ae7059a64)

**Comment by jahorton** [comment]
Also for contrast:

![IMG_3039](https://github.com/keymanapp/keyman/assets/25213402/b71b1fc8-e719-4b98-aaea-fc6f5038f379)

![IMG_3040](https://github.com/keymanapp/keyman/assets/25213402/085aa25f-f9e4-40e5-b904-be81b47272de)

Looks like iOS deleted the whitespace before the selected block?  I might need to double-check that all lines up correctly there.  _Definitely_ less severe than what we see on Android, though.

**Comment by darcywong00** [comment]
I remember the last time I tried to dig into something like this (backspace on selected text), I got totally lost in KeymanWeb and transforms.

**Comment by jahorton** [comment]
The repro works well enough within the app; the cause appears to be that KMW is saying to perform right-deletions, as if the caret were at the left side of the selection.

![image](https://github.com/keymanapp/keyman/assets/25213402/239fc329-6e63-431d-a7d7-0f952d1ae9ff)

So, the selected text is deleted, then the same number of characters are deleted off the right-hand side.

I did notice the relationship of selected text to right-deletions when working on... something else recently (I forget what), but didn't make changes at the time because I didn't want to break related Android stuff.  Well... looks like "related Android stuff" was actually broken anyway.
