### ISSUE TITLE
bug(ios): The Keyman banner only appears in landscape view after one additional device rotation

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#10847]
### Describe the bug

I noticed that the Keyman banner only appears in landscape view after one more rotation of the device.

### Reproduce the bug

1. Install Keyman 17.0.275-beta 
2. Open Keyman In-app. 
3. Download and Install sil_ipa or any other keyboard that does not have a dictionary feature. 
4. Enable as a system-wide keyboard. 
5. Open any browser. 
6. Change the Orientation into Landscape. 
7. Long the press the globe key. Switch Keyman Keyboard. 
8. Switch to sil_ipa keyboard. 

Here, I noticed that the Keyman banner was missing. 

9. Change the Orientation to Portrait. Revert to Landscape view. 

Now, the Keyman banner is visible. Seems to be a cosmetic issue. 

https://github.com/keymanapp/keyman/assets/19683143/115bf8f9-485f-4a58-9448-d85bda3e475f

### Expected behavior

Keyman banner should be visible for the keyboards (that do not have dictionary features) in landscape mode. 

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.275-beta

### Operating system

ios 15.5, ios 17.0

### Device

iPhone 13 Mobile device, iphone 15 Pro Max Simulator (iOS 17.0)

**Comment by jahorton** [comment]
It appears that the image banner is not set initially within the system keyboard if the first loaded keyboard has an associated lexical model; inspection shows that the "blank" banner is still set as the inactive banner type in that case.

Further inspection, into ios-host.js, shows something funky:
https://github.com/keymanapp/keyman/blob/0d2e044c5ae24d444f999a6857074c67e41181a2/ios/engine/KMEI/KeymanEngine/resources/Keyman.bundle/Contents/Resources/ios-host.js#L75-L80

There's no reason to condition how the inactive banner is set based on whether or not the _current_ banner displays suggestions or not.  If the input parameter is `false` (i.e: "prediction text isn't on"), this would prevent the image banner from taking prepared for future use.  If the method is _not_ called again on keyboard swap unless an orientation change happens - that would cause the error of the missing banner.

The "bad aspect ratio" issue is a separate matter, likely due to some sort of timing related issue with when the banner-image data is forwarded.
