### ISSUE TITLE
bug(windows): can't uninstall a keyboard in Keyman 

### ISSUE THREAD

**Issue by Nnyny** [keymanapp/keyman#11005]
### Describe the bug

I try to uninstall [Greek Polytonic SA keyboard](https://keyman.com/keyboards/greek%20polytonic%20sa) but when I click on the uninstall button in Keyman Configuration, nothing happened. The keyboards are still there. But I can remove it from my Windows in Language setting. I can uninstall other Keyman keyboards normally except this one.

I also try to remove the associate language of these 9 keyboards and add it again. And this error appear which stop Keyman from running. 

![image](https://github.com/keymanapp/keyman/assets/123520338/380c1a6e-bcbf-4bf6-80d8-115d07d98fd1)

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.147

### Operating system

Windows 11 Home Single Language 22H2

### Keyboard name

Greek Polytonic SA keyboard

### Keyboard version

1.0

**Comment by mcdurdin** [comment]
Thank you for reporting this @Nnyny.

@rc-swag pinging you on this.

@Nnyny when you capture these reports, please also make sure you use the Copy to Clipboard button to copy the text from the dialog, and paste that text into the issue so we can easily lookup the code. Thanks!

**Comment by Nnyny** [comment]
Noted @mcdurdin!

**Comment by rc-swag** [comment]
The Error Identifier text: 68EB15CB2D314B1CCFD64C92ADDBDDA5 (for future [reference](https://keyman.sentry.io/issues/4392759823/events/68eb15cb2d314b1ccfd64c92addbdda5/?project=5983518&referrer=issue-list&statsPeriod=14d)) 
The crash here appears on setting the tray icon. The attempted keyboard uninstallation may have left the system in a bad state? Either way there should be a "check exists" to stop it from crashing.  

For the initial problem not being able to uninstall. Inspecting the `uninstall` button with devtools I can see the keyboard id is `greek%20polytonic%20sa` so I will explore if the problem is string parsing problem with the white space.

**Comment by Nnyny** [comment]
when I try to install it again, the keyboards appear double. 

![image](https://github.com/keymanapp/keyman/assets/123520338/32f23170-f700-47b4-a885-e047156b1f83)
