### ISSUE TITLE
bug(core): wrong use of UnicodeString, dead store with side effects in km_core actions_normalize.cpp  🌱

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#11067]
### Issue 1:  need to check output.length()?

What is `&&output[0]` (converting a char to a boolean) in this if condition supposed to mean? Hitting the case where output is of size zero, so `output[0]` is `kInvalidChar`  (U+FFFF)

https://github.com/keymanapp/keyman/blob/5b22c92116ded939bf44928acea5744cd75c9688/core/src/actions_normalize.cpp#L123

`output` is a UnicodeString, is it trying to see that output is not the end of string?

### Issue 2: dead store?

In the body of the loop referenced above,

https://github.com/keymanapp/keyman/blob/5b22c92116ded939bf44928acea5744cd75c9688/core/src/actions_normalize.cpp#L140

but, unless the function exits with failure, it will eventually call the following which overwrites `code_points_to_delete`:

https://github.com/keymanapp/keyman/blob/5b22c92116ded939bf44928acea5744cd75c9688/core/src/actions_normalize.cpp#L216

### Issue 3: `Expression, cannot decrement begin list iterator`

I'm getting this exception in Windows running `test_ldml`, specifically the test `tests/separate/key-8-osage2`.  

The site is the same spot I was going to put an assert in #11066, that is on the `p--` of:

https://github.com/keymanapp/keyman/blob/67838e60a224712079e4c8d8957b4eb4e92544b0/core/src/km_core_action_api.cpp#L59-L60

**Comment by mcdurdin** [comment]
Good catches.

> Issue 1: need to check output.length()?

Yes, looks like I was treating it as a c string rather than UnicodeString. Your suggestion looks correct.

> ### Issue 2: dead store?

AFAICT remove line 140 ` actions.code_points_to_delete++; ` is the correct resolution, this was missed by me in the cleanup and refactor.

> ### Issue 3: `Expression, cannot decrement begin list iterator`

This one, I need more context on to be sure what is causing it. Certainly we shouldn't be running off the front of the string so there is clearly a bug somewhere else which we need to track down. Are you happy tracking it @srl295?

**Comment by srl295** [comment]
yes on issue 3!

**Comment by srl295** [comment]
^ separate PR for parts 1 and 2

**Comment by srl295** [comment]
all fixed
