### ISSUE TITLE
feat(core,developer): 'other' in modifiers 🙀 

### ISSUE THREAD

**Issue by srl295** [keymanapp/keyman#11072]
Spec compliance: `modifiers="other"` is not supported.

Could we add a bitvalue `0x10000000` (to not collide with kmx_file.h) for the 'other' fallback?

(**Edit** it is `other` not `default`)

**Comment by mcdurdin** [comment]
I need some more context on this. How is modifiers=default not bitmask 0x00000000?

(Also not quite seeing how this relates to #11040?)

**Comment by srl295** [comment]
> I need some more context on this. How is modifiers=default not bitmask 0x00000000?

This will be an additional entry in the kmap, that is, if an explicit match isn't found, try again using modifiers=X (where X is 0x10000000 as proposed).

Bitmask 0x00000000 is for _no modifiers_ which may be a different layer.

> (Also not quite seeing how this relates to #11040?)

That issue refactored the layers, but that's not relevant to the _issue_, only to the implementation. Removed the reference.

**Comment by mcdurdin** [comment]
The bitflags in question are these, right?

https://github.com/keymanapp/keyman/blob/dc5ac443695f6a7f02aa8c8a1eb8a560793200eb/common/include/kmx_file.h#L283-L304

Those are 16 bit only, so we can start at 0x10000 for new flags in the KMXPlus code. Note that legacy .kmx only supports 16-bit because vk+modifiers are wedged into a single 32-bit value, but I don't think that's true for KMXPlus. We would need to make sure we add documentary evidence to kmx_file.h and other places where these bitflags are defined.

## codes.ts

https://github.com/keymanapp/keyman/blob/a404c20ddf12ffbe8dcd36bd51ad6343ec37cd9d/common/web/keyboard-processor/src/text/codes.ts#L9-L45

## kmx.ts 

(not unified with @keymanapp/common-types codes.ts due to history and dependency challenges, plan to unify in 18.0)

https://github.com/keymanapp/keyman/blob/699e1f350b963dd432c4e1717efdcaf8c53a1084/common/web/types/src/kmx/kmx.ts#L328-L364

## legacy_kmx_file.h

Another one we want to unify but tricky, hoping to drop legacy_kmx_file.h in 18.0.

https://github.com/keymanapp/keyman/blob/7adc9b5d955961c6cf3e6901923ab118e72adba7/common/windows/cpp/include/legacy_kmx_file.h#L300-L321

## kmxfileconsts.pas

Also hopefully disappearing in 18.0.

https://github.com/keymanapp/keyman/blob/7adc9b5d955961c6cf3e6901923ab118e72adba7/common/windows/delphi/keyboards/kmxfileconsts.pas#L115-L143

## C7043_ldml.md

https://github.com/keymanapp/keyman/blob/1ff2bfc4d7ce7b4c9149ac7c01989f233fc343c4/core/src/ldml/C7043_ldml.md#L462-L474

## KMBinaryFileFormat.h

Keyman Engine for Mac still uses this for loading kmx metadata

https://github.com/keymanapp/keyman/blob/7adc9b5d955961c6cf3e6901923ab118e72adba7/mac/KeymanEngine4Mac/KeymanEngine4Mac/KME/KMBinaryFileFormat.h#L128-L149

## etl2log load.cpp

Should be able to use kmx_file.h, really...

https://github.com/keymanapp/keyman/blob/a90e9f45f350cdce5d7b2b0e71242873a38f704c/windows/src/support/etl2log/load.cpp#L210-L224

# Related issues

* #10656 
* #8146
* #11104

**Comment by srl295** [comment]
OK, i'll start with `0x10000` then.

**Comment by jahorton** [comment]
> > I need some more context on this. How is modifiers=default not bitmask 0x00000000?
> 
> This will be an additional entry in the kmap, that is, if an explicit match isn't found, try again using modifiers=X (where X is 0x10000000 as proposed).
> 
> Bitmask 0x00000000 is for _no modifiers_ which may be a different layer.
> 
> ```
> <layer modifiers="none"> ...</layer>
> <layer modifiers="default"> ...</layer>
> ```

I feel like I've missed something here.  We're saying that `"default"` modifiers may be different from no (`"none"`) modifiers?

The closest thing I could find in the spec: https://github.com/srl295/cldr/blob/master/docs/ldml/tr35-keyboards.md#57-element-settings.  I see no such reference in either https://github.com/srl295/cldr/blob/master/docs/ldml/tr35-keyboards.md#58-element-keymap or https://github.com/srl295/cldr/blob/master/docs/ldml/tr35-keyboards.md#513-element-layer at this time.

But, `fallback="omit"` is a global, top-level setting, clearly for fallback behavior.  At that point, since we failed to match, why could we not just hard-set the modifier bits to 0x00000 and try again instead of using a unique bitmap here?  Or, have I missed recent changes to the spec that would clarify your intent here?

**Comment by srl295** [comment]
@jahorton srl295/master is way out of date.  Current proposed draft is:

https://www.unicode.org/reports/tr35/proposed.html - click through to Part 7. 

> I feel like I've missed something here. We're saying that "default" modifiers may be different from no ("none") modifiers?

Yes.  See example above.

**Comment by mcdurdin** [comment]
Note: the current draft says 'other' rather than 'default'

> There is one special case: the `other` layer matches if and only if no other layer matches. Thus logically the `other` layer is matched after all other layers have been checked.

**Comment by jahorton** [comment]
> @jahorton srl295/master is 2years out of date. Current proposed draft is:
> 
> https://www.unicode.org/reports/tr35/proposed.html - click through to Part 7.
> 
> > I feel like I've missed something here. We're saying that "default" modifiers may be different from no ("none") modifiers?
> 
> Yes. See example above.
> 
> Fallback was removed.

... wow, how did I miss that it was srl295/master and not unicode's master?  🤦 My apologies there.

**Comment by srl295** [comment]
> Note: the current draft says 'other' rather than 'default'
> 
> 

you are right!  Okay- will fix. 

> 
> > There is one special case: the `other` layer matches if and only if no other layer matches. Thus logically the `other` layer is matched after all other layers have been checked.
> 
> 
> 
>

**Comment by srl295** [comment]
> > @jahorton srl295/master is 2years out of date. Current proposed draft is:
> 
> > 
> 
> > https://www.unicode.org/reports/tr35/proposed.html - click through to Part 7.
> 
> > 
> 
> > > I feel like I've missed something here. We're saying that "default" modifiers may be different from no ("none") modifiers?
> 
> > 
> 
> > Yes. See example above.
> 
> > 
> 
> > Fallback was removed.
> 
> 
> 
> ... wow, how did I miss that it was srl295/master and not unicode's master?  🤦 My apologies there.
> 
> 
> 
> For future ease of reference: https://cldr-smoke.unicode.org/spec/main/ldml/tr35-keyboards.html#layer-modifier-matching
> 

Proposed.html is a stable url. The above is a staging server. 

> 
> 
> _That_ section clears up the reasoning; thanks.  Just had to find the right reference.

Welcome

**Comment by jahorton** [comment]
> > For future ease of reference: https://cldr-smoke.unicode.org/spec/main/ldml/tr35-keyboards.html#layer-modifier-matching
> 
> Proposed.html is a stable url. The above is a staging server.

It's the link I reached from the URL you gave.  Is a "stable" version of the precise, drilled-down link possible?  The URL forwarding scheme used for stable links isn't immediately clear to me.

**Comment by srl295** [comment]
> > > For future ease of reference: https://cldr-smoke.unicode.org/spec/main/ldml/tr35-keyboards.html#layer-modifier-matching
> > 
> > 
> > Proposed.html is a stable url. The above is a staging server.
> 
> It's the link I reached from the URL you gave. Is a "stable" version of the precise, drilled-down link possible? The URL forwarding scheme used for stable links isn't immediately clear to me.
> 
> Since the spec is so huge, it really helps to have direct links for discussion like this, hence why I included it in my comment.

Totally understandable. I was just trying to give some caution. No there isn't a stable link to the latest drilled-down subsection.  It's a gap.

**Comment by srl295** [comment]
fixed
