### ISSUE TITLE
bug(linux):  mk-build-deps: Unable to install keyman-build-deps at /usr/bin/mk-build-deps line 460.

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#11133]
Per https://github.com/keymanapp/keyman/actions/runs/8511119411/job/23310266045 and other jobs

**Comment by ermshiperete** [comment]
Keyman depends on `python3-magic` which can't be installed on (not-yet-released) Ubuntu 24.04 Noble because `libmagic1t64` isn't available for `amd64`. `libmagic1t64` is already in `noble-proposed`, but it seems some other packages still need to be updated to be fully usable (currently installing the version from `noble-proposed` will uninstall several other packages because of dependencies). I assume this will be solved in a few days.

**Comment by ermshiperete** [comment]
The problem has been fixed in Ubuntu 24.04, so Keyman 17.0.304 built successfully for Ubuntu 24.04 Noble.
