### ISSUE TITLE
bug: [mac] Installation process is incomplete and awkward

### ISSUE THREAD

**Issue by mailinglists35** [keymanapp/keyman#11395]
### Describe the bug

it only copies itself to '~/Library/Input Methods/Keyman.app' but that's it. you cannot find it in Spotlight search, in Launchpad, in Finder under Applications, nowhere.

It must be manually launched via Terminal, where it opens a dialog window saying to be granted access in system preferences and asks to restart system, and clicking ok shows the system settings open to Accessibility with Keyman not already there, you must manually add it and browse for it and already know where to look for it which most users will not be able to - because you must know to manually press shift-command-g in the file open dialog to enter ~/Library, yet still cannot see it in menu bar after all that because you require restart - I don't restart my mac unless there is a system software update, it works just fine opening and closing the lid when I don't use it!

that's NOT what I would expect from installing an app. this is the worst installing experience EVER since I started using macs five years ago.

### Reproduce the bug

download and attempt to install on macos ventura like you already did for 500 other previous apps you already installed in the past 5 years

### Expected behavior

just damn work

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [x] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16
### Operating system

22.6.0 Darwin Kernel Version 22.6.0: Mon Feb 19 19:43:41 PST 2024; root:xnu-8796.141.3.704.6~1/RELEASE_ARM64_T8103 arm64

### Device

      Model Identifier: MacBookAir10,1

### Target application

?!?!?!
### Browser

not relevant yet
### Keyboard name

the one that comes in the macbook air
### Keyboard version

?!?!??!
### Language name

ABC
### Additional context

?!?!?!

**Comment by mailinglists35** [comment]
using latest release on macos ventura on air m1

**Comment by mailinglists35** [comment]
this is in contradiction to [documentation](https://help.keyman.com/products/mac/current-version/troubleshooting/configure-security) which says

"How to configure macOS security options for Keyman
Keyman requires access to your keyboard in order to translate input. In macOS Catalina, there are three different Privacy settings you will need to configure in order for Keyman to work correctly:
Privacy / Input Monitoring
Privacy / Accessibility
Privacy / Files and Folders
The Keyman installer will configure these privacy settings for you, and prompt you to allow access for Keyman."

it only opens "Privacy / Accessibility"

it does NOT configure itself,
it does NOT ask you to toggle it in the list
it does NOT add to "Privacy / Files and Folders" and there is no way you can manually add it there, as there is no plus sign to add it there unlike for input monitoring and accessibility

**Comment by mailinglists35** [comment]
how do you make it trigger asking itself access to privacy - files and folders?
and what command is needed to whatever it needs to to without rebooting the mac?

**Comment by mailinglists35** [comment]
also tried beta and alpha, same behaviour

**Comment by mailinglists35** [comment]
so in effect I don't see it as a language item in input sources, nor as a process in activity monitor

**Comment by mailinglists35** [comment]
I can do 'open ~/Library/Input\ Methods/Keyman.app' it shows in activity monitor but not as language choice in input sources.

**Comment by mcdurdin** [comment]
This is a user support request, not a bug report. Please ask (politely) for help at https://community.software.sil.org/c/keyman, and remember that those who respond on that forum (and here) are volunteers and giving you their time for free.

**Comment by fleytman** [comment]
@mcdurdin Hello,

Thank you very much for your work on the project and for developing it on a voluntary basis. However, as a QA specialist, I would like to point out some issues that, in my opinion, indicate the presence of bugs.

1. Absence of the application in Launchpad and Spotlight: After installation, Keyman does not appear in Launchpad and cannot be located via Spotlight. This is a classic installation bug, significantly raising the entry barrier for new users. I would classify it as critical since it affects the maximum number of potential users who could be interested in the application and even become potential donors.
2. Unclear configuration of permissions: The lack of clarity regarding which permissions need to be granted without referring to the documentation is a configuration bug. I would assign it a high or even critical priority, as it requires users to take additional steps to find the necessary information.
3. Discrepancy in the documentation: The documentation states that access to "Files and Folders" must be granted, but the application does not appear in this section. It seems that this part of the documentation was relevant for a previous version of macOS. This is a documentation bug, and I would assign it a normal priority if it turns out these permissions are no longer required.

Given the above, I would suggest reopening this issue and addressing the indicated problems. We should not forget about the "survivorship bias": many users who managed to overcome the installation issues may not be motivated to report them, and those who could not might not think to leave feedback on GitHub.

Thank you for your attention and for the opportunity to make the project better!
