### ISSUE TITLE
Long press in the numeric/symbol layers does not work

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#115]
In the numeric/symbol layer, the long press doesn't produce an output. In the default layer, however, it works just fine.

**Comment by mcdurdin** [comment]
This issue would be specific to a keyboard, not a general issue in KeymanWeb. Let's have a look at the keyboard in question and if necessary open an issue on its repo.

**Comment by jahorton** [comment]
This occurs on multiple keyboards (EuroLatin 2 and Hanga, to name a few) and is not an issue when embedded in KMEA/KMEI... it's almost certainly a general issue in KeymanWeb.

**Comment by mcdurdin** [comment]
Yeah, so I spoke too soon... :) Found a bug in KMW. Fix on the way.

**Comment by mcdurdin** [comment]
The issue relates to the `nextlayer` property for keys. It is not being managed correctly for longpress keys (and even for other keys, the functionality is slightly dubious, because it appears that setting `nextlayer` at all blocks all output, which is not the intention of the code -- but that may be a separate issue -- ).
