### ISSUE TITLE
[iOS] crash in [PKService run] - no Keyman code on stack

### ISSUE THREAD

**Issue by tombogle** [keymanapp/keyman#1169]
![image](https://user-images.githubusercontent.com/4229598/45324066-196b3180-b51b-11e8-9968-39a6baa2b1ad.png)

This is a fairly common crash affecting iPhones and iPads across many versions of iOS. Since there is no Keyman code in the stack, I'm inclined to suspect some kind of memory/hardware issue. Looking at other similar reports on-line, I found people saying it was an Apple bug, possibly a failure that occurs when code executes too slowly (certainly a possibility for Keyman).

Here are some sites I looked at as part of my investigation:
https://stackoverflow.com/questions/32736214/ios-keyboard-extension-crash-before-any-of-my-code-runs
https://bugzilla.mozilla.org/show_bug.cgi?id=1347076 (I tried to reproduce on my tablet by flipping it over and over while attempting different operations in the Keyman app and while using the Keyman system keyboard).
https://forums.developer.apple.com/thread/71453 (WatchOS, but similar issue)

**Comment by tombogle** [comment]
Should we maybe use one of our Apple support requests to see if they can shed any light?

**Comment by jahorton** [comment]
Doing my own investigation on this, these are near-certainly crashes due to app extension init time.  We'd probably need to spend significant time optimizing the load and refactoring to allow temporary deferral of non-critical code.

**Comment by jahorton** [comment]
OK... took me a while to figure out how to actually use Apple's tools to profile the thing.  Instruments will not auto-attach to an app extension process on launch, so to get this data requires recording the timing across all processes, then filtering for our (SWKeyboard) process.

First Interesting section:

General app extension startup:

![image](https://user-images.githubusercontent.com/25213402/50585447-8da15a80-0ea7-11e9-8b4c-fad42b79e934.png)

The [FBSSerialQueue] block leads to a **deep** tree that results in the following after shaving 11 ms elsewhere:

![image](https://user-images.githubusercontent.com/25213402/50585133-28009e80-0ea6-11e9-8259-a799e67d4bce.png)

This image shows the timings for one load of the SWKeyboard - in particular, for the parts we control and are responsible for.

As seen in the image below, there's about 50ms associated with rendering:

![image](https://user-images.githubusercontent.com/25213402/50585171-541c1f80-0ea6-11e9-84ee-377bbb3e5b21.png)

There is one other interesting part here, though... `_dyld_start` performs the dynamic linking we need, and its use by the keyboard extension, a little further in...

![image](https://user-images.githubusercontent.com/25213402/50585364-2683a600-0ea7-11e9-8e70-2d361b59cfc7.png)

So, that bit about an `ImageLoader` parameter - we may be using nearly 280 ms just to load the top bar's image.  This load is clearly _not_ deferred presently; the top bar is always the first part to be displayed when using the system keyboard, and unlike the WebView's internals, failure to load this in time *will* crash the keyboard extension.

------

## What can we learn?

1) Loading the top bar image literally takes longer than *all* the rest of the SW Keyboard's startup time.  (Note:  41 ms of the 'main setup' code is used by `.setupTopBarImage`, and that's on top of the 281 ms for the _dyld_start portion!) That it's on this order of magnitude is concerning.

2) If we could delay initializing KMW's containing WebView, we can shave off another 50 ms - and with the recent keyboard refactor, I think such a deferral is possible.

Of course, given 320 ms vs 50 ms... I think I know where our focus should be.

**Comment by jahorton** [comment]
OK, did some more profiling work and realized something important:

* `dyld` is most likely what loads/launches the app extension.
  * I forgot that *image* could alternatively refer to *disk images* - I now think that's more what the `ImageLoader` stuff is about, especially since `dyld:initializeMainExecutable` is nearby.

Also, as there could possibly be some notable differences between Simulator and on-device behavior, I did a few new profiling runs.  Turns out we don't save that much time from disabling the top bar image.  Both of the following are with it disabled, corresponding to the second image of the previous comment. 

### Simulator

![image](https://user-images.githubusercontent.com/25213402/50624016-59cd4000-0f4e-11e9-9829-f286ec7d5d30.png)

Minor spoiler / important to note:  the simulator has full access to debug symbols, so this will be a handy reference.

### iPad (iOS 9.3.5)

![image](https://user-images.githubusercontent.com/25213402/50624094-2a6b0300-0f4f-11e9-8a99-0d1acad83f05.png)

### Analysis

First things first, there's a clear running-time difference between on-device and in-simulator; despite the emulation involved, development devices clearly have a speed advantage.

While there's a loss of debug information in the on-device image, comparing it to the simulator's data allows a pretty decent amount of information:

* `[UIViewController view]` block
  * This section performs the following tasks:
    * Initializes the `Manager` - `Manager.shared.unsafeMutableAddressor` (the first access of `static Manager.shared` for app-extension mode).
      * This is the biggest time consumer on loads.
        * 353 of the 729ms block is spent programmatically loading KMEI's bundle - see Constants.swift, `Resources.bundle`.  Far less time is spent accessing Keyman.bundle from within KMEI's framework bundle.
          - This is loaded by KMEI's bundle name, not from any sort of address within the 'main' app bundle... probably because Manager itself can't rely on a specific main-app scope.
        * 85 ms:  `Storage.copyKMWFiles(from:)` - retrieves (core, default) KMW resources from Keyman.bundle, sets up associated fonts.
        * 201 ms:  `Manager.synchronizeSWKeyboard()` - grabs local keyboards, etc data from the app-group shared space, bringing it into app-extension process-accessible space for use.
* `[InputViewController.init()` block - cross-reference with `0x1d2507` in the second image.
  * This section performs the general UI hierarchy setup.
  * Note the `KeyboardViewController.init` section, ranking around 386ms.
    * Cross-referencing details shows that the KeymanWebViewController (KMW's host/wrapper) is taking 157ms to initialize.
    * The other big time block - 161ms of this run appears to be setting up the XCGLogger.

**Comment by jahorton** [comment]
Closing in favor of #1492; we've done what we can for 11.0, as further changes will require significant restructuring of the app.
