### ISSUE TITLE
feat(android): Add option to turn off auto shift / auto capitalization

### ISSUE THREAD

**Issue by spiraldoll** [keymanapp/keyman#12154]
### Describe the bug

After updating to Keyman Android v17, when I use my English keyboard, the Shift key gets automatically pressed when the cursor is at the start of an input box or after a sentence-ending punctuation mark and a space. To me, this is an intrusive feature that adds unexpected behavior while typing, and I have had it turned off in every other keyboard.

The lack of a feature to turn off this functionality—at least as far as I can tell—is a dealbreaker for me for typing in bicameral scripts.

Can you please add the ability to turn off auto-caps?

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0

### Operating system

Android

### Device

Google Pixel 4a 5G running GrapheneOS (Android 14 derivative)

### Keyboard name

EuroLatin (SIL)

### Keyboard version

3.0.2

### Language name

English

**Comment by mcdurdin** [comment]
I hear you. 

Adding this as a generic user option is difficult because this is not a generic feature, but rather each keyboard can tailor its rules to match the needs of the target language.

Probably the best way to resolve this quickly is for you to build your own custom version of sil_euro_latin which removes the auto-capitalization sensing. I think this involves just commenting out two lines starting with: 'begin newcontext >' and 'begin postkeystroke >'. (If this seems too hard, reach out and one of our tech support team can probably help you.)

**Comment by mcdurdin** [comment]
I will go ahead and close this issue as I think the workaround will work best in your case, but please feel free to respond if you have any additional feedback or concerns.
