### ISSUE TITLE
feat(developer): Add Text Zoom Slider

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#12153]
### Is your feature request related to a problem? Please describe.

Working in the KMD Layout code editor, text often appears smaller than desired though set to a regular size like 12. When working with an unfamiliar script, the differences between symbols may be difficult to discern easily leading to the wish to temporarily enlarge (or _zoom_)the text to more carefully make an edit.

### Describe the solution you'd like

In any text views, I would like to be able to zoom the text (all text in the editor) in and out as easily as I can in MS Word and other applications.  Word has a zoom slider in the lower right corner of the status bar that allows for easy resizing, this would be ideal.  Other applications offer `A+` and `A-` buttons to do the same, this would be a secondary preference.

### Describe alternatives you've considered

Going through the View menu then the two separate font menus to set the size temporarily, and reset it later.  This gets tedious so I will instead copy & paste layout code into Word, edit there, and paste it back.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.328

### Operating system

Windows 11 Pro (22621.1702)

### Device

laptop

### Target application

N/A

### Browser

N/A

### Keyboard name

Any

### Keyboard version

Any

### Language name

Any

**Comment by mcdurdin** [comment]
The dual-font issue is something I also find irritating! 

I would probably lean towards adding the <kbd>Ctrl</kbd>+<kbd>+</kbd> and <kbd>Ctrl</kbd>+<kbd>-</kbd> hotkeys along with <kbd>Ctrl</kbd>+mouse wheel actions, which mimics VSCode and other editors. Currently, the editor zoom (only accessible through right-click, Command Palette, Zoom) doesn't control the 'character font' size, only the 'code font' size, so that's a bit useless!

**Comment by mcdurdin** [comment]
Dup of #10711, closing.
