### ISSUE TITLE
refactor(common): Consider moving from xml2js to fast-xml-parser

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#12208]
Consider moving from xml2js to https://www.npmjs.com/package/fast-xml-parser?

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/8616#issuecomment-1630013900_

This arose again in discussions on kmc-convert

@srl295 we should discuss

**Comment by srl295** [comment]
FWIW I use fast-xml-parser in https://github.com/unicode-org/cldr/tree/main/docs/charts/keyboards for those charts. But this is a simplistic use that is not attempting to validate. 

Our json validation is separate from the xml validation, though, so that should not be an impact. 
I'm sure there will be some bumps due to differences in handling.

fast-xml-parser is at least currently maintained!

**Comment by srl295** [comment]
I had split the PRs so that this isn't actually fixed, yet.
