### ISSUE TITLE
bug(developer): kmcmplib does not run a full keyboard repository test

### ISSUE THREAD

**Issue by markcsinclair** [keymanapp/keyman#12623]
### Describe the bug

If a full keyboard repository test is requested in `kmcmplib` with, say, `./build.sh --full-test test:x86` no extra keyboards are tested compared to running without the `--full-test` flag

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [X] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

**Comment by markcsinclair** [comment]
The problems seems to be a couple of bugs in the meson setup.

Changes required to get `--full-test` to run:

`kmcmplib/meson_options.txt`:
`option('--full-test', type: 'boolean', value: true)`

`kmcmplib/tests/meson.build`, line 106:
`if get_option('--full-test')`

**Comment by mcdurdin** [comment]
> If the `full_test` option is defaulted to true (in `kmcmplib/meson_options.txt`), sadly, 65 of 702 tests fail, although many of these seem to be memory allocation problems.

This is curious, because we are building all the keyboards regularly with the release build of kmc/kmcmplib, whenever we receive a new PR in the keyboards repository (most days). Looks like we need to get this resolved so we can track this.

**Comment by mcdurdin** [comment]
> If the `full_test` option is defaulted to true (in `kmcmplib/meson_options.txt`), sadly, 65 of 702 tests fail, although many of these seem to be memory allocation problems.

Turns out they are not memory allocation problems -- there is some misdirection in the reporting due to meson. The test was returning error 88 which means that the binary file mismatches with the fixture.

I found a regression in #12107 which causes 64 of the 65 fails:

https://github.com/keymanapp/keyman/pull/12107/files#diff-966fa269ec2e2dd3b5c40550dbe4df652e4f0f4253ae75552838852a0a6df629L11-R12

The `N` was accidentally replaced with `M`. Any keyboards which included a `nomatch` rule would fail with this. New PR on its way to address this (and --full-test will come as a separate PR too)

Still investigating the last failure.

**Comment by mcdurdin** [comment]
The final failure, for masaram_gondi, is because the keyboard source had non-BMP characters in the key part of the rule on line 215, which has been picked up by the 18.0 compiler in #11806: 

```
$keymanonly: if(opt1 = 'gondi') any(Vyanjana)"𑵄" + any(Vyanjana)	>	index(Vyanjana,2) U+11D45
```

The trick here is that the compiled fixture developer/src/kmcmplib/tests/fixtures/keyboards-repo/masaram_gondi.kmx is based on a [broken version of the keyboard source](https://github.com/keymanapp/keyboards/blob/965ef1941f20a3bc0cb5d405792b4984cc46cd52/release/m/masaram_gondi/source/masaram_gondi.kmn) in the keyboards repo ([fixed version](https://github.com/keymanapp/keyboards/blob/06cfd2d186c9d5bf2fe2888a4121c746e87f2868/release/m/masaram_gondi/source/masaram_gondi.kmn)), and updating to the fixed version will also trigger updates to a bunch of other keyboards. I think the simplest resolution is probably to skip masaram_gondi for 18.0.

Three PRs incoming
