### ISSUE TITLE
[linux] Packaging onboard-keyman

### ISSUE THREAD

**Issue by nikita-moor** [keymanapp/keyman#1411]
I see several commits mentioning OSK (such as #1337) and a separate repository [onboard-keyman](https://github.com/keymanapp/onboard-keyman). Could I recommend our users installing optional package Onboard extending main functionality?

From my former conversation with Onboard community, development of this application was discontinued in favour of [OnboardOSK](https://launchpad.net/onboardosk):

> Onboard not being compatible with newer Technologies like Wayland and GNOME3, a rewrite of Onboard was started under the name of OnboardOSK more than one year ago.

However, neither OnboardOSK is developing. So, are you goining to get your patchs into the upstream or support own fork? Id est, do I need to package `onboard-keyman` fork?

**Comment by glasseyes** [comment]
Yes, it is a useful program to have for keyboards that have an OSK.

As you say, upstream looks dead, so I don't think there is a point in trying to get the patch there (but am willing to be persuaded otherwise) but I'm going to try to get it into Debian/Ubuntu main onboard packaging. Onboard is still used for MATE and some other desktops on Debian/Ubuntu for the moment.
The modified onboard package will also be on the community repo packages.sil.org

I'd recommend seeing if the Arch onboard packagers/maintainers would be interested in the patch.

**Comment by nikita-moor** [comment]
Thank you for the explanation.
