### ISSUE TITLE
bug(developer): Package Details - image info size shows as 0x0

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#1457]
Originally reported by @DavidLRowe 
> Image size is listed as 0 x 0 even when image is selected.
Is that because it's a .jpg and not .bmp?

**Comment by darcywong00** [comment]
From what I can tell, that field reports the .bmp size (140x250 for splash).

We can make that clearer on 
https://help.keyman.com/developer/10.0/guides/distribute/tutorial/step-4

**Comment by DavidLRowe** [comment]
The case I was looking at when I reported this was one of the RAC keyboards, where the image was a .jpg and the size was reported as "0 x 0". The .jpg may have been larger than 140x250.

For a specific case, take the release/rac/rac_aer keyboard. The RAC.jpg image (in the welcome folder) is used for the splash image. It is 206x264, but Developer reports the size as "0 x 0" in the Package Details tab. Is this because it's a .jpg rather than .bmp?

Additional notes:
Since the image is larger than the 140x250, it is shrunk to fit (and gets distorted).

The creation of the image is described on https://help.keyman.com/developer/10.0/guides/distribute/tutorial/step-2

**Comment by mcdurdin** [comment]
Yes, it looks like the image size label reports only on .bmp format files, even though .jpg are supported.

**Comment by DavidLRowe** [comment]
.png images are also reported as `0 x 0` (Developer 11.0.1356.0). See keyboards PR 715 for specific example.

**Comment by mcdurdin** [comment]
Fixed, possibly in #7594.
