### ISSUE TITLE
[Developer] Installer for v11 doesn't see IE11

### ISSUE THREAD

**Issue by auralarch** [keymanapp/keyman#1458]
When trying to install the Alpha v11.0.85.0 of Keyman Developer in Windows 7 x64 Ultimate, the installer doesn't find IE (even though IE was currently running).
I'm not sure what it's looking for or where, but there may be a problem with that, unless IE11 is not supported.

The installer offers the solution to download IE5.5 but the link is broken, the page no longer exists.

**Comment by auralarch** [comment]
Reverted to IE8 (have rebooted multiple times throughout this process BTW) but the installer is still not able to discover IE.  This seems very strange to me.

What exactly is the installer looking for?  And where does it check?

**Comment by auralarch** [comment]
It appears as though the installer checks the registry to determine the presence of IE.  My registry seemed to have the correct key and value so I'm not certain why it's not recognized.
I did notice that there seems to be a contradiction over the minimum version of IE required.  One source reported v5.5 or higher, another source seems to report that v9 or above is required (perhaps my lysdexia mixed that up though and it's v9 or lower?).
And, as I mentioned the link encoded to update IE is dead and should be updated or removed.

I was able to install Developer with a bit of a work around.

1. I extracted the contents of the installer using the -x command line switch.
2. I selected "Troubleshoot Compatibility" from Windows Explorer Context Menu.  The troubleshooter ran and devised a solution and I ran the program to test the mitigation.

It installed successfully.   

Furthermore the application launched and seems to run issue-free (although Windows Update seems to believe that IE11 is installed- and I did install it; however, launching IE runs version 8.0,7601.17514).

I wonder if there isn't a more reliable check for IE?  Or if that isn't worth bothering with since the plan is to abandon IE.


Looking forward to finding out what I can do with Keyman!

**Comment by mcdurdin** [comment]
Glad you were able to find a workaround. 

A few comments:

1. Sadly, Keyman Engine still requires IE, even though nothing that Keyman Developer uses requires it, so we can't remove the dependency until that is completely resolved in v12.

2. The installer message and link are clearly quite out of date. We should correct that (although the priority is low because we are trying to eliminate the dependency altogether).

3. It sounds like something is confused on your system wrt IE versions. This whole mess is one of the big reasons we are trying to eliminate the dependency on IE by using Chromium. (The other being, of course, that IE is long dead and Edge cannot be embedded until very recent builds of Windows 10, which is just a disaster).

**Comment by mcdurdin** [comment]
Fixed by #3839.
