### ISSUE TITLE
[Web] KeymanWeb is not loading on iOS 9.3.5 browsers due to syntax error in goog.DebugLoader

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#1516]
With Developer version 10.0.1202.0, I can compile a keyboard, use "Test keyboard on web" and access the keyboard from an iphone4s using Chrome. 

When I install version 11.0.1301.0 (or 11.0.1302.0), this no longer works. The iphone seems to connect to the given address, but doesn't show the keyboard being tested. (It shows EuroLatin2 or some previously tested keyboard instead.)

Uninstalling version 11 beta and reinstalling 10.0.1202.0 restores the functionality.

OS: Windows 10 1803
One keyboard under test was sil_arabic_phonetic (Keyboards PR 588)

**Comment by mcdurdin** [comment]
I cannot reproduce this issue.

* Does it work from the same computer as you are running Keyman Developer on? (e.g. [use Chrome with mobile emulation set](https://help.keyman.com/developer/11.0/guides/test/how-to-test-your-touch-layout-in-the-google-chrome-mobile-emulator))
* Can you try again with latest beta (1306 at time of writing) and see how you go?

**Comment by DavidLRowe** [comment]
- I tried the Developer 11 beta (1306) and my iphone4s could not find the page. Returning to Developer 10, the iphone4s found the served keyboard. Lorna got the same results with her Android device: a keyboard served with Developer 10 was found by the Android device, whereas the same keyboard served with Developer 11 (though on a different computer) was not found.
- With Developer 11 beta (1306), a Chrome page on the same computer found the keyboard, but the keyboard displayed on the emulated iphone5 was the desktop keyboard rather than the touch keyboard defined in the keyboard.

(Happy to show you in person next week!)

**Comment by mcdurdin** [comment]
It looks like the problem lies with `goog.DebugLoader.` I am unclear as to why that is even bundled into the compiled KeymanWeb (it's huge, and pollutes the global namespace) ... and it has a problem:

```keymanweb.js:16082: SyntaxError: Strict mode does not allow function declarations in a lexically nested statement.

...
else {
            /** @type {!Array<string>} The scripts we need to write this time. */
            var scripts = [];
            var seenScript = {};
            var deps = this.dependencies_;
            var loader = this;
            /** @param {string} path */
>>>>        function visitNode(path) {
                if (path in deps.written) {
                    return;
                }
                // We have already visited this one. We can get here if we have cyclic
                // dependencies.
                if (path in deps.visited) {
                    return;
                }
...
```

Curiously, this error only arises on downlevel browsers such as Safari or Chrome on iOS 9.3.5. I haven't dug into reasons.

**Comment by jahorton** [comment]
Right.  I remember having to work around this before during the old TS conversion work - it's part of a Google library referenced by kmwapi.ts so that compiled keyboards don't break.  (It facilitates maintaining the 'short form' name for the keyboard callbacks.)  I thought I'd cut issues with that reference out, though...

Basically, it was originally put there to facilitate "advanced" minification one day, which would allow us to drastically shrink the compiled size of KMW.  That'd need a lot more work to properly support at this point though, so it may be simplest to just remove the library and handle the aliasing more directly.

**Comment by mcdurdin** [comment]
> so it may be simplest to just remove the library and handle the aliasing more directly.

I like this idea, especially as we are not currently realising the benefits at present. Fewer dependencies is always a good thing too :)
