### ISSUE TITLE
bug(mac): MS Word font menu or font size menu triggers OSK

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#1523]
**Describe the bug**
From https://community.software.sil.org/t/keyman-11-beta-feedback/1631/12 @dyacob writes

**To Reproduce**
1. Select from MS Word font menu, or font size menu
2. Keyman OSK pops up

**Expected behavior**
OSK shouldn't appear (keyboard shortcut?)

---
**Keyman for macOS**
 - OS: macOS
 - Keyman version: 11.0.200
 - Target Application: MS Word 16.16.5, Chrome 71.0.3578.98

**Comment by dyacob** [comment]
My testing details that leads to the unexpected onscreen keyboard popup:

- Device: MacBook Pro
- OS: macOS Mojave v10.14.2
- Target Application: MS Word 16.16.5, Chrome 71.0.3578.98
- Keyman: 11.0.200
- Language: English-US
- Keyboard: gff_amharic v1.7

**Comment by SabineSIL** [comment]
see #5856

**Comment by sgschantz** [comment]
Reproduced this with Keyman 18 alpha
With Keyman as the active input method and the OSK showing, clicking on the Word font or font size menu in the format ribbon causes the OSK do hide. The OSK reappears after releasing the menu.

The logs show that `activateServer` is called when the menu is clicked and 'deactivateServer` is not called until the menu is released. So there appears to be no way for Keyman to programatically distinguish this activity from that of a user who has switched from Keyman to another input method.

This issue is not unique to Microsoft Word alone. I was able to reproduce with Pages while clicking on the Format menu. Keyman was deactivated the entire time that the menu was open.
