### ISSUE TITLE
[Mac] Keyman Mac does not work with Oxygen XML editor

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#174]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Sunday May 28, 2017 at 02:12 GMT_
_Originally opened as https://github.com/sillsdev/keyman/issues/27_

----

see [tavultesoft forum post](https://secure.tavultesoft.com/forums/topic.php?ForumTopicID=461&ForumPostID=1571)

**Comment by tombogle** [comment]
Confirmed. It appears that when Keyman returns YES (handled) from handleEvent, Oxygen ignores that and outputs the normal default character. I can see in Console that Keyman is outputting the desired characters, but in most cases they seem to get clobbered by Oxygen. I couldn't get any Amharic characters to output. For Devnagari, sometimes the special characters would be output, but always along with the Roman characters. This is probably a lower priority compatibility issue.

**Comment by tombogle** [comment]
Should be reported to Oxygen as a bug.

**Comment by tombogle** [comment]
Reply to Adrian:
Yes, if Oxygen uses Java, then it will have the same problem as other Java-based apps. (I was the one who reported that issue.) If you'd like, feel free to use whatever influence you might have to convince them to fix their implementation so that Oxygen can work correctly with Keyman and other custom Input Methods.
The built-in macOS keyboards work in a totally different way, so they are not likely to be affected by this bug.

**Comment by mcdurdin** [comment]
Not fixed but tracking in #3935.
