### ISSUE TITLE
[Linux] Running keyman on KOSMOS (Arch Linux derivative)

### ISSUE THREAD

**Issue by glasseyes** [keymanapp/keyman#1762]
Marc wrote:

> I'd like to introduce you to Lyheng, who is working with Keyman on a Ubuntu(?) clone called KOSMOS:
> 
> https://github.com/Koompi 
> https://kosmos.kramaos.org/kosmos
> 
> We are having trouble getting Keyman running properly on the system; while it installs fine, we cannot see any Keyman keyboards in the input method configuration and it does not seem to allow us to switch to using Ibus. One other issue that we see is we cannot uninstall a keyboard from Keyman once installed.
> 

It appears to be based on Arch Linux rather than Ubuntu. Also it uses
the KDE desktop enviroment which hasn't been tried.
According to https://wiki.archlinux.org/index.php/IBus you need either
kimtoy or kimpanel depending on the version of KDE plasma to be able
to use ibus.

I can't find how to install IBus on KOSMOS. The "Software" program in KOSMOS
doesn't list ibus. I can't find where I should contact someone to ask
about that. The koompi forum https://forum.koompi.com does not exist.

I tried pi -i ibus but it complains about installing pygobject-devel
3.32.1 breaks dependency of python-gobject which depends on
pygobject-devel 3.30.4

**Comment by glasseyes** [comment]
@nikita-moor: Can you help with this? KOSMOS is derived from Arch so should be similar

**Comment by nikita-moor** [comment]
I will take a look.

**Comment by nikita-moor** [comment]
Complete guide on installing IBus and Keyman, and setting them up:

## IBus

Problem with dependecies, such as:

> "installing pygobject-devel (3.32.1-1) breaks dependency 'pygobject-devel=3.30.4' required by python-gobject".

could be solved by upgrading the system:

```
sudo pacman -Syyu
```

**Notice:** any OS based on Arch Linux should be regulary fully upgraded, because of rolling release concept.

Install IBus:

```
sudo pacman -S ibus kimtoy
```

Run KIMToy from the Applicaiton Launcher (use search field). It will add new icon into the tray, from it's menu activate "Autostart", and in "Configure KIMToy" go to the IBus tab:

* activate "Run IBus at startup"
* field "Arguments" set to "-drx"

Log-out from the desktop session and log-in again (or restart computer).

Now IBus on itself should work, you could add some exotic layout (Arabic) and test it in the Libre Office. In case it does not work (though I tested it diligently), read [Arch Linux Wiki][1].

## Keyman

Keyman is in the Arch User Repository (AUR). KOSMAS does not prodive tools to install aplications from AUR, so you need another package manager, for example `pamac`:

```
sudo pacman -S vte3 itstool vala gobject-introspection 

cd ~
wget https://aur.archlinux.org/cgit/aur.git/snapshot/pamac-aur.tar.gz
tar xvzf pamac-aur.tar.gz
cd pamac-aur
makepkg
makepkg -i
```

Run `pamac` from the Applicaiton Launcher (it is called "Add/Remove Software") or from console (`pamac-manager`). Go to the Preference menu (button with 3 vertical dots in the upper right corner) and activate "Enable AUR support". Return to the main window and search for "keyman", there should be two applicaitons:

* keyman 11.0.122-1
* keyman-onboard 1.4.1

(Packages `kmflcomp`, `libkmfl`, `ibus-kmfl` belong to an old version of Keyman, ignore them.)

Several dependencies of Keyman are not included into KOSMAS system, install them also from `pamac`:

* python-numpy (Repositories)
* python-magic (AUR)
* python-requests-cache (AUR)

Now all Keyman's utilities should work. You can install required keyboard using:

```
km-config
```

Layout will be automaticly added into IBus, if not — restart IBus (right click on the icon in the tray).


[1]: https://wiki.archlinux.org/index.php/IBus#Initial_setup

**Comment by mcdurdin** [comment]
Thank you @nikita-moor for such a comprehensive response!

**Comment by mcdurdin** [comment]
I've added this to the repo wiki and closing this issue: https://github.com/keymanapp/keyman/wiki/How-to-install-IBus-and-Keyman-on-Arch-Linux-and-derivatives
