### ISSUE TITLE
[Windows] Adds unwanted keyboards

### ISSUE THREAD

**Issue by joshisanonymous** [keymanapp/keyman#1775]
**Describe the bug**
When I install Keyman 11.0 Desktop with the SIL IPA keyboard, extra unwanted keyboard layouts are installed, as well, and things get wacky when I try to delete them. I get two layouts with the SIL IPA "language": US English and Undefined. If I delete US English (which does show up in language settings initially), I then suddenly have Undefined, French France, and French Caribbean associated with SIL IPA (both of which are layouts that I used in the past). However, these don't show up in language settings so I have no way of deleting them. If I uninstall Keyman and then reinstall, the two additional French layouts disappear then reappear along with the SIL IPA language. I'm not sure if this is something others have experienced with other layouts or not.

---

**Keyman Desktop:**
 - OS: Windows 10 Pro
 - Keyman version: 11.0.1356.0
 
---
 
**Keyboard**
 - Keyboard name: SIL IPA
 - Language name: Undetermined (it's the International Phonetic Alphabet keyboard)

**Comment by mcdurdin** [comment]
Thank you for your report. Yes, this is something that I have noticed as well. The issue is difficult to solve because it's part of how Windows manages keyboard layouts (Windows adds these layouts itself when we ask it to add the Keyman layout!). We are continuing to monitor this and will be aiming to get a more stable solution in 13.0.
