### ISSUE TITLE
[LMLayer] Disabling predictions doesn't disable them

### ISSUE THREAD

**Issue by rfaramir** [keymanapp/keyman#1946]
Disabling predictions, just like on Android (#1904), doesn't disable them (and doesn't actually make much sense!)

**To Reproduce**
1. Go to Settings->Installed Languages-><a language>
2. Make sure Predictions and Corrections are both on
3. [Test to make sure, if you like]
4. Go back to Settings->Installed Languages-><a language> and turn OFF Predictions
5. See error

**Expected behavior**
We would expect Predictions to not be on when they are turned off.
[I am a bit unclear how we know when this is on and off. With only Corrections turned on, Are  there no suggestions at all until what is typed is one character away from a dictionary word so  a Correction is suggested? Then again, Levenshtein should suggest every single-character word in the dictionary for an empty context, right?]

---
 - Device: iPhone 7
 - OS: iOS version = 12.3.1
 - Keyman version 12.0 beta (very first)
 - Target application: Keyman

**Comment by eddieantonio** [comment]
I think the LMLayer/banner right now supports three states:

 - [x] no predictions/no corrections (no banner)
 - [x] predictions/no corrections (banner)
 - [x] predictions/corrections (banner)

The LMLayer does _not_ support the following state:

 - [ ] no predictions/corrections (banner)

...because the correction mechanism _requires_ predictions. 🙃 

---

I think we should only allow the three states supported states in the UI for Keyman 12.0 (i.e., making it impossible to have corrections with no predictions).
