### ISSUE TITLE
[Developer] New Project wizard dialog doesn't show new folder in path

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#2044]
**Describe the bug**
New Project wizard dialog doesn't show path with the new folder that will be created

**To Reproduce**
1. Project, New Project, Basic, OK, to bring up New Project dialog.
2. Click on Browse button, browse to C:\Users\David\Documents\NRSI\keyboards_testing\release\x
3. Enter File Name: "xyz.kpj", Save

**Problem:**
Dialog comes up with message: The project will be saved at "C:\Users\David\Documents\NRSI\keyboards...\xyz.kpj". Continue?
It is unclear from this message whether the New Project wizard will place the files (including xyz.kpj) in the C:\Users\David\Documents\NRSI\keyboards_testing\release\x directory or in the C:\Users\David\Documents\NRSI\keyboards_testing\release\x\xyz directory. (From experience I know it is the latter.)

**Expected (desired) behavior**
My preference would be for the dialog to show the entire path, or else to abbreviate the path by omitting folder names from the beginning:
[existing] 
The project will be saved at "C:\Users\David\Documents\NRSI\keyboards...\xyz.kpj". Continue?
[suggested] 
The project will be saved at "...\NRSI\keyboards_testing\release\x\xyz\xyz.kpj". Continue?

**Screenshots**
![image](https://user-images.githubusercontent.com/8562172/64231214-4f76a200-cf32-11e9-82e4-a9d39c4a8fc0.png)

---
**Keyman Developer (please complete the following information):
 - OS: Windows 10 1903
 - Keyman Developer version: 11.0.1356.0

**Comment by mcdurdin** [comment]
Agreed that this is a bit confusing. In my mind, part of the problem is the overloaded meaning of the Browse dialog. It would be better if that Browse dialog was selecting only the path where the new folder for the project would be created; so you would choose `C:\Users\David\Documents\NRSI\keyboards\release\x` and then the `xyz` folder would be created there and all files placed inside `C:\Users\David\Documents\NRSI\keyboards\release\x\xyz`. That would also simplify the theoretical model of what the Browse button does as it no longer conflates selecting a location and choosing a keyboard id.

For a working example of what I mean, see the Browse dialog in the New Wordlist Lexical Model Project Template dialog in the latest 12.0 beta.

Ideally, Keyman Developer could also create a "Keyman Developer Projects" folder which would be created in your Documents folder, and which you could change in the Options. This would be the folder given for new projects by default. `<--` But this is a 13.0 feature idea rather than a bug fix; if you think this is a good idea, I can turn it into a feature request.

**Comment by DavidLRowe** [comment]
I agree that selecting the path where the xyz folder will be created (without having to name the .kpj file as well) would go a long way to solving this issue. (If you could display the path in a control that allowed the user to scroll to the end, that would be nice, but clicking on "Browse" or "Set path" or whatever would allow the user to see (and change) the path, so that's not as critical if the behaviour of the Browse button is changed.)

So, I would rank changing the behaviour of the Browse button (and perhaps renaming it to "Set Path"?) a medium priority. (It works as is, though it is a bit confusing. A user will take a guess and maybe try again or move a folder after the fact.)

Personally I would rank a "Keyman Developer Projects" folder fairly low. But that's just my opinion.
