### ISSUE TITLE
feat(developer): Add button to add existing wordlist to current lexical model

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#2185]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be an easy way to add a TSV file to the current Wordlist lexical model file.

**Describe the solution you'd like**
I'd like a button that says **Add existing wordlist...** to the model project page. This should:

 1. copy the `.tsv` into the `sources/` directory
 2. add it to the `sources` field in the `.model.ts` file

**Describe alternatives you've considered**
A work around is to add the file using "Project" > "Add to project..." > "Other files"

**Product context**
 - OS: Windows 7

**Additional context**
The current existing option: "New model..." and "Add existing model..." seem of limited usefulness compared to the ability to add a new wordlist to the existing model.

**Comment by mcdurdin** [comment]
Conceptually this seems nice. However, I think there a few potential issues with this:

1. There is a feature mismatch between 'add to project' and 'add to model.ts': currently adding a file to a project makes no changes to source files. I would be hesitant to change this conceptually.
2. We currently don't do any analysis of the .model.ts file -- this requires parsing and updating the file. I would prefer not to do this because it introduces external limitations to the format of the .model.ts file.

In some ways, it would be better to make the model editor more like the keyboard editor - a tab for model source and a tab for each wordlist. But this leads back to the issue above -- we don't parse the .model.ts file at present and I am hesitant to do so (and compiling + loading the .model.ts with a JS interpreter is a big project... which would have benefits but also significant complexity)

**Comment by anna-ka** [comment]
It seems to me that having the ability to just upload a .tsv or similar simple format is far preferable to uploading a .ts file. Creating and uploading a .ts file requires that a user knows TypeScript - this is a too demanding a requirement for a non programmer, not to mention the potential to upload invalid files and potentially security issues.

Adding to "model.ts" through a GUI editor is not really realistic for even a small real-world lexicon. It seems to me too time-consuming. Even a modest lexicon would contain several thousand tokens. For any language that is polysynthetic, it would be at least hundreds of thousands. It's too much to type through an editor. 

Besides, a .tsv file is such a common and straight-forward way to import weighted word lists.

**Comment by mcdurdin** [comment]
This was re-requested at LTCT2022. Specifically, copy .tsv to source/ folder (or same folder as .ts for simplicity); suggest we "`cleanid()`" name it too (spaces to underscores etc).

**Comment by mcdurdin** [comment]
Well @eddieantonio, it's been a while, but I've fixed this now :grin:
