### ISSUE TITLE
[Android] Start Catalog download during keyman startup

### ISSUE THREAD

**Issue by safolit** [keymanapp/keyman#2258]
**Is your feature request related to a problem? Please describe.**
Catalog download could be very slow on bad internet connections. 
Download es already moved to background process, that the user interface is not blocked.

**Describe the solution you'd like**
Start the background download on startup of the application, that it is already finished, when the user opens Language settings menu.

**Product context**
 - OS: Android 

**Additional context**
* Refactoring the `LanguagesSettingsActivity` to separate the `ResourceUpdateHandling` from the `Activity`
* This arises from #2247.

**Comment by safolit** [comment]
When the user opens the language settings page, keyman first updates the catalog. 
Second step is a check if there is an update available for currently installed keyboards and dictionary. The App asks the user, if the updates should be downloaded and installed. User can click update or later.
What do we want to do with this check? Do it on system startup as well? Doing something else? Probably marking the keyboard in the keyboard picker?

**Comment by mcdurdin** [comment]
The UX really needs to avoid getting in the user's way. These mockups show my current thinking:

Once an update is available, it appears as a standard Android notification:

![image](https://user-images.githubusercontent.com/4498365/68643891-54298900-0567-11ea-960f-2c34f17882be.png)

If the user taps that notification it shows details for the update and allows them to install (not mocked up).

If the user opens the Keyman app, they can also see the flag for updates at the top right:

![image](https://user-images.githubusercontent.com/4498365/68643944-7cb18300-0567-11ea-956f-a5857da0eda2.png)

And they can access the update from the menu:

![image](https://user-images.githubusercontent.com/4498365/68643961-8b983580-0567-11ea-8f8e-44e80f20b53d.png)

These mockups may not quite conform to the Android material design standard; they are intended to show the concept rather than the final implementation.

The first mockup assumes that Keyman can periodically check for updates in the background.

Another future option for highlighting availability of updates is shown here:

![image](https://user-images.githubusercontent.com/4498365/68644235-740d7c80-0568-11ea-9573-94dc327a1e7d.png)

I note this as future because it involves a lot more interaction with KeymanWeb plus careful consideration of how this interacts with Keyman Engine.

The online update check should be done by Keyman and not Keyman Engine.

**Comment by safolit** [comment]
@mcdurdin Do you want this issue to stay open, until the change in system keyboard, with a later PR?

**Comment by mcdurdin** [comment]
> @mcdurdin Do you want this issue to stay open, until the change in system keyboard, with a later PR?

I think we can move that into a separate issue given it is 'future' design, and then this issue can close with #2335.
