### ISSUE TITLE
[Web] [Developer] Regression: keyboards do not behave correctly with nul statement -> full context replacement

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#2261]
**Describe the bug**
'nul' sequence is not output text as expected

Keyboard code

store(consonants_ra_key)  [SHIFT K_N] [SHIFT K_B] [NCAPS K_Y] 
store(consonants_ra_code) U+0CA3 U+0CAD U+0CAF 

nul U+0CB0 U+0CCD + any(consonants_ra_key) > U+0CB0 U+200D U+0CCD index(consonants_ra_code,4)

Expected output in notes app in a notes with pre existing text 'ರ್' (without quotes) and keystroke (y)
is 'ರ‍್ಯ' (without quotes)

Actual output is 'ರರ‍್ಯ'

Somehow ರ is carried over to the output with 'nul' I think.

This was not the case until recent update iOS or keyman. I don't know what's trigger this.
It was functioning correctly before.

**To Reproduce**
```
store(consonants_ra_key)  [SHIFT K_N] [SHIFT K_B] [NCAPS K_Y] 
store(consonants_ra_code) U+0CA3 U+0CAD U+0CAF 

nul U+0CB0 U+0CCD + any(consonants_ra_key) > U+0CB0 U+200D U+0CCD index(consonants_ra_code,4)
```
create a test keyboard with the above code
create a notes in iOS 13.1.2 or iOS 13.2 in the below line
ರ್
place the cursor at the end of the above text
and tap key 'y'
actual output:
ರರ‍್ಯ

Expected output:
ರ‍್ಯ

iPhone/iPad/Android (please complete the following information):

iPhone 11 pro mac
OS: iOS 13.1.2 and iOS 13.2
Keyman version 12.0.53
Target application: Notes, mail, ...
Keyboard

Keyboard name: custom

**Comment by mcdurdin** [comment]
@jahorton can you triage and verify; when we fix this we should ensure we create a unit test for the scenario.

**Comment by jahorton** [comment]
I stripped the example code down a bit and was able to reproduce it in a desktop form factor in the Keyman Developer debugger host page - it's a KeymanWeb issue, so not something in the iOS code base.

To keep things slightly simpler, I dropped the modifiers like so:
```
store(consonants_ra_key)  [K_N] [K_B] [K_Y] 
store(consonants_ra_code) U+0CA3 U+0CAD U+0CAF 

nul U+0CB0 U+0CCD + any(consonants_ra_key) > U+0CB0 U+200D U+0CCD index(consonants_ra_code,4)
```

---

On further investigation, I've found the root of the issue.  The rule compiles with the following output code:

```
k.KDC(3, t);
k.KO(-1, t, "ರ‍್ಯ"); // Not exact, but fine for here.
```

There's one _small_ issue here - the context has size 2, not 3.  Slot 3 is the `nul`, which isn't something that can be deleted.  Of course, KMW _should_ be bounds-checking this anyway, so it's kind of a bug in both Developer and KMW.  As KMW isn't bounds-checking this during OutputTarget management, and the context-deletion method uses our custom `kmwSubstring` - which _does wraparound when the second parameter is negative_ - the context isn't deleted properly as a result.

So, now to fix that!

**Comment by mcdurdin** [comment]
Good analysis, thank you!

**Comment by MayuraVerma** [comment]
you could also use F key to type U+0CCD

```
store(consonants_ra_key)  [K_N] [K_B] [K_Y] [K_F]
store(consonants_ra_code) U+0CA3 U+0CAD U+0CAF U+0CCD

nul U+0CB0 U+0CCD + any(consonants_ra_key) > U+0CB0 U+200D U+0CCD index(consonants_ra_code,4)
```

**Comment by MayuraVerma** [comment]
@jahorton This is not resolved in iOS 13.0.20

**Comment by jahorton** [comment]
Interesting; I'm seeing it as "fixed" in iOS 13.0.22; I just tested with the original keyboard ruleset.

What are you getting now?  The same as before?  Maybe there's something extra at play.

**Comment by MayuraVerma** [comment]
I updated to iOS 13.0.22, it is still the same issue.

It is the same as before.

**Comment by jahorton** [comment]
This occurs with just the reproduction code you've isolated above on your device?  Or is this as part of a larger keyboard?

I have noted that sometimes there's a hidden character before the context, though that may be the result of pasting it in - the only error I can get is when a plain 'y' occurs because of said hidden character.

I've got a compiled version of your original reproduction code from above online at https://jahorton.github.io/ios_nul_test.kmp.  When I install that on our testing devices, we don't get `ರರ‍್ಯ` - we get just `ರ‍್ಯ` (if not `ರ್y` due to annoying hidden character, but that's a different issue).  Could you verify that the keyboard in that package still gives you `ರರ‍್ಯ`?  Maybe there's something off in how I compiled the reproduction code somehow.

If you do see the `ರ್y` version, just put the cursor before the test after pasting it in again, hit backspace a time or two (_after_ pasting), then move the cursor back and try again.

----

Just in case, here's the full .kmn for the compiled keyboard in that package:

```
c ios_nul_test generated from template at 2019-10-31 08:54:30
c with name "ios nul test"
store(&VERSION) '10.0'
store(&NAME) 'ios nul test'
store(&COPYRIGHT) '©'
store(&KEYBOARDVERSION) '1.0'
store(&TARGETS) 'any'
store(&VISUALKEYBOARD) 'ios_nul_test.kvks'
store(&LAYOUTFILE) 'ios_nul_test.keyman-touch-layout'

begin Unicode > use(main)

group(main) using keys

store(consonants_ra_key)  [SHIFT K_N] [SHIFT K_B] [NCAPS K_Y] 
store(consonants_ra_code) U+0CA3 U+0CAD U+0CAF 

nul U+0CB0 U+0CCD + any(consonants_ra_key) > U+0CB0 U+200D U+0CCD index(consonants_ra_code,4)
```

The .kvks file and touch layout are the default layouts provided by the standard template.
