### ISSUE TITLE
platform('native') does not exclude KeymanWeb in compiler.

### ISSUE THREAD

**Issue by erros84** [keymanapp/keyman#229]
It's starting to seem nearly impossible to work around KeymanWeb limitations without breaking something on other platforms or duplicating everything in the code. If I could compile for everything _except_ KeymanWeb, I would be _very_ happy.

With David's help and this page: https://help.keyman.com/developer/language/reference/platform , I'm currently using `platform('desktop native')` before any line in the KMN with LCTRL, RALT, CAPS, or NCAPS (which is most of them) to avoid: `warning 2098: Extended shift flags LALT, RALT, LCTRL, RCTRL are not supported in KeymanWeb`. This warning is not normally fatal, except when compiling for distribution.

This works to rule out KMweb and avoid the error, but I think it excludes tablet and phone, which is not intended (my external tablet keyboard DOES have a caps-lock key). I think the correct rule to exclude ONLY KeymanWeb would be `platform('native')`, but this does not succesfully exclude KeymanWeb in the compiler. I again get the following error: `warning 2098: Extended shift flags LALT, RALT, LCTRL, RCTRL are not supported in KeymanWeb`. Am I missing something, or is there a check missing in the compiler?

Currently this `platform` bug and the `nextlayer` bug are keeping me from completing my keyboard.  
https://github.com/erros84/keyboards/blob/master/cameroon_qwerty/source/cameroon_qwerty.kmn

keymandeveloper-10.0.931.0.exe

**Comment by mcdurdin** [comment]
As KeymanWeb Engine is used by both Keyman for Android and Keyman for iPhone and iPad, `platform('native')` is insufficient; you do need to include `platform('desktop native')`.

The warning helps to indicate a possible conflict between rules that arises if you use a Caps Lock rule within KeymanWeb (/iPhone/iPad/Android) -- the rule is still compiled, but without the Caps Lock flag, so it may match where you don't intend.

There is a little bit of nuance around external tablet keyboards. They are treated as 'desktop' keyboards because that is how they behave, and it makes the most sense for desktop-style rules to take effect. But at present, Caps Lock is not supported, because the implementation still uses KeymanWeb under the hood.

I think we could improve the wording around the `platform()` documentation to make this clearer. (I've noted this in the help.keyman.com issue list).

We are currently designing an new feature for Keyman to support left/right modifiers and Caps Lock, as browsers now make this information available (at the time the functionality was built, most browsers did surface return left/right modifier state or Caps Lock state).
