### ISSUE TITLE
[iOS] Multi-row longpress keys not contained within keyboard bounds

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#2299]
Issue reported from [community site](https://community.software.sil.org/t/ios-13-eurolatin-diacritics-blocked/2754)

> When EuroLatin (SIL) is chosen, some diacritics of some letters on the top row (i o u) can’t be displayed, as shown in the screenshot. My system is iOS 13.2. iPadOS does not have this problem because the diacritics all fit within one row.

**To Reproduce**
1. On iPhone device, have SIL EuroLatin keyboard selected as system keyboard
2. Go to [Community Site](https://community.software.sil.org/c/keyman) and click "+ New Topic"
3. Longpress on `i`
4. See error. Top longpress row blocked by site's "Done" banner

**Expected behavior**
All the longpress keys should be visible below the "Done" banner

**Screenshots**
![361d22fe6bd2ed379549a14f62e7e1f883d4c8f4_2_276x500](https://user-images.githubusercontent.com/7358010/68351234-6bb2dd00-0135-11ea-81e1-754e7143d012.jpeg)

---
**iPhone/iPad:**
 - Device: iPhone X (not iPad)
 - OS: iOS 13.2
 - Keyman version: 12.0 
 - Target website: [Community Site](https://community.software.sil.org/c/keyman) I'm assuming from Safari
 
**Keyboard**
 - Keyboard name: SIL EuroLatin
 - Keyboard version: 1.8.1
 - Language name: English

**Comment by jahorton** [comment]
My initial suspicion is that this is a side-effect from some of our architectural changes for version 12 - in particular, how the banner is now hosted on the html side of the keyboard now.  This probably resulted in a change of coordinates that may cause older bounds tests that would have prevented this to fail.

I severely doubt this is due to iOS 13 - it's more likely a version 12 thing, though this is only a prediction until we learn for sure which Keyman version the error-reporter was using.
