### ISSUE TITLE
[Android] Layer keys selectable via SHIFT-longpress do not have the special OSK font applied

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#239]
Pretty much what the title says. It results in situations like this:

![image](https://user-images.githubusercontent.com/25213402/29857871-039144b2-8d85-11e7-98b7-362522b19277.png)

The problem does not exist in native KeymanWeb; only in the Keyman App proper.

Seems to be suffering the same issue as #238.

**Comment by jahorton** [comment]
Further notes - it appears it is managed in native KMW's `osk.showSubKeys` method, line 539 by the `osk.setButtonClass` call.  This method is not called by the Android App, which has a separate method for managing "popup keys."  The keyboard.html function `oskCreatePopup` seems to trigger use of SpecialOSK if the `.sp` property of a subkey is either 1 or 2.  Extending this to include the values 3 and 4 (corresponding to the subkeys, I believe) isn't enough to fix the issue, though.

**Comment by darcywong00** [comment]
@jahorton from https://keymanweb.com/?tier=alpha#fr,Keyboard_french (engine/10.0.62)
![kmw longpress shift](https://user-images.githubusercontent.com/7358010/36624901-58e51034-1948-11e8-9536-665e0aad1a38.png)

The longpress on SHIFT also looks incomplete. Shouldn't the first key be a "SHIFT" arrow instead of a box to match the default layer?
