### ISSUE TITLE
[web] Not enough space allotted for display of wide character

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#2411]
**Describe the bug**
Not enough space is allotted for display of two-letter combination in longpress list.

**To Reproduce**
1. Load the Landuma keyboard (see notes under "Keyboard" below) into Vivaldi or Chrome browser.
2. Use F12 and select "IPhone 5/SE". Use F5 to refresh to get iPhone display. (see screenshot 1)
3. Press and hold "gb" key to see longpress display
4. Notice that "gb" is truncated to "g", "GB" is clipped on the right edge. (see screenshot 2)

**Expected behavior**
Each key (even if multiple characters) should be fully displayed.

**Additional note**
The touch keyboard changed between the original PR 915 and the current (hopefully final!) PR 988, to add an additional row of keys. The result is that the keys are now so small that with the iPhone 5 display, the "gb" doesn't display on the base key. (see screenshot 3)

**Screenshots**
screenshot 1:
![image](https://user-images.githubusercontent.com/8562172/70016709-ebb24400-1535-11ea-8b0a-f1446e3416e3.png)

screenshot 2:
![image](https://user-images.githubusercontent.com/8562172/70016733-ff5daa80-1535-11ea-8b15-2f266d96acdb.png)

screenshot 3:
![image](https://user-images.githubusercontent.com/8562172/70115195-d3185b80-1613-11ea-9e53-1b2b336d9501.png)

---
**KeymanWeb (please complete the following information):
 - OS: [Windows 10 1903]
 - Browser: [Vivaldi 2.3.1440.41; similar results with Chrome 78.0.3904.108]
 - KeymanWeb Version: [12.0.52.0 perhaps? launched from Keyman Developer 12.0.52.0]
 
**Keyman Developer (please complete the following information):
 - OS: [Windows 10 1903]
 - Keyman Developer version: [e.g. 12.0.52.0]
 
---
 
**Keyboard**
 - Keyboard name: [landuma]
 - Keyboard version: [1.1]
 - Language name: [Landuma]
 - Originally noted on Keyboards PR 915; this PR replaced by PR 988, which shows the same issue (commit: https://github.com/keymanapp/keyboards/pull/988/commits/457d9a13782e0ad5b90e91a344ccebdb44b09e20). Eventually this PR should be merged and will be available at https://keyman.com/keyboards/landuma

**Comment by jahorton** [comment]
https://github.com/keymanapp/keyman/pull/4270 and some of its predecessors have done much to remedy this issue.

Taken from Chrome emulation of iPhone 5 / SE (1st gen):

<img width="250" alt="Screen Shot 2021-03-05 at 10 35 04 AM" src="https://user-images.githubusercontent.com/25213402/110063881-8f744a80-7d9e-11eb-9adb-1789d534e032.png">

There's still a _slight_ bit of overrun on that `GB` subkey, but even that's a major improvement compared to the earlier image.  I wanted to compare against the other screenshots, but apparently that 5-row keyboard never became a thing?  I see that PR 988 was replaced with a different one later on.

So, instead... Khmer Angkor has long had a few keys that were big offenders:

<img width="247" alt="Screen Shot 2021-03-05 at 10 41 34 AM" src="https://user-images.githubusercontent.com/25213402/110064301-686a4880-7d9f-11eb-851c-23252a677cb1.png">

It's kinda subtle in that screenshot, but...

<img width="456" alt="Screen Shot 2021-03-05 at 10 42 43 AM" src="https://user-images.githubusercontent.com/25213402/110064360-889a0780-7d9f-11eb-8074-f50f0860dcf2.png">

Also, 

<img width="252" alt="Screen Shot 2021-03-05 at 10 46 23 AM" src="https://user-images.githubusercontent.com/25213402/110064636-1118a800-7da0-11eb-8857-176bb68aef87.png">

<img width="409" alt="Screen Shot 2021-03-05 at 10 46 16 AM" src="https://user-images.githubusercontent.com/25213402/110064641-14139880-7da0-11eb-8479-e071efca4f68.png">

On smaller devices, KMW now dynamically downscales overflowing keys so that they fit, only doing so for the keys that need it, and only as much _as_ they need it.
