### ISSUE TITLE
Designer Layout issues

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#252]
<a href="https://github.com/mcdurdin"><img src="https://avatars1.githubusercontent.com/u/4498365?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mcdurdin](https://github.com/mcdurdin)**
_Friday Sept 5, 2013 at 19:56 GMT_
_Originally opened as KD-8_

----

## Discussion Needed ##
* Need a way to specify Key Cap text in hex and/or set the font to the applied font for each key.

## Issue Fixed but needs Tidying ##
* ~~Still need the ability to specify an override layer so that standard key identifiers can be used to generate the normal result when shift is held from other than the SHIFT layer. This is especially needed when including punctuation keys in a symbol or numeric layer, to avoid the need for defining a new key identifier and duplicating the rules already added for the desktop mapping program.~~

## Issues to complete ##
* ~~(Minor) Change "Add/Remove Subkey array" to "Add/Remove Popup Keys" or something like that.~~ 
* Empty strings are added for width, pad and nextlayer fields when left blank, instead of omitting the keywords. KMW code has been modified to prevent errors, but it would be better (more compact file) if keywords were omitted if field is blank. 

## Issue for implement in the Engine instead of Designer/Layout
* ~~It makes sense for phones, not for tablets, for popup key arrays to include the base key. But on phones, there should always be a popup key array showing the base key, so the popup key flag should only be displayed (on phones) if the length of the popup key array is more than one.~~

**Comment by jahorton** [comment]
To the best of my ability to parse this in comparison to KMW's current state, the only possible issues remaining at this time are the following:

* Need a way to specify Key Cap text in hex and/or set the font to the applied font for each key.
* Empty strings are added for width, pad and nextlayer fields when left blank, instead of omitting the keywords. KMW code has been modified to prevent errors, but it would be better (more compact file) if keywords were omitted if field is blank.

Both merit further investigation and may already be implemented, but it'll take some work to verify each.

**Comment by mcdurdin** [comment]
Empty strings issue covered in #1831, and other issue is a little too vague and not very important. Closing.
