### ISSUE TITLE
change(mac): Stop storing keyboards in Documents folder

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#2542]
**Describe the bug**
Currently Keyman for Mac stores keyboards under the user's Documents folder. There are other locations better suited to storing program data. This also causes a security dialog to pop unnecessarily (asking for permission to access Documents).

---

**Keyman for macOS:**
 - OS: macOS Catalina
 - Keyman version: 13.0

**Comment by SabineSIL** [comment]
see #3883

**Comment by sgschantz** [comment]
This could be the cause of #181, #9060 and #10217. Access to the Documents folder is an obstacle to displaying the Keyman menu, which makes most of the configuration of the app inaccessible.

Because of frustration this may cause some users this should be a high priority for 18. The best location to migrate the keyboard files to would probably be under `\Library\Application Support` as documented [here](https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html).

**Comment by MakaraSok** [comment]
The most recent report on this issue: https://community.software.sil.org/t/keyman-configuration-not-available/8185.
