### ISSUE TITLE
[iOS] Eurolatin (SIL) long press menu does not appear

### ISSUE THREAD

**Issue by Kurdum** [keymanapp/keyman#2716]
**Describe the bug**
Long pressing keys with the Eurolatin (SIL) keyboard doesn't trigger the diacritic menu

**To Reproduce**
1. Select "English" with the "Eurolatin (SIL)" keyboard layout.
2. Switch to it
3. Long press a letter key 
4. Nothing pops up.

**Expected behavior**
With the Eurolatin (SIL) layout, every letter key should have a pop up menu for diacritics / accented letters. So such a menu should pop up.
**iPhone:**
 - Device: iPhone X
 - OS: iOS 13.4 (17E5233g)
 - Keyman version: 13.0.100
 - Target application: Notes, Keyman, etc.

---
 
**Keyboard**
 - Keyboard name: Eurolatin (SIL)
 - Keyboard version: 1.8.1 sil_euro_latin
 - Language name: English

**Comment by jahorton** [comment]
I'm not currently able to reproduce this issue; could you tell us a little more about when and/or how often this happens?  Or does the long press menu never show?

That said... I can't help but notice that you're using iOS 13.4, which isn't yet released.  I assume that means you're on its beta?  There's a slim chance that they might have broken something accidentally at the time (hence the 'beta' part), as my reproduction attempts are based on iOS 13.3.1 and 13.2.

**Comment by Kurdum** [comment]
That's possible that it's the newer 13.4 public beta that's broken something. Currently, on my device, it is basically impossible to trigger the long press menu. Certainly, if it's something that the official release of iOS 13.4 breaks, you should be able to reproduce the issue when it is released. I'll live with the issue for now!

**Comment by Kurdum** [comment]
Just updated to 13.4, can confirm that the issue persists; I'm unable to trigger the long press menu.

**Comment by jahorton** [comment]
Do any longpresses work within the app?  Can you trigger the popup keys on the default (SIL EuroLatin) keyboard?

We've had a report of some difficulty with other longpress situations, so this may help determine if the two issues are related.

**Comment by Kurdum** [comment]
No -- can't trigger the popup keys in the app either. So far none of the long presses work anywhere.

**Comment by jahorton** [comment]
Does the issue continue after force-quitting the app?  Please refer to https://support.apple.com/en-us/HT201330.

While it sounds like the app still responds, we can use this trick to perform the classic IT "have you tried turning it off and on again?"  For one of our other, similar reports, it sounds like this temporarily resolved the issue.  It was also useful for temporarily fixing #2184 while it still occurred on my personal device, and there's a pretty good chance the underlying cause is related.  (The device one day simply... stopped reproducing the issue, hence why that one never got fixed either.)  

Whether or not this actually _does_ temporarily resolve your situation would be useful information for chasing this down, and possibly even for getting some sort of reproduction that would greatly assist fixing the bug, though I'm not holding my breath on that last point quite yet.

There's also the slim probability of a corrupt install (where uninstalling and reinstalling would fix it), if you want to test this possibility and feel comfortable doing so, though I understand if not.

**Comment by Kurdum** [comment]
Not fixed by force closing or reinstalling.

**Comment by jahorton** [comment]
Once I updated my Xcode and Simulator to start testing this against iOS 13.4, I rapidly started experiencing the same issue.  iOS 13.3 doesn't experience it; there's something explicitly part of iOS 13.4 that must have changed, and it's blocking our app from being notified of longpresses in 13.4.  I can literally disable any potential conflicting gestures and they _still_ won't trigger when testing.

This is quite high on my priority list, but progress is pretty slow so far... it's looking to be something niche, subtle, or possibly both.

**Comment by mcdurdin** [comment]
See also https://twitter.com/MuradMoh/status/1245761635161182209

**Comment by jahorton** [comment]
Well, the good news is that I've narrowed down the cause and created a reproduction.  That can be found at https://github.com/jahorton/webkit-gesture-bug-repro/, and I'll be submitting it to Apple as a bug report.

Unfortunately, changing that aspect of our codebase is currently introducing other issues, the worst of which breaks predictive text and backspace within the system keyboard.  (There are one or two other issues this introduces.)  I'm trying to work around those issues now.

**Comment by mcdurdin** [comment]
Keyman 13.0.106 has now been released to the App Store and should work around this issue. We will continue to chase Apple for a better resolution because there are a number of advantages to the old model -- particularly for in-app keyboards -- but at least popups and longpress should work again!
