### ISSUE TITLE
feat(developer): allow `U_xxxx_yyyy` to output two Unicode characters

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#2858]
**Is your feature request related to a problem? Please describe.**
If a key on a touch layout needs to output two Unicode characters, the designer must assign a T_xxxx label, then use the .kmn file to cause that T_xxxx code to output the two Unicode characters.

**Describe the solution you'd like**
Just as using U_zzzz on a touch layout produces U+zzzz, using U_xxxx_yyyy would produce U+xxxx and U+yyyy.

**Describe alternatives you've considered**
The current use of T_ codes and code in the .kmn file.

**Additional context**
Would need to consider how to handle non-BMP characters.
Once you allow two characters, someone is sure to want three, etc.

**Comment by mcdurdin** [comment]
Thank you for the suggestion. I think this is a nice idea; would require changes to both Keyman Developer and KeymanWeb in order to implement. non-BMP characters would be handled transparently (`U+12345_12346`). I would suggest chaining to allow multiple characters would fit into this:  `U_12345_12346_12347`.

I've not put a date on implementation as we have our plates pretty full at present but will consider in the next round of issue triage.
