### ISSUE TITLE
Crowdin existing translation

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#2917]
**Describe the bug**
Crowdin doesn't have existing translation.

Should we copy them over to crowdin?
or is there any plans to make batch copy to crowdin?

**Comment by mcdurdin** [comment]
Yes, when we finish the work on Keyman Desktop localization conversion to crowdin, we'll copy in the existing translations. It's dangerous to do it too early, because if we have to change the structure, we'll lose any work that localizers make. We'll announce when the crowdin interface is ready for general use -- not yet 😀, because we still have to finish the preparation work for iOS, Windows, macOS and Linux!

I'll close this issue accordingly.
