### ISSUE TITLE
change(common/lmayer): make it simply the lmlayer scope

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#3124]
I'm not gonna lie; this is me being lazy. Basically, the `common/lmlayer` scope is too much to type in commit messages and in PRs; besides, the `lmlayer` is both a part of `web` and the `developer` tools. So I propose a new root-level scope: `lmlayer`. @mcdurdin, what are your thoughts on this?

**Comment by mcdurdin** [comment]
I think this opens a scope can of worms. 🥫 🍝

Right now we have top level scopes which correlate to the target projects, the top-level folders in the repository and the GitHub labels. That is: `android`, `ios`, `linux`, `macos`, `web`, `windows` and `developer`. Then we have a `common` scope for shared code, CI, etc. The subscopes are less well defined.

These top level scopes work well currently because at the end of the day we have to have a lot of platform-specific code and infrastructure, and it divvies up pretty well for maintainers etc. As we refactor, the `common` scope is going to grow and then at some point it may make sense to shift scopes around. But not yet...

So I don't really want to start adding component-type top-level scopes at this stage. I'd need to think through all the different components we have and I think it'd add a fair bit of confusion to the available scopes. I think the `common/lmlayer` scope is the right place for `lmlayer`.

Note: some of the scopes are currently somewhat rubbery because `web` components are used also in `android`, `ios` and `developer` 🐙. But Joshua is fixing that with his Web refactor, so some time soon the Web shared components will all be in `common`. Then, we'll probably need to have `common/core/web/keyboardprocessor` scope or similar.

Note that folder names are currently used to determine which tests need to be run. As more code moves into `common`, we may want to optimise these definitions in `trigger-test-builds.sh`.

As I noted, it might help to define all the subscopes more clearly and consistently between GitHub labels, folder names, and the repository. We could rename the `web-lm-layer` label to `common/core/web/lmlayer` ... okay, kidding, `common/lmlayer` will suffice? And fixup the rest of the GitHub labels to match the code scopes more precisely?

**Comment by mcdurdin** [comment]
One more minor tweak: `common/lm`. Why do we need to use the term 'layer'? 😁

Places where these scopes should appear and be consistent:
1. Folder names
2. Commit messages
3. `resources/shellHelperFunctions.sh` (currently includes `'lmlayer'` as a platform which is ... weird) -- this needs substantial refactoring due to confused use of "project" and "platform" terms.
4. `resources/git-hooks/commit-msg-defs` 
5. `resources/build/trigger-definitions.config`
6. GitHub labels
7. status.keyman.com

Items 3-5 need some refactoring to DRY them out... That may impact build scripts in other projects as well. I think I will put this up for discussion before making any changes (@jahorton and @darcywong00).

Verily The Beast It Doth Grow.

**Comment by darcywong00** [comment]
> Places where these scopes should appear and be consistent:

8. https://www.npmjs.com/package/@keymanapp/lexical-model-types (Keywords)

**Comment by darcywong00** [comment]
It seems to me the path of least resistance would be to modify the `commit-msg-defs` to accept `lmlayer` as a scope with the understanding it's somewhere in common/

**Comment by eddieantonio** [comment]
> I think this opens a scope can of worms. 🥫 🍝

Where do we keep getting all of these cans of worms? 😂 

> As I noted, it might help to define all the subscopes more clearly and consistently between GitHub labels, folder names, and the repository. We could rename the `web-lm-layer` label to `common/core/web/lmlayer` ... okay, kidding, `common/lmlayer` will suffice? And fixup the rest of the GitHub labels to match the code scopes more precisely?

Yes! This will alleviate the confusion (somewhat)!

> One more minor tweak: `common/lm`. Why do we need to use the term 'layer'? 😁

Even better! I like the sound of `common/lm`!

Though, yes, that's a lot of places to change things! 😅
