### ISSUE TITLE
[linux] Configure dependencies on onboard and ibus-keyman

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3223]
**Describe the bug**

Right now, users need to install all three of `keyman ibus-keyman onboard`. We should be able to configure the `keyman` package to depend on `ibus-keyman` and `onboard`, surely?

Ref: https://community.software.sil.org/t/unable-to-install-arabic-phonetic-keyboard-on-ubuntu/3434/4

---

**Keyman for Linux:**
 - OS: Ubuntu 20.04
 - Keyman version: 13

**Comment by ermshiperete** [comment]
That's mostly already dealt with in #2705. I think `onboard` is an optional dependency, i.e. things should work without it being installed, but I can add it as a recommended dependency (or something like that).

`keyman` already has `ibus-keyman` as a dependency and will install it. However, the only way the user could get into the situation he reported (and that Darcy reproduced) was if he forgot to do the first step from the instructions and add the ppa. In that case Ubuntu will install the keyman version that's included in the official Ubuntu package repos which is version 11 and depends in `ibus-kmfl`.

**Comment by mcdurdin** [comment]
I see. Is it possible to get the version in the official Ubuntu package repos updated to current stable? (and keep it updated?)

While onboard is an optional dependency, it would be better to install it by default unless instructed otherwise, if that is possible -- most users will want it and it won't hurt. IMO anyway.

**Comment by ermshiperete** [comment]
> I see. Is it possible to get the version in the official Ubuntu package repos updated to current stable? (and keep it updated?)

I guess that's something that @glasseyes  would need to do since he's the official maintainer of the [`keyman` Debian package](https://packages.debian.org/buster/keyman). Anyways, it'll be a long way since Ubuntu usually takes it's packages from Debian and I doubt they will update to a new major version for already-released Ubuntu versions. But I'm not very familiar with the policies and workflows in regards to packages in the official package repos.

> While onboard is an optional dependency, it would be better to install it by default unless instructed otherwise, if that is possible -- most users will want it and it won't hurt. IMO anyway.

Yes. I'll have to look into it - there are two categories for optional packages, and one gets installed by default (unless the user sets the option that he doesn't want them), so I think that would be the way to go.

**Comment by ermshiperete** [comment]
Added `onboard` as a recommended package to `keyman` (cf https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#control)
