### ISSUE TITLE
Allow Packing of Files with Non-Latin Characters

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#3502]
**Is your feature request related to a problem? Please describe.**
When trying to compile a package with a file having non-alphanumeric names (but valid letter characters) the following compile error appears:

gff_gurage.kps: Compiling package gff_gurage.kps...
gff_gurage.kps: Warning: The file ዘቢዳር-R.ttf does not follow the recommended filename conventions. The extension should be all lower case, and the filename should include only alphanumeric characters, -, _, + and .
gff_gurage.kps: Failure: 'C:\Users\Daniel Mekonnen\git\keyboards\release\gff\gff_gurage\source\gff_gurage.kps' was not compiled successfully.

**Describe the solution you'd like**
Allow filenames in UTF-8 where the characters are alphanumeric in the multilingual sense.

**Describe alternatives you've considered**
Transcribing files into Latin script appears to be the only option.

**Product context**
Windows 10.  Keyman Developer 13.0.111.0 .

**Additional context**
None.

**Comment by mcdurdin** [comment]
This is quite intentional; the problem is that adding Unicode filenames is not very backwardly compatible. This is particularly the case when using flash drives as is common in many parts of the world (although that's less of an issue inside a .kmp file). Restricting the character set to Latin has been a pragmatic way to avoid these issues, which are less common than in the past, admittedly, but I don't think we're quite ready to assume that all systems are going to work okay on all platforms...

The lower case restriction helps to reduce issues with case sensitive file systems (on Windows, we tend to get sloppy and reference files with differing case, e.g. in welcome.htm files, which breaks on Linux). 

I'm going to tag this as a Future issue because it would be nice to be able to allow any characters in filenames when we can be confident that they'll work everywhere we want them to.

**Comment by mcdurdin** [comment]
This is so tied to operating system and infrastructure that it's not something we can really fix ourselves. Maybe one day in the distant future...
