### ISSUE TITLE
[lmlayer] Deprecate and remove support for custom models

### ISSUE THREAD

**Issue by eddieantonio** [keymanapp/keyman#3576]
**Is your *anti*-feature request related to a problem? Please describe.**

When reviewing PRs that change the lmlayer and make changes to the `Model` interface, I always ask myself "what implications do these changes have for custom model authors?"

But do we even _have_ custom model authors? Or is it just the Keyman team that maintains model "templates" that implement the `Model` interface?

If we drop support for custom models, then I wouldn't have to keep asking myself this question, and we'll be more free to make changes to the `Model` interface and its interactions 😅 

**Describe the solution you'd like**

Custom models in the compiler to be deprecated in 14.0. When compiling custom models, it should issue a warning, essentially saying "you're on your own if things break"

**Describe alternatives you've considered**

We could create a _separate_ inteface for custom model authors to target that does not get the benefit of corrections; or perhaps, has to implement EVERYTHING including the model compositor and the correction engine.

Why reimplement EVERYTHING? Because the model compositor and the distance modler are coupled to the behaviour of the `TrieModel`.

@jahorton, what's your opinion on this?

**Comment by jahorton** [comment]
My opinion is "no."

I took great care in ensuring that the behavior of the distance modeler is _not_ coupled to the behavior of a `TrieModel`.  It is coupled to models with lexicons that may be represented via a `Trie` or may be 'traversed' in a similar manner.  

At first glance, that may not seem like much of a distinction... but here are a few reasons why it's actually significant. 

#### Notable `TrieModel` constraints _**not**_ assumed by the distance modeler:
- For the Trie-backed wordlist model, weighting is stored within the Trie on a per-word basis and used to generate probabilities.
    - The distance modeler doesn't care where or how the probability of any word is specified.
    - Presently, it doesn't even consider the word's probability; it simply returns the best prefixes.
       - That may be retooled later to simply ask the model "what's the probability of this word?", which need not be tied to traversal.
- For the Trie-backed wordlist model, each word must _actually exist_ within the backing Trie.
    - Suppose some sort of morphology-based model (say, based on FSTs) is developed for agglutinative languages.  Wouldn't it be possible to 'traverse' the lexicon as if it were Trie-backed in a generative manner by noting the morphological rules and tracking possible states?
    - Alternatively... even if we kept things 'simpler' and just used morphology for compression, we could still iterate over all wordlist entries without directly storing all words by their plaintext form.

If a model can represent its lexicon in such a way that it can efficiently (and internally) generate the set of allowed longer legal prefixes from a shorter prefix, its lexicon can be reasonably made "traversable" _like_ a Trie.

**Comment by jahorton** [comment]
Finally, let's take a step back and ask ourselves what would be 'necessary' and 'sufficient' to support a correction algorithm for any conceivable lexical model.

My assumption to this point:  
>    _Correction algorithms, by necessity, must know the set of possible valid corrections._
- If such an algorithm doesn't know what possibilities are or are not legal for a language, it would very easily provide invalid 'corrections' while also failing to provide others.
    - Exhaustively 'blacklisting' all impossible orthographic forms is prohibitively expensive.  
    - Thus, by nature, we assume a whitelist approach is necessary.

That last detail leads us to this question:

>    _"How would a correction algorithm consume a whitelist of legal correction targets?"_
- Obviously, we need _some_ way to iterate over that whitelist.
- Suppose that said whitelist were ordered at complete random.  How would that affect the algorithm's computational complexity (both re: time and memory)?
    - Requiring each step of the algorithm to iterate across a full lexicon would _rapidly_ become cost-prohibitive unless the algorithm could somehow avoid the need for 'steps' entirely.
    - Noting this, what then would be the most natural 'steps' an algorithm might take?

Which led me to the `LexiconTraversal` abstraction:  as text-correction algorithms tend to be based upon the Levenshtein distance (or similar), there is a natural need to consider two dimensions of possible 'step' iteration.
1. Appending all possible new characters to the end of an existing prefix  ("Breadth")
2. 'Iterating' over all possible prefix lengths.  ("Depth")

The _one_ distinction I can foresee model designers possibly wanting to make:  traversing on a morpheme level (prefix, root, suffix) instead of a per-character level.  But, I'd argue that such a case could be _mapped_ to function on a per-character basis... with a bit of care, of course.

------

That said, I may have missed something in my analysis, so please feel free to add in your thoughts on the nature of the problem.

**Comment by eddieantonio** [comment]
Okay, this makes sense. My major concern is making life easy for model designers, and making life easy for us, who are writing the documentation!

I've thought of how we can expose this to model developers, and I think I have an idea for a refactor in the future that would solve both making things easy for developers AND make our code more robust to things like null-checks and the like 🗡️ 

I'm gonna wait a bit for the dust to settle on some of the correction PRs though 😅
