### ISSUE TITLE
spec: Caps Lock layer for touch layouts

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3620]
This is part of a broader specification for Caps Lock support on touch devices. Development of this touches multiple components; each component will be implemented in a separate PR, referencing this issue.

## Related features

* #3621: spec: Start of text/sentence selects shift layer
* #3720: spec: Suggestions respect capitalization
* #5029: spec: multitap and flick for touch keyboards

## Introduction

A separate `caps` layer should be supported for touch layouts that provides support for Caps Lock semantics. This allows for slight nuances if there are differences between a `caps` and a `shift` layer, and also gives a clean pathway forward for existing keyboards that may have already defined `nextlayer` properties on each key.

If the keyboard defines layer controls in rules, these will not override `nextlayer` controls. According to [spec](https://help.keyman.com/developer/language/reference/layer), touch layout wins.

The `caps` layer, if present, will be accessible by double-tapping the Shift key. See #5029.

## C1.1 File Formats: .keyman-touch-layout changes

Changes to the file format and the JSON schema are required.

1. Required: Add a `caps` entry to the list of predefined layers. The templates will not include this layer by default, as ideally Keyman Developer will include tooling to help generate the `caps` layer from the `shift` layer.
2. Optional: Add a property for each layer called `nextlayer`. When set, for each normal key on that layer that has no `nextlayer` set, this would be applied by KeymanWeb. (this resolves the tedium as discussed here.) The templates would be updated to set `nextlayer` to `"default"` for `shift` layers.

###  Backward compatibility

Touch layout files that contain these features will be backwardly compatible with earlier versions of Keyman, with a graceful degradation of functionality.

* (if `nextlayer` is implemented) The compiler will transform the `nextlayer` property from layer-level to key-level at build time. Existing per-key `nextlayer` properties would override the layer `nextlayer` property.

## C1.2 Changes to Compiler

1. (if implemented) The compiler will transform the `nextlayer` property from layer-level to key-level at build time. Existing per-key `nextlayer` properties would override the layer `nextlayer` property.

## C1.3 Changes to Developer IDE

* Optional: The touch layout editor needs to surface the `nextlayer` property for each layer.
* Optional: A helpful function would be to be able to generate the `caps` layer from the IDE.
  * A caps layer’s initial form may easily be made by duplicating its base layer.
  * No special wizard or anything needed there.
  * Keys that have overridden modifiers may need manual correction.
  * nextlayer properties on each key may need manual correction.
  * Updates to the shift layer will not auto-propagate to the caps layer.
* Optional: Also helpful would be some validation tests for `nextlayer` property consistency.

## C1.4 KeymanWeb enhancements

* Required: KeymanWeb needs to support the Caps Lock layer.

**Caps Lock Interaction:** double-tapping Shift will switch to the `caps` layer -- see #5029.

**Caps Lock Presentation:** the `caps` layer Shift key needs treatment to differentiate from the Shift key on the `shift` layer. This will be through the caps indicator image defined as `*Caps*`. We should also consider colour styling, for example, this could be defined in the CSS with a rule for selector `.kmw-key-shift#caps-K_SHIFT`. The styling may differ per platform.

## Related Issues and discussions

* #246
* https://community.software.sil.org/t/how-to-return-from-shift-automatically-and-how-to-caps-lock-by-double-tapping/3469/3 
* https://community.software.sil.org/t/problem-with-caps-lock-output/3718
* [Original design document](https://docs.google.com/document/d/1J1WX41trb7GtPMM_VkfnV3XNOd3WFfHRlXdbf6YR7U8/edit#heading=h.vn6hrktkdivc)
* [RFC](https://community.software.sil.org/t/request-for-comment-specification-for-caps-lock-layer-for-touch-layouts/3890/2)
* [15.0 planning document](https://docs.google.com/document/d/1ojMK69QMFQzuZFfyGHphRO4eBiPJvx_nOoDndabVXsY/edit#)

**Comment by MattGyverLee** [comment]
## 1.1.1

### Considering Only letter and Number Keys:
If the base touch KB has a number row, in my understanding, 'buildCapsLayerFromShiftLayer' would be turned OFF for QWERTY and ON for AZERTY. It is the QWERTY world where Caps and Shift differ. If no number row is included, it may not matter.

For QWERTY: NCAPS (Numbers and Lowercase), NCAPS-SHIFT (Symbols and Uppercase), CAPS (Numbers and Uppercase), and CAPS-SHIFT (Symbols and Lowercase). This creates 4 distinct layouts, as the variable on a physical keyboard is whether CAPS affects a key, shift "always" does. 

Following AZERTY: NCAPS (Special and Lowercase), NCAPS-SHIFT (Numbers and Uppercase), Symbols and Uppercase), CAPS (Numbers and Uppercase),  and CAPS-SHIFT (Special and Lowercase). This creates only 2 distinct layouts. 

### Considering Punctuation keys:
If the main layer has, for example, period or comma, it may be up to preference whether those are affected by Caps.

### Multiplication of Layers 
Following 1.1.1, shouldn't there also be a CAPS-RALT, CAPS-CTRL, CAPS-SHIFT, CAPS-SHIFT-RALT, etc. ? My keyboard currently has desktop rules for CAPS-RALT, CAPS-SHIFT-RALT, NCAPS-SHIFT-RALT, and NCAPS-RALT. 

MSKLC's solution is pretty elegant that one can switch on or off "caps affects this physical key", and everything just works. Since a physical key has several layers, it works without having to multiply layers. With the Keyman touch having several layers with a collection of keys that may not correspond one-to-one by location, it gets muddy quickly. 

## 1.2 
This algorithm seems to work, as I can still override it with a next-layer. The developer question is what to do with, for example, an intervening hyphen in an all-caps word (does it stay on the caps layer).

**Comment by mcdurdin** [comment]
Thanks for the feedback @MattGyverLee.

At my guess, 90% of the Latin script keyboards are based on QWERTY and will benefit from the `buildCapsLayerFromShiftLayer` optimisation. I hope that the Keyman Developer experience is clean enough that creating a `caps` layer manually is not too onerous, for the remaining cases.

> MSKLC's solution is pretty elegant that one can switch on or off "caps affects this physical key", and everything just works. Since a physical key has several layers, it works without having to multiply layers. With the Keyman touch having several layers with a collection of keys that may not correspond one-to-one by location, it gets muddy quickly.

Yes, this is not really applicable to touch layouts where each layer is pretty independent of the others.

> The developer question is what to do with, for example, an intervening hyphen in an all-caps word (does it stay on the caps layer).

If there was a hyphen key on the `caps` layer, then it would probably not cancel Caps Lock. There are other questions around end-of-word triggering layer changes which need to be considered as part of #3621.

**Comment by MattGyverLee** [comment]
> At my guess, 90% of the Latin script keyboards are based on QWERTY and will benefit from the `buildCapsLayerFromShiftLayer` optimisation.

My Dad always tells me I see things backwards from the way he sees him, and maybe this is a similar case. For KBs with only alphabetic characters on `normal` and `shift`, yes, this feature would work 100%. 

The big question isn't really whether they are `QWERTY` or `AZERTY`, but whether they have any non-alphabetic characters represented on the base and shift layers, and whether you want _those_ affected by `CAPS`. (Only Alphabetic characters are `CAP`ped on Qwerty desktop, all keys are `CAP`ped on AZERTY desktop.) If your period key became a question mark in a shifted layer, you'd probably still want the period on the `caps` layer.

If you enabled `buildCapsLayerFromShiftLayer` on a `QWERTY` touch KB with numbers and punctuation, you would get unexpected results (your numbers and special character keys would also get `CAP`ped unless we had an override)...but it could work 100% for AZERTY where shift and caps are functionally equivalent on the desktop.  

My point was that you only want this feature to affect alphabetic keys on QWERTY, and to possibly affect all keys on AZERTY. I feel like I see this feature helping AZERTY far more than QWERTY (if any non-alphabetic characters are on `normal` and `shift` layers). Note in the screenshot below from Gboard, the shift and caps layers are NOT identical on the top row, but they could be on AZERTY if GBoard followed the desktop (it doesn't). This the rationale for my questioning.

![image](https://user-images.githubusercontent.com/986339/94432653-f9a11780-018e-11eb-89f5-97fe4047b426.png)

**Comment by mcdurdin** [comment]
> My point was that you only want this feature to affect alphabetic keys on QWERTY, and to possibly affect all keys on AZERTY. I feel like I see this feature helping AZERTY far more than QWERTY (if any non-alphabetic characters are on `normal` and `shift` layers). Note in the screenshot below from Gboard, the shift and caps layers are NOT identical on the top row, but they could be on AZERTY if GBoard followed the desktop (it doesn't). This the rationale for my questioning.

Righto. That makes sense. Most Keyman keyboards don't have that 5th row with digits, so the Caps layer would tend to be the same as the other Shift layer for those keyboards. But yes, differentiated Caps and Shift layers would make the `buildCapsLayerFromShiftLayer` feature significantly less useful, and I can't really see a generic way of making it work well in those circumstances. For differentiated Caps layers, the keyboard developer would need to design the layer themselves.

**Comment by mcdurdin** [comment]
One issue that needs discussion here also: does the Caps layer generate `[CAPS K_X]` or `[SHIFT K_X]` events? It should generate `[CAPS K_X]` but that probably requires additional code for a number of keyboards -- making the effort to add a Caps layer significant work and reducing the value of `buildCapsLayerFromShiftLayer` even further.

The `modifier` property for keys already has `caps` options available, but we need to make sure that the `caps` options are presented and linked to the `caps` layer when a `caps` layer is present. (Side note: the link between layers and modifiers is based entirely on the layer name and is a little obscure; having a little message that highlights that link would be helpful in the designer.)

This is leading me to think that perhaps we drop the automated generation at compile time. We continue to include a function in Keyman Developer to duplicate the Shift layer and apply the appropriate `nextlayer` removals, as a tool to assist the Caps layer building, but don't go further than that. Thoughts @jahorton, @darcywong00?

**Comment by jahorton** [comment]
What if we allowed a keyboard rule flag to the affect of "treat CAPS as SHIFT"?  For some keyboards, there are likely use cases where they need to be differentiated... how common are these?  My intuition (which could be wrong) expects such keyboards to be 'edge cases', where in 'common cases' there shouldn't really be much distinction.

Heck, we could even keep CAPS vs NO_CAPS while also aliasing the shift state, just in case someone does want CAPS rules... so long as they don't have separate requirements on SHIFT.  (CAPS w/o SHIFT illegal, NO_CAPS w/ shift illegal)

Just an idea, of course.

**Comment by mcdurdin** [comment]
> "treat CAPS as SHIFT"

This *could* work for simple touch layouts but not for desktop platforms. Caps applies only to the alphabetic keys. But even on simple touch layouts, there are often punctuation key[s] on the Shift layer which have different modifiers applied to them in order to give cross-platform consistency (e.g. think `.` and `?`), so that's also problematic.

> CAPS vs NO_CAPS while also aliasing the SHIFT modifier state

This would play havoc with existing keyboards also -- Shift and Caps are separate flags; on QWERTY for example, Shift+Caps+X = lower case x.

**Comment by mcdurdin** [comment]
This will not land in 14.0.

**Comment by mcdurdin** [comment]
> "treat CAPS as SHIFT"

Let's make sure we think about the [`&CasedKeys`](https://help.keyman.com/developer/language/reference/casedkeys) implementation when working through this. It may give us what we need.

**Comment by mcdurdin** [comment]
`buildCapsLayerFromShiftLayer` and "treat CAPS as SHIFT" are both being sidelined for now. The current iteration of this feature is much simpler, and we'll aim to build smarts into the dev tools rather than the runtime environments.

**Comment by jahorton** [comment]
Noticed something worth considering while developing #5451 under specific conditions:

- a keyboard actually has `CAPS` rules, and
- either: 
    - the caps-shifting key uses `K_CAPS`
    - or the caps-unshifting key uses `K_CAPS`

We would need _both_ keys to do so.  KeymanWeb emulates caps-state management for the OSK (because 'desktop'), and `K_CAPS` will trigger this state emulation.  Noting a would-be issue with the `khmer_angkor` keyboard, the visual aspects can be disabled safely for touch keyboards whenever the state doesn't actually matter for a keyboard's rules.  But, if it actually _mattered_ for a keyboard's rules, we'd need consistency to properly model the state.

**Comment by mcdurdin** [comment]
@jahorton I don't understand the scenario. What do you mean by "the caps-shifting key uses `K_CAPS`"?

**Comment by jahorton** [comment]
If you inspect the definition of `khmer_angkor`, the key to shift to the numeric layer has key id `K_NUMLOCK`.  Because of how Web-Core is currently built, this triggers emulation of the num-lock state.  In fact, that keyboard doesn't use `K_NUMLOCK` to return to the 'default' layer, so for each round-trip, the emulated state will toggle a single time.  Of course, `khmer_angkor` doesn't have any rules based on the num-lock state, so there's no impact for that keyboard.

But, if this were a keyboard meeting the conditions above... we'd have a quite different story.  Though... thinking about it, we may be safe disabling that state-key emulation on touch form factors?

**Comment by mcdurdin** [comment]
I think caps state management in mobile KMW should be related to the active layer rather than the id of the key that triggers it.
