### ISSUE TITLE
[windows] discrepancy in keyboard library on keyman.com and on Keyman Desktop

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3675]
**Describe the bug**
Sgaw Karen keyboard cannot be found in the Keyman Desktop, but it does exist in the keyman.com.

![image](https://user-images.githubusercontent.com/28331388/95298965-17652f80-08a7-11eb-9f2f-57ffc4b6a97f.png)

---

**Keyman Desktop:**
 - OS: Windows 10 Pro 1909 | Windows 10 Pro 2004
 - Keyman version: 13.0.112 | 14.0.154-alpha
 - Target Application: [self]
  
---
 
**Keyboard**
 - Keyboard name: Sgaw Karen
 - Keyboard version: 1.0
 - Language name: Sgaw Karen

**Comment by MakaraSok** [comment]
It looks like all newly added keyboard are not found in the Keyman Desktop keyboard download. 

- sil_buang
- sil_korda_latin
- sil_korda_jamo
- sil_tepehuan
- ...etc

**Comment by mcdurdin** [comment]
This is because the staging site does not automatically update with new keyboards. Currently, we only rebuild the staging site data when we update it, and not when keyboards are published.

Closing this as I have now updated the build scripts to notify keyman-staging.com as well; we'll see if that works better.
