### ISSUE TITLE
Keyman Crash in High Sierra (mac0S Version 10.13)

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#368]
The Keyman configuration doesn't respond.

**Comment by michaelvm** [comment]
from my console logs, when I try and open “configuration” for keyman, this is what I see: 
-[KMInputController showPreferences:]: unrecognized selector sent to instance 0x60000003f260 
error	14:15:59.944763 -0600	Keyman	<private> 
error	14:15:59.945382 -0600	Keyman	<private> 
default	14:18:33.131592 -0600	Console	[Error] invalid range passed to IMK -attributedSubstringFromRange : inputSource = keyman.inputmethod.Keyman

**Comment by tombogle** [comment]
There are three calls to attributedSubstringFromRange in the Keyman IM. Of the three, I suspect that the offending one is the one in updateContextBuffer, since it doesn't seem to check to ensure that the length is > 0. It's an unsigned int, so it can be negative, and I'm fairly certain that it is not a problem for it to be 0 in Sierra, but it's possible that that has changed in High Sierra. More likely, though, is that length is coming in as NSNotFound (max value of unsigned int), and passing that value to attributedSubstringFromRange may well throw an exception. More research needed...

**Comment by tombogle** [comment]
I get the same behavior and can see the "unrecognized selector" message in Console. I'm not getting the "invalid range" message, probably because I am using my current dev version, which doesn't attempt to retrieve the context until the user starts typing. In any case, it is probably unrelated. FWIW, I have a little test app based on Apple's official sample Input Method app (which someone put into Github), and when I try to open the Preferences window for it on High Sierra, nothing happens. No error in Console, but no preferences window appears.

**Comment by tombogle** [comment]
I have submitted a bug report to Apple https://bugreport.apple.com/web/?problemID=35422518 and also opened an incident report to request tech support.

**Comment by mcdurdin** [comment]
@tombogle : Apple bug reports are private. Would you consider submitting it via OpenRadar as well?

Can we give our users a workaround? e.g. an alternate method of opening Configuration?

**Comment by mcdurdin** [comment]
Please don't forget to remove the warning from keyman.com when resolving this issue.

**Comment by mcdurdin** [comment]
Community discussion: https://community.software.sil.org/t/solved-configuration-issue-with-macos-high-sierra/420
