### ISSUE TITLE
spec: Suggestions respect capitalization

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3720]
This is part of a broader specification for Caps Lock support on touch devices. Development of this touches multiple components; each component will be implemented in a separate PR, referencing this issue.

## Related features

* #3620: spec: Caps Lock layer for touch layouts
* #3621: spec: Start of text/sentence selects shift layer

## Introduction

When a user starts typing at start-of-sentence, currently KeymanWeb does not respect the start-of-sentence capitalization. As the lexical model dictionary ignores case for matches, we need a method of adjusting the suggestions to match the input casing -- Initial case or ALL CAPS.

A flag named `languageUsesCasing` on the model determines if casing rules should be applied to suggestions. If this flag is not set, none of the following functionality should apply.

A model can define an `applyCasing()` method consumed by `wordform2Key()`:

```ts
applyCasing(form: enum {lower, upper, initial}, text: string): string
``` 

Initial case will only upper case the first letter of the string. Lower case will lower case the whole string, and upper case will upper case the whole string.

A default implementation uses `toLowerCase()`, `toUpperCase()` and a simple `toInitialCase()` function. Developers may override `applyCasing()`, then should simply call `super.applyCasing()` after handling special cases.

## Example for Turkish

```ts
function applyCasing(form: casingForm, text: string, 
                     defaultApplyCasing: (form, text) => string): string {
    switch(form) {
    case casingForm.lower:
        return super.applyCasing(form, text
                    .replace(/I/g, 'ı')
                    .replace(/İ/g, 'i'));
    case casingForm.upper:
        return super.applyCasing(form, text
                    .replace(/ı/g, 'I')
                    .replace(/i/g, 'İ'));
    case casingForm.initial:
        return applyCasing(casingForm.upper, text.charAt(0)) + text.substr(1); 
    default:
        return text;
    }
}
```

Note: <code>toLocaleUpperCase</code>/<code>toLocaleLowerCase</code> are only supported in Chrome M58 on Android (we currently support M35), so we cannot use them at this time.

## Mechanism

**Start of token predictions:** KeymanWeb should report the current on screen keyboard layer to the LMLayer. For start-of-word, this will allow predictions to display with ‘initial’ casing.

To assist with this, ‘start of token’ will trigger a _predictive_ round of fat-finger execution based on the current on-screen keyboard layer.  The lm-layer will request this of Web.

**Mid-word predictions:** The LMLayer should check the current context token to determine casing requirements for suggestions. If the first character is lowercase, then predictions should be provided without case modification (e.g. this allows for proper names, acronyms, and special casing that are provided in the model, which covers a majority of languages).

Else, if the token is only one character long, or only the first character is upper case, then `applyCasing(initial)` should be applied for each suggestion, unless the first letter of the suggestion is already uppercase (again, allowing for acronyms, special cases).

Otherwise, if the token is all upper case, then `applyCasing(upper)` should be applied to each suggestion.

## Testing Casing

So long as the input text adheres to one of the three standard casing patterns, testing it against itself (via `input_text == applyCasing(case, input_text)`) should be mostly sufficient.  However, if the input is all lowercase (the default case), we should not modify the suggestion’s base casing.  If the suggestion’s base form in the lexical model is either `initial` or `upper`, that implies that the wordform is invalid for `lower`-casing.

So, in broad-stroke pseudocode…

```ts
if get_case_of(input_text) == lower
    return suggestion_text
else
    return applyCasing(get_case_of(input_text), suggestion_text)
```

## C3.1 Changes to .model.ts format

Additions:

*   `applyCasing`
*   `languageUsesCasing`

## C3.2 Changes to Compiler

Incorporates everything listed in C3.1.

May need additional validation:  the new function (`applyCasing`) must compile properly.

## C3.3 Changes to LMLayer

*   adds case-matching
    *   is called toward end of prediction process
    *   is a transform on the most likely suggestions
    *   merging of duplicate suggestions required after the transform (e.g. god->God, God)
*   Use of `languageUsesCasing`

## Additional notes

Future functionality plans remain in the Google Doc. We will revisit if/when we decide to implement.

## Related Issues and discussions

* #2638
* https://community.software.sil.org/t/problem-with-caps-lock-output/3718
* [Original design document](https://docs.google.com/document/d/1J1WX41trb7GtPMM_VkfnV3XNOd3WFfHRlXdbf6YR7U8/edit#heading=h.vn6hrktkdivc)
* [RFC](https://community.software.sil.org/t/request-for-comment-specification-for-suggestions-respect-capitalization/3973)

**Comment by MattGyverLee** [comment]
From reading this, it seems generally OK. 

If you can't use Locale, how are you generating the `.replace(/İ/g, 'i'));` pairs? Unicode often knows the lower/upper correspondence if they follow the rules. 

If applyCasing is enabled:

- A lowercase word such as `when` in the wordlist becomes `When` for initial and "WHEN" for caps.
- I think a proper noun (in the wordlist) would fall through correctly to autocorrect without being affected `Jesus/Jesus/JESUS`. This works because there is no rule forcing "Jesus" to "jesus", but you would have to make sure that identical proposals `Jesus/Jesus` don't show up twice.
- The challenge will be camelCase proper nouns such as iPhone, which will incorrectly transform to `iPhone/IPhone/IPHONE`. My inclination would be to scan and break `initial` if there is already an uppercase letter somewhere in the word. The odd part is that if someone types "iphone', you want it to suggest "iPhone".

**Comment by mcdurdin** [comment]
> * The challenge will be camelCase proper nouns such as iPhone, which will incorrectly transform to `iPhone/IPhone/IPHONE`. My inclination would be to scan and avoid `initial` if there is already an uppercase letter somewhere else in the word. The odd part is that if someone forcably types "iphone" or "Iphone", you want it to suggest "iPhone", meaning that the shift-state and autocorrect proposals need to be independent.

Good point, at least for this kind of marketing abuse of writing systems (harsh but fair I think). I think I have come across some languages that also do interesting things with mixed casing in words but that would mean a custom casing solution. 

BUT: I am wary of a one-size-fits-all exception for mixed case words in the wordlist, and I note that some devices already title-case `iPhone` to `IPhone` so it may be a small enough concern that we can ignore it for now.

Longer term, would a better solution here to be to have case rules in the word list, e.g. adding lower/upper/initial exceptions into the wordlist and use those rather than the algorithmic solution?

Or we could extend the `applyCase` function to have special cases for certain common words (nearly all of them being Apple creations??).

Exceptions make our life hard.

**Comment by mcdurdin** [comment]
> * but you would have to make sure that identical proposals `Jesus/Jesus` don't show up twice.

Noted and spec updated.

**Comment by MattGyverLee** [comment]
I hope this is the type of input you're looking for when you post a request for comment. 

> Good point, at least for this kind of marketing abuse of writing systems (harsh but fair I think). I think I have come across some languages that also do interesting things with mixed casing in words but that would mean a custom casing solution.

Yes, I agree that camelCase words are an abuse of writing systems, and that's why I specifically called out aPple (typo intentional). With that said, I haven't seen an orthography that uses non-initial caps outside of a proper noun (name or product). Have you? I guess that a language could choose to capitalize whole digraphs (mbouda->MBouda) or trigraphs at the beginning of the sentence, and that would require custom notation/programming.

> Longer term, would a better solution here to be to have case rules in the word list, e.g. adding lower/upper/initial exceptions into the wordlist and use those rather than the algorithmic solution?

Yes, there will eventually need a default algorithm and a way to generally and precisely override/define exceptions. I would envision that if a language has casing, there could be language-wide config and word-level overrides.

## Language-Level variables in the language model:
1. Use casing: Default: Yes
2. Should camelCased words get further modified by initial? Default: No
3. Should camelCased words get further modified by CAPS? Default: Yes
4. List any longer sequences (digraphs/trigraphs) that should get uppercased together. Default: single character initial caps as written in the example code.
5. List any word-forming characters that should be ignored or passed? One example would be the curved glottal (u02bc) letter in some languages that represents the Glottal stop and has no capital (we have an alternate version with a capital form uA78C/uA78B) that some language chose. Should ʼamal become ʼAmal ?
6. List any non-Unicode-standard capital/lowercase pairs. Default: None

## Word-Level Overrides in the language dictionary:
Somehow, spell out the 3 versions of any words that do NOT follow the above rules?
i.e.
| lower | initial | caps |
|---|---|---|
| * | iPhone | IPHONE, i</span>PHONE|
| durdin | DURdin | DURDIN|

## Caps VS Predictions??
On another front, I mentioned that the layer changes and predictive text need to be relatively separate. This will be important on a multilingual keyboard with less-defined languages.
Will keyboards without predictive language models be able to benefit from caps-layer shifting? i.e. jumping to the shift layer after sentence-final punctuation and jumping back.

**Comment by mcdurdin** [comment]
> I hope this is the type of input you're looking for when you post a request for comment.

💯% yes!

> With that said, I haven't seen an orthography that uses non-initial caps outside of a proper noun (name or product). Have you?

[Some KiSwahili writers](https://kamusi.org/content/swahili-kiswahili) sometimes use medial capitals. [Klingon when written in Latin script](https://en.wikipedia.org/wiki/Klingon_scripts) uses medial caps 😉.

> Will keyboards without predictive language models be able to benefit from caps-layer shifting? i.e. jumping to the shift layer after sentence-final punctuation and jumping back.

Yes. See #3621. A basic solution will be available in-keyboard; it is anticipated that a model will be able to provide more sophisticated mappings in the future. This will be implemented independently (and sadly, probably not in 14.0 as we just don't have the capacity).

**Comment by jahorton** [comment]
> Klingon when written in Latin script uses medial caps 😉.

Does Klingon, when written in Latin script, actually perform casing behaviors?  That is, is there case-based syntax when it's written in Latin?  If not, I think this case is safe to ignore.

> Some KiSwahili writers sometimes use medial capitals.

This one is definitely relevant... and helps further motivate an idea I've had stewing about supporting 'model options' at some point in the future.  (No GitHub issue exists for this... yet.)  The fact that there are distinct sets of preferences for use of casing, depending upon the KiSwahili writer, is a perfect motivating use-case for such a feature.

Of course, _that_ case also motivates yet another detail to consider:  wordlist entry 'annotations', for lack of a better term.

For the KiSwahili scenario, my interpretation of that link suggests that the casing behaviors are still regular and could be covered by the following:

- optional word property:  `casingRootIndex: number`
    - Default value:  `0`
    - Value for "KiSwahili":  `2` - the index of `'S'` within "KiSwahili".
- lexical model options:
    - "Capitalize proper noun prefixes"  (default:  `false`)
        - `true` - the "ki" prefix is capitalized as "Ki", despite being before the specified `casingRootIndex`.
        - `false` - the "ki" prefix (the part before `casingRootIndex`) remains uncapitalized.
    - "Capitalize proper noun root"  (default: `true`, is _forced_ to `true` if previous option is `false`)
        - `true` - Ensures the "Swahili" part is properly initial-capitalized
        - `false` - Leaves the "Swahili" part uncapitalized _so long as the "Ki" prefix **is** capitalized_.
        - The "forced" behavior would be in noted in the keyboard's documentation/help, not actually dynamically forced by the option UI.  At least initially, as that would require extra features far out of scope.

The model's `applyCasing` method would then read the model options and interpret the `casingRootIndex` annotation accordingly.

**Comment by jahorton** [comment]
Following from that comment...
- Assumption:  annotations would be represented as (optional) extra columns in the word's CSV row.

Interestingly, as I think about it... the `casingRootIndex` annotation idea _could_ cover words like the following:
- 'iPhone'
- 'iPad'
- 'iMac'
- etc.

But... would that cover _all_ potential cases that could arise?

Another potential 'annotation': `isCasingException`

Words marked with this annotation in the word list would be noted as exceptions to standard casing behaviors.
- As it's probably a "common enough" scenario, this 'annotation' should be officially supported and available as part of default behaviors.
- Once `isCasingException` is found within a CSV file, the following three columns define the word's casing behavior.  In order:
    - 'lower'
    - 'initial'
    - 'upper'

In order for `applyCasing` to process this, a new (optional) method should exist on the `LexicalModel` type:

```ts
function isCasingException?(word: string): boolean { /* ... */ }
```

This would be implemented by model templates, rather than defined on a per-model basis.  (If not provided, the default implementation may simply return `false` for all cases.)

`applyCasing` would also receive a slight modification:

```ts
applyCasing(form: enum {lower, upper, initial}, text: string, forKeying: boolean): string
```

The new `forKeying` parameter allows models to bypass casing exceptions for keying operations while not bypassing them for the actually-generated suggestions.  Otherwise, "iPhone" would 'key' to "iPhone" and not "iphone", preventing "iphone" from serving as a Trie 'prefix' for "iPhone" and possibly preventing the suggestion from occurring.

**Comment by jahorton** [comment]
> 1.    Use casing: Default: Yes

In our team discussions, we decided that this will actually default to `false` / "no".  This will require a few existing models to be modified accordingly, but it's a large assumption to make for a language.

> 4.    List any longer sequences (digraphs/trigraphs) that should get uppercased together. Default: single character initial caps as written in the example code.

I don't see what you're referring to by "as written in the example code", at least not for possible digraph/trigraph examples for this case.

> 5.    List any word-forming characters that should be ignored or passed? One example would be the curved glottal (u02bc) letter in some languages that represents the Glottal stop and has no capital (we have an alternate version with a capital form uA78C/uA78B) that some language chose. Should ʼamal become ʼAmal ?

We'd suggest a similar approach to the Turkish case for this scenario.  Loosely speaking:

```ts
function applyCasing(form: casingForm, text: string, 
                     defaultApplyCasing: (form, text) => string): string {
    switch(form) {
    case casingForm.lower:
        return super.applyCasing(form, text);
    case casingForm.upper:
        return super.applyCasing(form, text
                    .replace(/ı/g, '\uA78C')
                    // Revert the character that doesn't capitalize in this language.
                    .replace(/i/g, '\u02BC'));
    case casingForm.initial:
        return applyCasing(casingForm.upper, text.charAt(0)) + 
            applyCasing(casingForm.lower, text.substr(1)); 
    default:
        return text;
    }
}
```

> 6.    List any non-Unicode-standard capital/lowercase pairs. Default: None

A similar approach should work here, so long as no two glyphs map to the same other-case glyph when lowercased or when uppercased.  Or am I missing something?

**Comment by MattGyverLee** [comment]
Ok, so I was assuming that the proposed Turkish code would become the default for a useCasing language, so I'm looking at how I'd adapt it for languages I know.

> I don't see what you're referring to by "as written in the example code"

I was referring to the Turkish code, that it is hardwired to uppercase the 0th character and lowercase the rest.

```
    case casingForm.initial:
        return applyCasing(casingForm.upper, text.charAt(0)) + 
            applyCasing(casingForm.lower, text.substr(1)); 
```

With my curved glottal (u02bc) example (ʼamal becomes ʼAmal ), char(0) should be ignored, but char(1) would need to be capitalized. Everything else would stay the same as in the dictionary.

Actually, now that I look closer, if we assume that the dictionary is normally lower-case, except for words that always appear capitalized (i.e. proper nouns), it would seem needlessly destructive to forcefully apply lower-casing to the rest of the word.
Why wouldn't we just put: `applyCasing(casingForm.upper, text.charAt(0)) +  text.substr(1);` 

If the dictionary was: 
'book'
'car'
'Rambo'
'McDonald'
'NASA'

The original Turkish code (as in your example) would (wrongly) create Mcdonald or Nasa as the initial version when presented with this dictionary, while mine preserves it. Why would you ever want to force lowercase?

**Comment by jahorton** [comment]
> The original Turkish code (as in your example) would (wrongly) create Mcdonald or Nasa as the initial version when presented with this dictionary, while mine preserves it. Why would you ever want to force lowercase?

I was thinking about that earlier, and I think I agree with you.  We probably should preserve casing for the rest of the text with 'initial'... so long as our underlying assumptions here are valid.

With the way the spec is currently outlined, I think `'lower'` really represents something more akin to `'base'` - assuming that the lowercase form of text is its base form.  Of course, that is a significant assumption.

**Comment by MattGyverLee** [comment]
I guess i was also thinking that there would be variables/stores defined in the code, and the "default" 

> Another potential 'annotation': `isCasingException`

Marking exceptions in the dictionary is fine (except for more regular cases such as KiSwahili), but wouldn't we want to manually define the 3 forms?

**Comment by jahorton** [comment]
> Once `isCasingException` is found within a CSV file, the following three columns define the word's casing behavior. In order:
> 
>     * 'lower'
> 
>     * 'initial'
> 
>     * 'upper'

Yep.  Once `isCasingException` is annotated for a word, the 3 entries following it would define exactly that.

**Comment by MattGyverLee** [comment]
I guess I was gently campaigning to have such a catch in the boilerplate code, but it seems reasonable that this would be custom code if it is systematic. This could also be handled as a manual casing exception if the examples were rare.

Ok, so rather than defining curved glottal in the language as a defined ignored character that the 'default' code catches and ignores gracefully, the initial code would need to be manually adapted to check for an invariant character and move down the line. Something more elegant than my pseudocode below (that would handle recursion if there are 2 or more initial non-cap characters).

**initial:**
```
if char0 in IgnoredChars:
  return text.charAt(0) + casingForm.upper, text.charAt(1)) + text.substr(2);  
else:
 return applyCasing(casingForm.upper, text.charAt(0)) + text.substr(1);
```

**Comment by MattGyverLee** [comment]
> In our team discussions, we decided that this will actually default to `false` / "no". This will require a few existing models to be modified accordingly, but it's a large assumption to make for a language.

I'm going to challenge this assumption because I am naïve and want to learn. In the Unicode-aware tools that I have used, trying to programmatically capitalize (or lowercase) a letter that has no capital form in Unicode results in no change. Can't we use this to our advantage?

1. A language uses a script with capital letters (i.e. Latin/Greek/Cyrillic), and the orthography uses them in English-like ways (**useCasing = true**)
2. A language uses a writing system with no capital letters (i.e. Arabic or Hebrew), (useCasing = **True or False** are safe, the as casing rules will apply vacuously)
3. A language uses a script containing capital letters (i.e. Latin/Greek/Cyrillic), but the orthography only uses lowercase letters. (**useCasing = False**)
4. A language uses a script (i.e. Latin/Greek/Cyrillic) and orthography using capital letters, but the keyboard developer does not want to use automated switching/capped suggestions.  (**useCasing = False**)

It seems to me that option 1 and option 2 would cover most of the world's languages, where enabling useCasing would be safe (even if ineffectual in option 2). 
A priori, you only get into trouble with useCasing if you use characters that have capital forms, but don't use those capital forms. Option 3 would be rare (I can imagine that there are some of these languages in PNG), but is entirely possible. Option 4 seems unfortunate for the user, but this is the developer's choice.

**Comment by jahorton** [comment]
5.  A language uses a script with (mostly) capital letters but _not_ lowercase letters (i.e. [Sencoten](https://github.com/keymanapp/keyboards/tree/master/release/fv/fv_sencoten)) - (**useCasing = false**)

![File](https://user-images.githubusercontent.com/25213402/97378969-3da24c00-18f6-11eb-8046-9aa1346b05a8.jpg)

This is the _base_ layer of the keyboard; almost all characters use uppercased Latin characters, but there is that lowercased 's'.  Also note that it has an existing lexical model we'd rather not break.

I'm not super-familiar with the language; @eddieantonio should be able to give more details in this regard, as he assisted with the lexical model's creation.

**Comment by mcdurdin** [comment]
> I'm going to challenge this assumption because I am naïve and want to learn. In the Unicode-aware tools that I have used, trying to programmatically capitalize (or lowercase) a letter that has no capital form in Unicode results in no change. Can't we use this to our advantage?

I find your commentary helpful. The principle I am working from is that a model that works in a certain way in v13 should continue to work in the same way in v14. In general, it is good to make new functionality *possible* but not good to assume that new functionality will be *automatically desirable*. In the first instance, a model developer can update their model at their convenience to support the new functionality (e.g. casing). Conversely, if we automatically enabled that the new functionality, that would force a model developer adversely affected by it to scramble to put out a fix. Casing is just one scenario of many.

We also try and make far fewer assumptions of language and script knowledge than many Unicode-aware tools, because we are providing tools for less-supported languages. That sometimes shifts some work downstream, but it doesn't tend to cause breaking problems for keyboard devs or end users.

**Comment by mcdurdin** [comment]
> Ok, so rather than defining curved glottal in the language as a defined ignored character that the 'default' code catches and ignores gracefully, the initial code would need to be manually adapted to check for an invariant character and move down the line. Something more elegant than my pseudocode below (that would handle recursion if there are 2 or more initial non-cap characters).
> 
> **initial:**
> 
> ```
> if char0 in IgnoredChars:
>   return text.charAt(0) + casingForm.upper, text.charAt(1)) + text.substr(2);  
> else:
>  return applyCasing(casingForm.upper, text.charAt(0)) + text.substr(1);
> ```

This is a great example of using a custom casing function to solve this problem -- it's not something that should be automatically applied to every language, and the language-specific nuances mean that it's best done at a model-level.

We are considering putting a handful of special-cases into the base `applyCasing` (iPhone, iPad, etc).

**Comment by jahorton** [comment]
For now, we'll only be implementing the base details from the description for 14.0; anything else (like the 'annotation' idea for extended / special capitalization cases) will be left for later versions.

We may proactively handle a few exceptions - particularly for iDevices / known case-abusing marketing terms.

**Comment by MattGyverLee** [comment]
> Conversely, if we automatically enabled that the new functionality, that would force a model developer adversely affected by it to scramble to put out a fix. Casing is just one scenario of many.

In your concise comment, you've convinced me. I see now that default, in the context of backward compatibility, is not analogous with handy or most-useful, but is dangerously forceful. Use-casing probably should be recommended for "most" languages, but not defaulted in the engine.

**Comment by jahorton** [comment]
I updated part of the description to better match the final implementation, since it's our current best documentation of how a custom `applyCasing` function should be implemented.
