### ISSUE TITLE
bug(windows): The display language list has incorrect labels and doesn't work

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3750]
**Describe the bug**
No other languages are shown in the Display language list.

![image](https://user-images.githubusercontent.com/28331388/97130526-3f440680-1774-11eb-9ab4-de3f0da3e8e8.png)

**To Reproduce**
1. Go to 'Configuration'
2. Click on 'English' next to the globe icon `Display in:`.
3. See error

**Expected behavior**
The list should not show "Englishes". Various languages should be there to choose from instead.

---
**Keyman Desktop:**
 - OS: Windows 10 Pro 2004
 - Keyman version: 14.0.168-alpha
 - Target Application: [self]

**Comment by mcdurdin** [comment]
Also, clicking off the menu doesn't cancel it, and escape also does nothing.

**Comment by mcdurdin** [comment]
And, mouse cursor is incorrect in the menu.

**Comment by mcdurdin** [comment]
All this is related to the new strings.xml-based translations. Summarising:

- [ ] Language names are incorrect (due to not enumerating locale files correctly)
- [ ] Still attempts to load locale.xml from packages (no longer supported)
- [ ] Loads every strings.xml when Keyman Configuration runs in order to get list of languages (poor performance); suggest resolving this by making the language selection its own dialog?
- [ ] Dialog sizes are still read out of locale file (visible e.g. for Proxy dialog)

UI issues:
- [ ] Clicking off the menu doesn't cancel
- [ ] Pressing Esc doesn't cancel
- [ ] Mouse cursor is not correct in menu
