### ISSUE TITLE
chore(web): keymanweb.js is growing too much in file size

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#3796]
**Describe the bug**
Looking at various versions of keymanweb.js, I am concerned about the file size growth. I think we need to try and find ways to bring it back down.

I've listed here the minified file sizes of latest releases for each major version. In particular, we more than doubled the file size between versions 11 and 12. 

* 2.0.473: 140KB
* 10.0.103: 202KB
* 11.0.227: 186KB (good work!)
* 12.0.106: 381KB
* 13.0.109: 389KB
* 14.0.154: 435KB

Ideally, we should be at around 150KB or less. That may not be achievable, but I am sure we can improve on what we have. It would be good to understand where the bulk of the growth comes in each version.

**Comment by jahorton** [comment]
I'd like to point out that the largest jump in file size, by _**far**_, occurred when we introduced predictive text in 12.0.  Comparing 12.0+ against KMW 2.0.473's file size is pretty unfair.

That said, true... that jump in file size is more extreme than it ought to be, and I believe a sizable chunk of that is due to the need for duplicating polyfills for both KMW and the lm-layer's worker.  `es6-shim` in particular.  I'd love to find a way to dynamically forward polyfills from KMW to the worker, but that's likely to require a bit of time investment.

I also have hopes that involving `webpack`, with its use of tree-shaking, might help here.  Again, time investment required.  I've noted it as part of my investigation toward moving KMW into a more "modular" JS format better suited for NPM use/distribution, though that's a separate goal/issue entirely.  (Refer to https://github.com/jahorton/progressive-namespace-to-migration-example/pull/1.)

**Comment by jahorton** [comment]
#6557 includes changes that get us quite close to dropping `es6-shim`, a notable contributor to KMW's file-size issue.

**Comment by jahorton** [comment]
You know, I just realized something that might make a difference, even if it would also complicate things a bit.  We could do a Closure minification pass on the WebWorker code - something I don't believe is being done at all currently.

It’d take some time and effort to make sure it doesn't break the Worker boundary APIs, but that could probably make a dent in the file size increases.

We'd probably want a "switch" of sorts in the build, though - minification does get in the way of debugging.

**Comment by mcdurdin** [comment]
I think we build both minified and unminified versions of the worker? Gets us the best of both worlds.

Debug build should always be unminified of course.

Semi-related, can we just have debug=unminified and release=minified? That way we match the patterns for other platforms. Ref https://docs.google.com/document/d/1xoQaO7ZcICNm2q_C35Cm7Z9TgYq8d2XErSJblVPXM28/edit?usp=drivesdk

**Comment by jahorton** [comment]
> I also have hopes that involving `webpack`, with its use of tree-shaking, might help here. Again, time investment required. I've noted it as part of my investigation toward moving KMW into a more "modular" JS format better suited for NPM use/distribution, though that's a separate goal/issue entirely. (Refer to [jahorton/progressive-namespace-to-migration-example#1](https://github.com/jahorton/progressive-namespace-to-migration-example/pull/1).)

An update regarding this comment:  apparently `esbuild` is now the current industry darling in this regard.  (https://esbuild.github.io/)

**Comment by jahorton** [comment]
- 15.0.269:   519,244 bytes
- 16.0.56:  407,832 bytes (likely from dropping es6-shim)

**Comment by mcdurdin** [comment]
That's a nice improvement!

**Comment by mcdurdin** [comment]
> An update regarding this comment: apparently `esbuild` is now the current industry darling in this regard. (https://esbuild.github.io/)

Tracking move to es modules in #7309.

**Comment by mcdurdin** [comment]
Future improvements to come with es modules, and will continue to improve this as we go.
