### ISSUE TITLE
bug(developer): select a font from the dropdown menu barely scrolled

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#3843]
**Describe the bug**
It is hard to get to the desired font from the dropdown menu under Keyboard menu > Font.

https://youtu.be/2q3Hbod6OJM

---
 
**Keyman Developer:**
 - OS: Windows Pro 10 1909
 - Keyman Developer version: 13.0.115

**Comment by mcdurdin** [comment]
You can also scroll by clicking inside the scrollbar itself rather than just on the arrows, which will be faster (or using pgup/pgdn/up/down keys).

I'm going to label this one as wontfix because it's probably not trivial to change the scrolling behaviour and I think given the above workarounds is probably not a high priority.
