### ISSUE TITLE
bug(android/app): Intermittent blank keyboard

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#3996]
Found during User acceptance testing for 14.0 beta

At some point during testing, I turned off predictions.
Then selecting system keyboards with the globe sometimes resulted in a blank keyboard.

Possibly tied to #3991 ?

Will need to tinker to try to repro

**Comment by mcdurdin** [comment]
I just got a repro of this on my phone. Connected to chrome inspector. The keyboard has an opacity of 0.

Screenshot captured from DevTools:
![image](https://user-images.githubusercontent.com/4498365/100790081-6ffe1680-346b-11eb-8e7c-4b8057b3a779.png)

![image](https://user-images.githubusercontent.com/4498365/100790201-91f79900-346b-11eb-8b62-6c7d62c8703d.png)

As soon as I change the opacity to 1, the keyboard displays correctly:

![image](https://user-images.githubusercontent.com/4498365/100790267-a6d42c80-346b-11eb-8fbb-650d86c94085.png)

![image](https://user-images.githubusercontent.com/4498365/100790337-c10e0a80-346b-11eb-8c4d-1645ede008d8.png)

I haven't tried to investigate the root cause of this but hope that gives you something to track.

**Comment by darcywong00** [comment]
I had a repro where the system keyboard was on hideKeyboard. But haven't found consistent steps.
I was clicking rapidly on the default sil_euro_latin keys in the Chrome omnibar.
