### ISSUE TITLE
bug(android/engine) Physical Keyboard's Enter Key pressing become doubling

### ISSUE THREAD

**Issue by ramesh-k** [keymanapp/keyman#4213]
**Describe the bug**
When typing in Google Docs Android app (or on Keyman app's text editor) using Keyman for Android with physical keyboard over OTG, the Enter key pressing get doubling.

**To Reproduce**
1. Connect a physical keyboard with Android phone over OTG.
2. Change Keyman as default input method.
3. Go to 'Keyman app for Android'
4. Start typing using physical keyboard.
5. Press Enter Key.
6. See error.

**Expected behavior**
The Enter key pressing should not be doubling. It should only get one.

---
**Keyman for Android:**
 - Device: Redmi 8A
 - OS: MIUI Global 11.0.2
 - Android Version: 10
 - Keyman version: 13.0.6220
 - Target Application: Keyman, Google Docs
 
**Keyboard 1**
 - Keyboard name: EuroLatin(SIL)
 - Keyboard version: 1.9.2
 - Language name: English

**Keyboard 2**
 - Keyboard name: Malar Malayalam
 - Keyboard version: 1.3
 - Language name: Malayalam

**Comment by darcywong00** [comment]
Thanks for letting us know. I'll look into it next week

**Comment by darcywong00** [comment]
I was able to reproduce the issue with Keyman for Android 13.0.6220 stable.

The physical keyboard <kbd>ENTER</kbd> key works (1 press = 1 new line) in the latest Keyman for Android 14.0.217 beta pre-release. But I haven't tracked down which PR fixed it.

I'll discuss with the team. Since we aim to release Keyman 14.0 within a few months, it's possible we might not fix this in 13.0.

**Comment by darcywong00** [comment]
Update after team discussion

Unfortunately, we won't be able to implement a fix for 13.0, since we're trying to get 14.0 released early this year.

If the <kbd>ENTER</kbd> key impacts your workflow, you can try 14.0 Beta pre-release at
https://keyman.com/downloads/pre-release/#android
