### ISSUE TITLE
bug(web): extremely slow load of keyboards on keymanweb.com

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4240]
**Describe the bug**

KeymanWeb is currently very slow to load a keyboard on Chrome on Windows, at least. I have not yet tested on other browsers. I ran a profile and found it taking 4-6 seconds to build the desktop OSK, which seems more than a little excessive!

The good news is that >99% of the load time is taken up in a single function call `deviceDependentLayout` and two child functions `generateKeyText` and `generateKeyCapLabel`, which means this is easy to isolate and hopefully we will be able to reap some quick and easy wins.

**To Reproduce**

1. Go to keymanweb.com
2. Select a keyboard. Observe that the page locks up for a few seconds while the script runs.

* Profile 1: Loading basic_kbdbene on 13.0.109: 
![image](https://user-images.githubusercontent.com/4498365/104403830-7aa0e500-55ad-11eb-8827-a78759c59a46.png)

* Profile 2: Loading indigenous_nt on 14.0.219:
![image](https://user-images.githubusercontent.com/4498365/104406126-ad99a780-55b2-11eb-9c08-3a3c247de808.png)

* Performance capture: [Profiles.zip](https://github.com/keymanapp/keyman/files/5806352/Profiles.zip)

---

**KeymanWeb:**
 - OS: Windows 10 2004 x64 
 - Browser: Chrome 87.0.4280.141 
 - KeymanWeb Version: 13.0.109 
 - URL: https://keymanweb.com/#fr,Keyboard_basic_kbdbene

**Comment by jahorton** [comment]
As far as I can tell, this is only an issue when the Toolbar UI is active.  It can occur from the Toolbar UI testing page for KMW as well.

If using a mobile form factor to access a site that prefers the Toolbar UI, it seems to load slowly in a similar manner, but OSK swaps seem to be responsive and not affected by this bug.

... actually, not all keyboards seem to be delayed by multiple seconds, either.  Just the first one.

All of this taken from a MacBook Pro running 10.15.7 (Catalina).

**Comment by mcdurdin** [comment]
I'm seeing the same behaviour on Unminified Source test page (keymanweb/testing/unminified.html); for example, selecting Lao 2008 Basic:

![image](https://user-images.githubusercontent.com/4498365/104860232-8100d980-597e-11eb-904c-326f2cc72801.png)

The amount varies by keyboard but the significant pause is present in all cases.

Again, Chrome 87.0.4280.141. Note that this issue does **not** repro in Firefox.

**Comment by jahorton** [comment]
> Again, Chrome 87.0.4280.141. Note that this issue does **not** repro in Firefox.

Ah.  That's a pretty significant note.  I do tend to prefer Firefox over Chrome, so I wouldn't have run into it as often.

... I wonder if this has anything to do with the [newly-supported `TextMetrics` features](https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics/fontBoundingBoxAscent#browser_compatibility)?  Maybe I should find a way to spin up an older Chrome install and compare.

While this PR isn't making any use of the new `TextMetric` features, Chrome 87 now has to calculate and provide values on the returned object that it previously didn't.  Perhaps that might make an impact, and might be why we've only noted this issue now?

On the other hand... I just decided to do a little profiling in Firefox for comparison.  Definitely quicker... and based on #4270's branch... but even then I noticed something enlightening:

![Screen Shot 2021-01-18 at 8 53 02 AM](https://user-images.githubusercontent.com/25213402/104864111-ac79c900-596a-11eb-8f64-94df98a59ac2.png)

Both text-scaling methods currently rely on calls against the OSK cookie via `VisualKeyboard.prototype.getFontSizeFromCookie`:

https://github.com/keymanapp/keyman/blob/cb98febc206c7e2d83030bb8b4890d58534cc7e1/web/source/osk/visualKeyboard.ts#L1817-L1832

Granted, it appears this particular method only seems major use on desktop platforms:

https://github.com/keymanapp/keyman/blob/cb98febc206c7e2d83030bb8b4890d58534cc7e1/web/source/osk/visualKeyboard.ts#L1796-L1815

In comparison, a Firefox mobile profiling excerpt:

![Screen Shot 2021-01-18 at 9 04 35 AM](https://user-images.githubusercontent.com/25213402/104864660-3d9d6f80-596c-11eb-95ca-7bbdd3c2fbaf.png)

--------

Finally, I can corroborate some of this with the following except from a Chrome (desktop-mode) profiling around against unminified.html:

<img width="619" alt="Screen Shot 2021-01-18 at 9 06 45 AM" src="https://user-images.githubusercontent.com/25213402/104864771-9c62e900-596c-11eb-8fb2-040c195fe48e.png">

Fortunately, I think I've worked on some (loosely-related) code recently.  Noting https://github.com/keymanapp/keyman/pull/4232#discussion_r555532084, it'd probably be wise to cut the cookie dependency here, or at least cache the value on the `VisualKeyboard` instance (and clear that cache on resizes).

--------

So while it does seem to be related to our `getTextWidth` / `getTextMetrics` (#4270) method, the actual issue may be with a method it calls, rather than the `TextMetrics` system itself.  There is a slim chance of "why not both?", but it's hard to be certain at the moment.

**Comment by jahorton** [comment]
Now that https://github.com/keymanapp/keyman/pull/4279 is merged, do we want to continue pursuing this now, or do we feel satisfied with the improvements, at least as far as 14.0 is concerned?

**Comment by jahorton** [comment]
Per team planning meeting, closing this.  We're satisfied for now.
