### ISSUE TITLE
bug(ios): cannot install keyboard package from Keyman Developer debug page

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4281]
**Describe the bug**

When using the Keyman Developer debugger, you can install a package from the debug page:

![image](https://user-images.githubusercontent.com/4498365/104886928-a1e91f00-59be-11eb-80e5-d18c3990038c.png)

However, when I click the blue link above on my iPhone (yes, I know that screenshot is from the emulator, bear with me here), I get the following error in Keyman:

![image](https://user-images.githubusercontent.com/4498365/104886969-b4fbef00-59be-11eb-801c-5b66ef5be4f1.png)

`Error installing package - could not copy required files`

**To Reproduce**

1. Start Keyman Developer, use the Package Editor to test a package.
2. On the phone, load the debug page (e.g. http://thark:8008 is my local test machine) in Safari.
3. Click the download link, then attempt to open the completed download.

Tested successfully with Keyman for Android.

---

**Keyman for iPhone/iPad/Android:**
 - Device: iPhone 7 
 - OS: iOS 12 
 - Keyman version 14.0.233-beta

**Comment by jahorton** [comment]
A quick note:  that alert indicates that our custom error `KMPError.copyFiles` was thrown.  There are a few possible causes of this, so further investigation will be necessary.

**Comment by jahorton** [comment]
Possibly related to #2757.

**Comment by jahorton** [comment]
Turns out this is related to https://github.com/keymanapp/keyman/pull/4095.  If a URL is _not_ security-scoped, attempting to open it as if it were causes an error that crashes the KMP installation process.

Of course, Apple docs being... Apple docs, I'm having trouble finding how to detect whether or not a URL actually _is_ security-scoped.  That would be _very_ helpful for handling both possibilities optimally.

That said, I get the feeling that things should always consistently be one way or the other regarding security-scoping, but clearly that hasn't been the case for the Keyman app.  Perhaps there's a deeper issue... but documentation on this is very poor if so.
