### ISSUE TITLE
bug: Backspace in linux acting strangely when using the Engram layout

### ISSUE THREAD

**Issue by binarybottle** [keymanapp/keyman#4322]
**Describe the bug**
After installing the Engram layout on Linux (Ubuntu derivative Pop OS), the Backspace key is acting strangely.  Whereas it works fine on macos for qwerty or Engram, and works fine for qwerty in Linux, for Engram in Linux you have to tap repeatedly on the Backspace key before it starts erasing characters. This behavior also differs depending on whether or not you are typing in a terminal, browser, or desktop application.

**To Reproduce**
1. Install the Engram layout on Linux (e.g. Ubuntu): https://keyman.com/keyboards/engram
2. Type in a terminal, browser, and desktop application.
3. Tap on the Backspace key.

**Expected behavior**
The previous character should delete.
---

**Keyman for Windows/macOS/Linux:**
 - OS: Linux (Ubuntu derivative Pop OS)
 - Keyman version: 14.0 beta
 - Target Application: terminal, Slack in Google Chrome

---

**Keyboard**
 - Keyboard name: engram
 - Keyboard version: 1.1
 - Language name: English

**Comment by darcywong00** [comment]
Also related to #1489

**Comment by mcdurdin** [comment]
@ermshiperete are you able to check this?

**Comment by ermshiperete** [comment]
Tested on PopOS 20.10 with Keyman 14.0.239. Testing revealed an unrelated problem downloading/installing keyboards which should be fixed in 14.0.240.

But in regards to this bug, this seems to be the same issue as #1489: Backspace works fine in gedit and address bar in Firefox, but doesn't work in gnome-terminal.

Closing this as duplicate. Please see #1489.
