### ISSUE TITLE
bug(linux): Caps Lock is not working as expected

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#4542]
This behavior is also experienced in Linux (`20.04.2 LTS`) 

_Originally posted by @MakaraSok in https://github.com/keymanapp/keyman/issues/4525#issuecomment-785773595_

**Comment by ermshiperete** [comment]
Turns out support for caps lock was never implemented in `common/core/desktop`.

On Windows `kmprocess.cpp` gets the key events and can access the state of the modifier keys. However, in `common/core/desktop` we split the processor from the platform layer (`ibus-keyman`). The latter processes the key events but doesn't know the rules the keyboard defines for caps lock, so it's not possible to simply pass capslock as additional modifier key.

We could add an additional API method to the processor where we pass the CAPSLOCK key press event and let the processor keep track of the capslock state.

This doesn't help if capslock is on before we switch to a Keyman keyboard; in that case we don't see that capslock is already on. That might not be so bad - seems Keyman for Windows behaves the same.

We could probably call the existing `km_kbp_process_event` method. And we would also have to call it for Shift so that the processor can turn capslock off if that option is set in the keyboard.

@mcdurdin said on Slack: If it is not implemented in core, then we need to go through a design phase so we'll have to do it in 15.0. It's not something I want to rush into the code in beta.
Keyman for Windows beta has a current bug around caps lock but normally it does know that caps lock is on and it does track caps lock events. The bug will be fixed before release.

**Comment by ermshiperete** [comment]
Solution might be as easy as adding a block like below in `ibus_keyman_engine_process_key_event` to get basic caps lock functionality working:

```
    if (state & IBUS_LOCK_MASK)
    {
        km_mod_state |= (1 << 7); // KM_KBP_MODIFIER_CAPS;
    }
```

 For implementing missing functionality, see #5052.
