### ISSUE TITLE
feat(linux): XKB support

### ISSUE THREAD

**Issue by bam80** [keymanapp/keyman#4593]
Any hope to add ability for creating/editing layouts in XKB language?
It's de-facto standard for X11/Wayland on Linux.

We have 20 years-old bug report here in KDE bug tracker:
https://bugs.kde.org/show_bug.cgi?id=30481

**Comment by mcdurdin** [comment]
This is currently outside scope for Keyman Developer, but keep an eye on version 15 as we work on the LDML keyboarding standard, which will eventually include tools to convert to/from XKB.

Keyman keyboard layouts are not easily converted to XKB because they can do things that just aren't supported in XKB 😀.

**Comment by bam80** [comment]
> which will eventually include tools to convert to/from XKB

Do that tools will also be for Windows only?

**Comment by mcdurdin** [comment]
No, future tools will be cross-platform. Newer components of Keyman Developer, such as the lexical model compiler, are already cross-platform. The existing compiler runs under WINE, which is not ideal, and we'd welcome pull requests that make it more cross-platform (although the challenge is that part of the existing compiler is written in Delphi, which is not that easy to cross-compile with).
