### ISSUE TITLE
bug(windows): Keyman Composition Not Replacing SMP Characters Correctly

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#4655]
**Describe the bug**

When composing characters in the Unicode address range 1E7E0 - 1E7FF, Keyman is not completely removing a character upon update.  For example, if 1E7E5 is in an editor, and a modifier key is struck to change the character to 1E7E6, what appears on the screen will be D839 1E7E6.  The D839 is unexpected.

**To Reproduce**

1. Build the attached keyboard issue_1e7xx.kmn and install.
2. Start MS Word on another application.
3. Type "h", followed by "y" and 1E7E5 appears.
4. Type "o" and 1E7E5 is replaced by D839 1E7E6 (no space in between).

**Expected behavior**

Only a single character appears on screen, as per the defined mapping

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10.0.19041 Build 19041
 - Keyman version: 13.0.118.0
 - Target Application: Microsoft Word 2016

**Keyman Developer:**
 - OS: Windows 10.0.19041 Build 19041
 - Keyman Developer version: 13.0.118.0

---

**Keyboard**
 - Keyboard name:  issue_1e7xx.kmn the keyboard is attached to this ticket in a zip file that also includes a font.  The keyboard is a reduced version of the gff_gurage keyboard to demonstrate the issue.
 
[issue_1e7xx.zip](https://github.com/keymanapp/keyman/files/6127275/issue_1e7xx.zip)

**Comment by mcdurdin** [comment]
Ho @dyacob, can you try this with version 14 beta, because I believe we fixed this in #4360?

**Comment by dyacob** [comment]
Hi @mcdurdin , yes, it is working great with the latest 14 beta :-)  thanks!

**Comment by dyacob** [comment]
Is it possible to restrict the keyboard compatibility for Keyman Desktop v14 or greater?  I can't find a setting like this in the .kmn or .kps file.  What I am imagining is that a user trying to install it with Keyman v13 would see a message like _"Sorry, this keyboard will not work with this version of keyman.  Please upgrade by following the link here..."_, or similar.  Also good if someone searching for keyboard from an older keyman simply wouldn't see it listed.

**Comment by mcdurdin** [comment]
There's two parts to this:

1. .kmn support: This is a little tricky because other platforms will work just fine in 13.0. You can specify the file version in the .kmn with `store(&version) "14.0"` and then it will not install on earlier versions. You can only compile that with 14.0 compiler, of course.

2. .keyboard_info support: you can put a minimum Keyman version in the .keyboard_info: see the `minKeymanVersion` spec at https://help.keyman.com/developer/cloud/keyboard_info/current-version/ (this file has some [outdated](https://github.com/keymanapp/help.keyman.com/pull/355) version numbers in it...) (This is extracted automatically from the `&version` store during build)
