### ISSUE TITLE
Keys in 10th column appear skinnier than other keys

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#487]
On some 10-column keyboard layouts, the 10th column appears skinnier than the others.

Screenshots below from Android 7.1.1 with the default "EuroLatin2" keyboard and "Cree, Moose keyboard"

![eurolatin2](https://user-images.githubusercontent.com/7358010/33866650-7fefaa48-df2a-11e7-98aa-6b8a0d783f89.png)
![cree moose](https://user-images.githubusercontent.com/7358010/33866656-84125ba2-df2a-11e7-94ac-396049618c3d.png)

Check how KMW engine is handling integer-scaled keyboard widths.

**Comment by jahorton** [comment]
I all the work that's happened since this issue was last evaluated has already fixed this as a side-effect.

`khmer_angkor`:

![image](https://user-images.githubusercontent.com/25213402/198447886-d078c151-dc0b-4be9-bfbf-43073a4095de.png)

`sil_euro_latin`:

![image](https://user-images.githubusercontent.com/25213402/198448545-592fbaaf-da7d-442a-9c9d-7b5ecc1e3e8e.png)

Cree, Moose (`fv_moose_cree`)

![image](https://user-images.githubusercontent.com/25213402/198449239-27657080-7056-443a-8c86-e64686ae2e33.png)

Interesting alignment issue on the first key, last row... but it's otherwise fine.  (Looks like the final row is told to take up more space than the rest.)

**Comment by mcdurdin** [comment]
> Interesting alignment issue on the first key, last row... but it's otherwise fine. (Looks like the final row is told to take up more space than the rest.)

```
  "pad": "0",
```

https://github.com/keymanapp/keyboards/blob/b6e66946949bfb36669e8b66d70fc96d72343a56/release/fv/fv_moose_cree/source/fv_moose_cree.keyman-touch-layout#L226

**Comment by jahorton** [comment]
> > Interesting alignment issue on the first key, last row... but it's otherwise fine. (Looks like the final row is told to take up more space than the rest.)
> 
> ```
>   "pad": "0",
> ```
> 
> https://github.com/keymanapp/keyboards/blob/b6e66946949bfb36669e8b66d70fc96d72343a56/release/fv/fv_moose_cree/source/fv_moose_cree.keyman-touch-layout#L226

Huh.  Odd design choice, but okay.  👍

**Comment by mcdurdin** [comment]
Indeed, I was mostly concerned that it wasn't a weird bug creeping in somewhere in KM.
