### ISSUE TITLE
bug(common/models): LM stops working on a fresh install

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#4959]
**Describe the bug**

With a fresh installed of Keyman for Android, after installing [Khmer Angkor keyboard](https://keyman.com/keyboards/khmer_angkor) and [NC Khmer Wordlist LM](https://github.com/keymanapp/keyman/files/6355990/sil.km.nckw.model.zip), start typing in the text area ស្រ to see no suggestion on the banner.

**Expected behavior**

The LM should give the expected/relevant suggestions on the banner.

**Screenshots**

![InkedScreenshot_1619072210_LI](https://user-images.githubusercontent.com/28331388/115666338-a848b780-a36e-11eb-9c57-0e480d06068c.jpg)

---

**Keyman for Android:**
 - Device: Pixel 2 (AS emulator)
 - OS: Android 10
 - Keyman version 14.0.271
 - Target application: Keyman

---

**Keyboard**
 - Keyboard name: khmer_angkor
 - Keyboard version: 1.0.9
 - Language name: Khmer
 - LM source: https://github.com/keymanapp/lexical-models/pull/131

**Comment by MakaraSok** [comment]
The behavior is rather unpredictable. I experienced that the error would not happen right of the gate. The suggestions might keep showing after typing ស្រ . The LM would crash or stop giving the suggestions if the same sequence is typed over and again after choosing from the suggestions.

i.e. keep typing ស្រ and choose ស្រី (the first option) until the banner turns blank. See below. It turns blank after three rounds for me.

![Screenshot_1619083180](https://user-images.githubusercontent.com/28331388/115689805-a0950d00-a386-11eb-84ca-6ebb798e06ae.png)

**Comment by jahorton** [comment]
It's worth noting that errors will generally be a lot more likely for models targeting languages without proper word-breaking implementations.  Our support for them is simply lacking until we're able to implement #5025.

If this can be shown to also affect models for languages with space-based wordbreaking, that would give this issue higher priority.

**Comment by mcdurdin** [comment]
I am wondering if this is a performance issue -- that the prediction engine is giving up because the lookup is slow and we are near a timeout threshold and sometimes crossing it?

**Comment by jahorton** [comment]
@mcdurdin You mentioned at one point that there were some other behaviors not currently documented here that might be related?  Could you please add those details here?  I'll need those in order to better pursue this issue.

**Comment by mcdurdin** [comment]
There is nothing specific. I have observed, which may or may not be releated:
* when there is 'more' text in a field, suggestions are failing to appear.
* deleting text (backspacing) often leaves the banner empty.
* Here's anomolous behaviour I observed with a recent 15.0 beta, using sil_euro_latin, in-app on Android:
  * Type <kbd>h</kbd><kbd>e</kbd><kbd>l</kbd><kbd>l</kbd>, select "Hello" from banner (note capital 'H'?!)
  * Type <kbd>w</kbd><kbd>o</kbd><kbd>r</kbd>, select "world" from banner.
  * Backspace **quickly** until "Hello w" is left -- the banner will often (but not always) offer "the", "to", "a" instead of words starting with "w". Note that backspacing slowly will usually offer more appropriate suggestions.

Hope these pointers help a bit. That last one in particular may be relevant?

**Comment by jahorton** [comment]
> * Backspace **quickly** until "Hello w" is left -- the banner will often (but not always) offer "the", "to", "a" instead of words starting with "w". Note that backspacing slowly will usually offer more appropriate suggestions.

Is that with a multi-tap backspace, rather than a held one?

Also, can you replicate this in iOS?  Or on the "Predictive Text: robust testing" Web test page?  I'm not seeing this effect on either platform in my personal tests.

> deleting text (backspacing) often leaves the banner empty.

I don't see this either, and that's when backspacing as rapidly as possible, even with long words.

**Comment by jahorton** [comment]
The closest thing I've seen was when keystroke errors were occurring behind the scene during some unrelated development/testing recently.  When that happens, if memory serves, the Android keyboard tends to reset itself - so I doubt that's at fault here.  Or has this changed signfiicantly - and if so, in what ways?

**Comment by mcdurdin** [comment]
> Is that with a multi-tap backspace, rather than a held one?

Multi-tap

> Also, can you replicate this in iOS? Or on the "Predictive Text: robust testing" Web test page?

I haven't had the capacity to try and replicate on other platforms yet, sorry.

**Comment by jahorton** [comment]
While we're not sure exactly how just yet, it seems that this may have interesting interactions with Android-specific behaviors.

**Comment by mcdurdin** [comment]
@MakaraSok would you mind re-testing this one please?

**Comment by MakaraSok** [comment]
Tested with Keyman for Android 16.0.84-alpha on SG S9+ running Android 10. The issue cannot be reproduced. It seems to have gone away by now.

**Comment by mcdurdin** [comment]
Good stuff, closing as resolved :grin:
