### ISSUE TITLE
bug(macOS/Windows): the rota and context rules not working in Google Doc in macOS/Windows

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5106]
**Describe the bug**

**To Reproduce**

1. Get this [keyboard](https://drive.google.com/file/d/1hlNIfKkG7BT5JYoMFRpSHFtYtJ8agOhu/view?usp=sharing) package
2. Install it on macOS and Windows
3. Opon Google Doc on Chrome or Safari and type <kbd>a</kbd>+<kbd>/</kbd>, expected output `á` and current output is `a` on macOS and `a/` on Windows
4. See error -- the current output stated in 3 right above

**Expected behavior**

Both rota and context rules should be working as normal in Google Docs and else where. :)

Rota rules on Ma'di (SIL) keyboard is "any vowel + <kbd>x</kbd>" should output:
1. á when press <kbd>x</kbd> once after vowel a
2. â when press <kbd>x</kbd> twice after vowel a
3. ã when press <kbd>x</kbd> thrice after vowel a

Context rules:
1. á when press <kbd>/</kbd> once after vowel a
2. â when press <kbd>Shift</kbd><kbd>6</kbd> twice after vowel a
3. ã when press <kbd>Shift</kbd><kbd>`</kbd> thrice after vowel a

---

**Keyman for Windows/macOS:**
 - OS: Windows 10 Pro 20H2 x64 / macOS Big Sur
 - Keyman version: 14.0.274
 - Target Application: Google Docs on Chrome / Safari

---

**Keyboard**
Keyboard name: [sil_madi](https://github.com/keymanapp/keyboards/pull/1472)
Keyboard version:1.0
Language name: Ma'di

**Additional context**

The keyboard works as expected when testing in Notes, Mail, Messages, Keynote, Numbers  and Pages.

**Comment by MakaraSok** [comment]
These don't work in LibreOffice Version: 7.1.3.2 on macOS either.

They work in LibreOffice Version 7.0.5.2 on Windows though.

**Comment by rc-swag** [comment]
Works for me but seems flaky
Somewhere after the initial install of Keyman I was asked to update the security preferences for "Input Monitoring" [system Preferences->Security & Privacy-> Input Monitoring ].
Initial tests showed it working.   After I installed Libreoffice it stopped as I was typing. I then saw a request to update "Accessibility" after enabling this, it was still not working. I standard keyboard input from the macOS taskbar then reselected Keyman.  It then worked fine on Safari, and Libreoffice again.   
I installed Chrome and tried Google Docs it had stopped working - while it wasn't working I checked Pages and Libreoffice and it wasn't working there either. I again cycled to standard keyboard and back and it started working everywhere.
So I can report it works on the following but with issues.
macOS 11.2.3 Big Sur
chrome 90.0.4430.212 (google docs)
libre office 7.0.62
safari 14.0.3

Note: when I say working or not working I am referring to the Ma'di rules been processed a + /  etc. Instead of á you would get  a/

**Comment by MakaraSok** [comment]
I've found this help page: https://help.keyman.com/products/mac/current-version/troubleshooting/configure-security.

Permission were granted to two of the three options mentioned there in:

> Privacy / Input Monitoring
> Privacy / Accessibility

This was not visible in Big Sur and no permission was able to be granted.
> Privacy / Files and Folders

The keyboard, however, now is working as expected. 
@rc-swag Keyman didn't crash on me, and everything is running well now. 💯 

_What was confusing to me when encountering this is that Keyman works on most apps, but not Google Docs and LIbreOffice. Why is that privacy stuff affected only Google Docs and LibreOffice?_

**Comment by rc-swag** [comment]
Yes, reading that help document it shows that those setting may only appear when an attempt is made access them the first time. At the bottom of that document it also mentions cycling the input source like I had to, I never received a prompt to restart keyman though.  To your question of why some apps worked and others don't. It seems they use"accessibility" options and the others don't.
I think this bug could now be closed.  Do you agree?

**Comment by MakaraSok** [comment]
Yes, let's close this.

**Comment by mcdurdin** [comment]
Is this working for Windows then?

**Comment by rc-swag** [comment]
> Is this working for Windows then?

Yes
