### ISSUE TITLE
Double-clicking on a .kmp on macOS should install the keyboard

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#511]
I'm seeing reports that double-clicking a .kmp file on macOS shows an error: https://community.software.sil.org/t/amharic-font-not-installing/515

It should be installing the keyboard. If this is not supported, this is a new feature; otherwise it is a bug...

**Comment by mcdurdin** [comment]
It looks like we need to do this with a supporting app -- the input method cannot associate with a filetype. So we'll punt this through to 11.0, because it means significant rework of the installation.

**Comment by tombogle** [comment]
@mcdurdin Great news! I have this mostly implemented (see branch mac-support-double-clicking-kmp). The current implementation gives no UI feedback, and the newly added keyboard is not initially selected (checked) in the configurations page. This latter behavior is consistent with what happens when the user downloads a new keyboard, but I'm not sure it's desirable. However, if a KMP has multiple keyboards, we probably wouldn't want to select them all. I think maybe the best approach would be to try to display the configuration window so that the user could see that the double-click worked, and then they could hopefully realize that they need to select the desired keyboard(s). Does that sound right to you?

**Comment by mcdurdin** [comment]
Okay, it's not 100% ideal. I'd prefer to mimic the behaviour we have on Windows and (now) on Android: show a confirmation dialog prior to installation, then show the welcome documentation when installation is complete.

If a package has multiple keyboards, we select them all by default. In most cases, this is the desired outcome, e.g. Galaxie Greek and Hebrew package.

Then we can certainly consider if we want to show the Configuration window. Perhaps if the Configuration window opened and the confirmation dialog appeared over it we get the best of both worlds?

**Comment by tombogle** [comment]
I think I have everything working now except automatic selection of keyboards after installation.
