### ISSUE TITLE
docs(mac): Update security configuration for Big Sur

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#5151]
This page says permission is supposed to be granted in three separate places under Security and Privacy, but only two of the three can be granted and Keyman works as expected after the permission was granted to the two.

Link to the page: https://help.keyman.com/products/mac/current-version/troubleshooting/configure-security

Related: https://github.com/keymanapp/keyman/issues/5106#issuecomment-844589227.

**Comment by MakaraSok** [comment]
The third on the list (Privacy / Files and Folders). Keyman is not found on the list.

![Screen Shot 2021-05-26 at 9 29 45 AM](https://user-images.githubusercontent.com/28331388/119593956-203e4d80-be05-11eb-8fb6-a3fbd95a20e2.png)

**Comment by mcdurdin** [comment]
The files and folders permission will probably be required when you install a keyboard, yes?

**Comment by MakaraSok** [comment]
No, not when you install a keyboard. Not even when you (re?)install Keyman for mac. 

The interesting fact is that Keyman is not shown in the "Files and Folders" settings.
![image](https://user-images.githubusercontent.com/28331388/122846294-bc3d7500-d32f-11eb-8bad-119923d1e07b.png)

**Comment by sgschantz** [comment]
When I run a fresh install of Keyman 15 with macOS Monterey and switch to Keyman for the first time, here is what I see:
1. request for Documents Folder access
2. request for Keystroke Receiving (Input Monitoring permission)
3. after enabling Input Monitoring, alert to restart
4. another request for Documents Folder (despite it already being granted)
5. Keyman runs but the shift layer does not work
6. after restart, the shift layer works
7. attempting to use the OSK produces a request for Accessibility Access (Events)
8. after granting, OSK works without a restart

This experience will definitely change with Keyman 16 because of the Mac code changes around security, but it also changes based on the version of macOS. Some APIs that do not require permission with older versions of the OS, do require permission with later versions. I will update the documentation to make it clear that the permission requirements vary.
