### ISSUE TITLE
Support for these flags in KeymanWeb on those browsers that support l/r ctrl/alt

### ISSUE THREAD

**Issue by johnmangam** [keymanapp/keyman#52]
It would be great if you could add support for these flags in KeymanWeb on those browsers that support l/r ctrl/alt.

I get the error: **Extended shift flags LALT, RALT, LCTRL, RCTRL are not supported in KeymanWeb.** 

Thanks and regards,
John

**Comment by johnmangam** [comment]
Hello Marc,

Good-day!

Could you please let us know when we could expect this modification to be incorporated?

Thanking you.

Best regards,
John

**Comment by mcdurdin** [comment]
We don't currently have this on our development timeline; it would be considered a low priority feature at this time. We would welcome a pull request.

**Comment by johnmangam** [comment]
Thank you Marc for the message. As you have suggested in a [related issue](https://github.com/tavultesoft/keymanweb/issues/9), **event.location allows us to distinguish between L/R ctrl/alt on modern browsers**, I will try to make the changes and send a pull request. In the KMW source, could you please let me know which file(s) I need to make the necessary changes?

**Comment by mcdurdin** [comment]
Off the top of my head, changes would probably required in a number of files, e.g. keymanweb.js, kmwbase.js and kmwcallback.js, with some minor changes required to kmwosk.js. But there may also be changes required to kmwnative.js, kmwlegacy.js and kmwkeymaps.js; I'd have to investigate to be sure. It's not trivial because differentiating between L/R ctrl/alt involves changing the way the On Screen Keyboard works to allow for handling the keys independently, as well as passing updated modifier flags through in the appropriate locations.

Remember that distinguishing the L/R setting is a keyboard-level option, so some keyboards will have this flag set, and others won't. I don't think the setting value is compiled into the javascript output for a keyboard at this point: I also need to note that the compiler will also need updating to complete this issue. The compiler is not yet open source (preparing the Keyman projects for open source is the current focus of our efforts).

**Comment by johnmangam** [comment]
Thank you very much, Marc.

**Comment by jahorton** [comment]
Implemented with #300 and #313.  Visual editor support is pending but will be added soon.

**Comment by jahorton** [comment]
Visual editor support is coming with #342, which should be through to Alpha by the end of this week.
