### ISSUE TITLE
bug(web): Uncaught (in promise) Error

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#5353]
Found while testing #5260

For testing the error handling of kmwkeyboards.keymanCloudRequest(), I intentionally defined an invalid URL
```javascript
 const URL='https://apis.keyman.com/cloud/4.0/'
                + ((arguments.length > 1) && byLanguage ? 'languages' : 'keyboards');
```

This caused the following console exception
> Uncaught (in promise) Error: Could not find a keyboard with that ID.
    at HTMLScriptElement.Lscript.onerror (kmwkeyboards.ts:1258)

Turns out this also can be repro'd on the current `master` branch (as of 15.0.73 alpha) after making the same change to URL, separate from my Promise API PR's.

**Comment by mcdurdin** [comment]
This is arising because we have a nested promise that is not being caught. We have a mix of async/await and 'traditional' promises, which makes it kinda hard to reason through the code. I wonder if we consider transforming to async/await? I will see if I can map out the promise tree that is causing the problem first, though.
