### ISSUE TITLE
The nextlayer property on a key in the touch layout overrides output

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#54]
If you define a nextlayer property for a given key, this overrides the output rule defined for the key, so it becomes a plain modifier key. This is probably not a good situation -- ideally, the nextlayer control should allow output, then swap layers.

A workaround is to use the `layer(<name>)` statement in the keyboard source for the associated rule instead.

**Comment by mcdurdin** [comment]
Furthermore, trying to use nextlayer to move from a custom layer to a default layer (e.g. "shift") is broken, see the code in `osk.updateLayer`. I don't know why this code is like this and we probably need understand why the code is doing this before we fix this.

**Comment by erros84** [comment]
This is my biggest blocker bug, and I don't think it is truly closed. 

I see you fixed this bug in KM web. https://github.com/keymanapp/keyman/issues/116 

I also see your workaround of using layer(<name>) in the source. The workaround didn't work on android for long-press items, but maybe it does now.

As it seems to me: 
1. The workaround only partially works (because of longpresses), and 
2. Using NextLayer the normal way (in KD) doesn't seem to work at all (it jumps to the layer before outputting the text).

So where are we now on this bug? Should I still be using the ugly workaround, or Is this bug fixed in any current Android/iOS alpha versions?

**Comment by jahorton** [comment]
Note that both our Android and iOS app use KMW as their core; our Alpha versions of both apps should no longer have this issue.  If you'd like to investigate this for yourself, please check our links on https://keyman.com/downloads/pre-release/ for details on how to get our in-development versions.

Note that we're in the midst of a big overhaul of our products in preparation for a new major version; unfortunately, this means that #116 will not be 'released' for quite some time.  If this is something for something you'll likely need in the next couple of months, I'd advise continuing with the workaround for now.

Also, would you mind sending us a copy of the problematic keyboard source so that we may use it for testing to ensure the issue is properly resolved for future versions?

Thanks for your feedback on this!
