### ISSUE TITLE
bug: Lexical Model languageUsesCasing=true works on KeymanWeb but not Android or iOS: true

### ISSUE THREAD

**Issue by rowbory** [keymanapp/keyman#5463]
**Describe the bug**
Related to issue #4115
languageUsesCasing works to enable suggestions to be capitalised when the shift key layer is selected on Keyman Web but not on the phone (iPhone/Android) versions of the keyboard. In addition, it now seems that my keyboard's automatic triggering of the shift layer after end of sentence (. /? /! ) gets turned off when in Keyman app on iPhone.

**To Reproduce**
1. I added languageUsesCasing: true to my lexical models
2. I compiled and tested the lexical model in browser and it worked as expected, when imitating a phone to type on the soft keyboard. ie. I typed T and the suggestions came with that capital letter at the start of all of them and maintained the upper case when I chose them.
3. I transferred the lexical models to Keyman on iPhone by AirDrop (easiest way) and installed them.
4. I tried typing with the keyboard and found that suggestions did not follow the caps I had already typed.  eg I typed T and the suggestions were lower case 'the' 'they' and they changed the capital T to a small t.
5. Behaviour was the sae in Keyman and in other apps but in the Keyman app, when I double-tap space or do a space after a full stop, the shift key goes on and then off. In other apps it behaves normally (coming on automatically when starting a new sentence).

**Screenshots**
![UNADJUSTEDNONRAW_thumb_4efd](https://user-images.githubusercontent.com/420492/125944406-a0f2121e-7a96-422f-a725-205ac3d53f6c.jpg)
https://user-images.githubusercontent.com/420492/125944826-c9cc7d11-953d-4506-951e-3394822fc871.mp4

**Keyman for iPhone/iPad/Android:**
 - Device: iPhone 6
 - OS: 12.5.4
 - Keyman version 14.0.277
 - Target application: Keyman, Notes

**KeymanWeb:**
 - OS: macOS 10.14
 - Browser: Chrome
 - KeymanWeb Version: 14.0.277

---

**Keyboard**
 - Keyboard name: naijatype.kmp / david_rowbory.en.british_english.model.kmp
 - Keyboard version: 29
 - Language name: English

**Comment by rowbory** [comment]
Retested on Android and found that the capitalisation issues wasn't working there too, but the automatic shift layer worked as expected. So perhaps there are 2 different issues, one to do with the handling of the keyboard in the iOS Keyman app. That's not a high priority I don't think, but is puzzling.

One other related puzzle. When I installed the new dictionaries/lexical model kmp files on both devices (which had had the previous versions installed) for some reason they each presented an old version of the readme.htm file which didn't reflect the version number of the actual kmp package. If no-one else can reproduce this, then we may in fact have a bug related to updating existing dictionaries.

**Comment by jahorton** [comment]
Any chance you could provide us a copy of the packages you mention in the issue?  I don't see either the keyboard or the lexical model within our repositories, so I can't attempt to reproduce any keyboard / model specific errors that may be occurring.  As I realize this implies they may be intentionally proprietary, if you wish to keep them private, you may wish to send us copies via our Community Site.  Here's a link to [my profile page](https://community.software.sil.org/u/joshua_horton/summary), from which you can DM me the files.  
- If they can't be uploaded as .kmp files, just throw 'em into a .zip or rename them as .zip files.

------

In the meantime:

I recall when doing some of the initial development and testing for `languageUsesCasing` that sometimes reinstalling the same package gets... tricky on mobile devices.  For example, iOS loves to rename incoming files slightly, adding a `(1)` or a `(2)` to the package filename when re-imported by a Simulator drag-and-drop operation.

> I transferred the lexical models to Keyman on iPhone by AirDrop (easiest way) and installed them.

iOS's AirDrop is probably a "similar enough" feature to have the same problem occur.

You may wish to open up your device's Files app and delete any previously-imported copies of the package, then try again.  (You may also want to delete the previously-installed copies of the keyboard and model, just to be extra-sure.)  There's a chance that this iOS behavior is interfering, preventing any newer versions from replacing the older versions properly.  If this is the case, if the old version didn't have the behavior implemented but the new one _does_,  you'd still see "old" behavior instead of your new behavior - hence the "no casing" bit.

For comparison, if you have the `sil_euro_latin` keyboard and the default English lexical model installed, note that said model uses `languageUsesCasing`.  If it's a _general_ problem with the feature, that model should fail as well.  However, my personal phone is also on `14.0.277` and `languageUsesCasing` works correctly, at least with that keyboard/model pair.

------

> Behaviour was the same in Keyman and in other apps but in the Keyman app, when I double-tap space or do a space after a full stop, the shift key goes on and then off. In other apps it behaves normally (coming on automatically when starting a new sentence).

As for this "automatic triggering" part of the issue... as that's keyboard-custom behavior, I can't give much feedback without seeing its implementation or testing directly with it.  This observation actually is pretty informative, but the affected part of the app is tricky to maintain; we'd need to test any changes to ensure a proper fix.

**Comment by rowbory** [comment]
Many thanks. I'm working through getting the keyboard submitted properly but hadn't started submitting the lexical models to the repository. I did wonder whether it could be an issue with updating keyboards/models and can try to test whether that is where things are going wrong. 

(Is there a 'standard' English model that I have missed and could be using? I made my own quickly from British National Corpus, but I'm sure it could be better.)

[naijatype-29.kmp.zip](https://github.com/keymanapp/keyman/files/6841201/naijatype-29.kmp.zip)

[all_dictionaries.kmp.zip](https://github.com/keymanapp/keyman/files/6841190/all_dictionaries.kmp.zip)

**Comment by jahorton** [comment]
> (Is there a 'standard' English model that I have missed and could be using? I made my own quickly from British National Corpus, but I'm sure it could be better.)

Our default English model is defined at https://github.com/keymanapp/lexical-models/tree/master/release/nrc/nrc.en.mtnt.  It comes preinstalled in the Android and iOS apps.  We're sure it could be better as well, admittedly.

**Comment by jahorton** [comment]
Just tested with the files you sent; I'm not seeing any issues when I install them.  I'm getting the expected auto-shifting after double-spaces and after a post-period space.

`languageUsesCasing` seems to work fine as well.  Note that suggestions won't be capitalized until the first letter is typed; that's a limitation of the current implementation.  (A single capital letter will use "initial" casing (for standard capitalization), while more capitals without _any_ lower case will fully capitalize the entire suggestion.)

Do the problems persist if you delete your current copies and their original .kmp files from your phone, then attempt a reinstallation?

**Comment by rowbory** [comment]
The problem persisted through me deleting and reinstalling the kmp files. I then removed and reinstalled the Keyman app which weirdly made some very old keyboards pop up from the grave. And the problem then remained. I rebuilt everything in case my packages weren't picking up the most recent version of the lexical models, and I put a version number test system into them all, and now when I install it works. So I suspect I had been stupid somewhere, probably in the build process. I have so many dictionaries that I'm building that I've started building everything into one folder, but I think some of the files built themselves into the wrong place. Sorry for wasting your time.

**Comment by jahorton** [comment]
One remaining tidbit; while it did seem to work fine for now (especially on iOS), our intent for `.model.kmp` files is that they only contain a single model.  Keyboard `.kmp` files may contain more without issue, though admittedly we'd _prefer_ just one per `.kmp` as well if they're going to be submitted for distribution.
