### ISSUE TITLE
bug(windows): When help/hint dialog is minimized, it cannot be restored

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#5574]
This was reported by a user via email. Video describing the symptom below
Unfortunately, this was an isolated case as he was unable to reproduce the issue in later attempts.

### Configuration
Windows 10 Version 20H2, OS Build 19042.1110
Keyman for Windows  14.0.279

> I tried exiting the program just now, and it shut down without even prompting me to confirm. Reloaded the program, exited it again, and this time it asked me to confirm. But no problem getting to the window this time. Tried it a third time, same result as the second. So I haven't been able to reproduce the problem yet. 

https://user-images.githubusercontent.com/7358010/128788173-b2277c7a-9e62-4f00-8575-6d1810aa17fb.mp4

**Comment by mcdurdin** [comment]
Okay, this is a Delphi issue. This happened because the window was minimized and there's a bit of a weird windowing mode for dialogs. We had the same issue with splash so the same fix should apply:

https://github.com/keymanapp/keyman/blob/f83c8ebbe5538d173b40f4a616a9b89547c1fa26/windows/src/desktop/kmshell/startup/UfrmSplash.pas#L183-L192
