### ISSUE TITLE
bug(mac): inconsistent terminology for 'keyboard'

### ISSUE THREAD

**Issue by sgschantz** [keymanapp/keyman#5781]
**Describe the bug**
Throughout Keyman for Mac, keyboards are referred to as Keyboards, Keyboard Layouts and Packages.

**To Reproduce**

See labels Configuration window፡ "Keyboard Layouts"
See label in Keyboard info: "Keyboard/Package Info"
See install confirmation alert when double-clicking a .kmp file in Finder: "Keyman Package"

**Expected behavior**
Rename all references to standardize on the word "Keyboard"

**Screenshots**

<img width="468" alt="image" src="https://user-images.githubusercontent.com/89134789/135419115-70e5e956-ced6-4d58-b8ac-c57d0aa285be.png">

**Comment by mcdurdin** [comment]
I'm not 100% on this, because there is one tricky aspect -- some packages include more than one keyboard. When a user installs or uninstalls these packages, they will add/remove multiple keyboards. It might be okay to be ambiguous about this, but want to flag it anyway.

On Windows, it's even trickier, because users can install .kmx files (keyboards) or .kmp files (packages). So the distinction becomes significant. On all other platforms, we only allow install of .kmp files, but Windows has had this distinction for a long time so we need to maintain it.

Happy to not use "keyboard layout" anywhere, just use "keyboard" instead.

**Comment by darcywong00** [comment]
Re: "Keyman package" . Someday when we add lexical-models to desktop, you'll want to distinguish keyboard packages from dictionary (lexical-model) packages.

**Comment by mcdurdin** [comment]
"Keyman package" is hopelessly ambiguous in any case: does it mean a package with Keyman in it? 😆

**Comment by sgschantz** [comment]
Maybe we could call it something like 'Keyman resource'. It is broad enough to represent both keyboards and lexical models and potential other stuff. It also sounds more like an extra component than sounding like something that might contain all of Keyman. Not sure if 'resource' sounds like technical jargon -- there are probably other options that also sound like an add-on thing.

**Comment by SabineSIL** [comment]
We decided to close in Bug triage meeting

**Comment by mcdurdin** [comment]
@sgschantz says this is fixed :grin:
