### ISSUE TITLE
question: Windows 10 additional system tray icon 

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#5796]
**Describe the bug**
In Windows 10, there is an additional system tray icon. Keyman Engine is using Keyman Core Library("engine.compatability.use_keyman_core" system setting)

What is this icon?
How to remove it?

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 x64 (1802)
 - Keyman version: 15.0.123-alpha

**Comment by mcdurdin** [comment]
This is a debug flag in the 15.0 alpha which reminds testers that the new Keyman Core implementation is in use. Because the Keyman Core integration in Keyman for Windows is brand new, there will potentially be problems and limitations, so we felt it important to be able to see instantly which core is in use (Keyman Core or Windows legacy core). The icon will be removed before we go to stable release. It is only visible if the `engine.compatability.use_keyman_core` system setting is enabled (which it is, by default).
