### ISSUE TITLE
Touch Element Resize Event Doesn't Work

### ISSUE THREAD

**Issue by Sethyboy0** [keymanapp/keyman#64]
When using a device with a touch screen, the blocking elements added by KeymanWeb are created at the same size as their base input. To deal with the issue of inputs that change size, those inputs get a "resize" event added to them that then calls resizeInput on the blocker element on top of them.

The problem is that resize events seem to [only be supported by the window](http://stackoverflow.com/a/18662439/5857510) , meaning they cannot be fired (even manually) in the input element.

I tried to get around this by calling the resizeInput function on the blocking element, but that didn't work as anticipated. While the blocking element expanded to fully cover the expanded size of the input, the fake input inside of it did not. It instead remained the same size and moved position to the top left corner of the input.

I've attached three screenshots showing the problem. The first shows the input being covered as expected, the second what happens when the input is made larger (which was also programmed to fire the resize event), and the third what happens after calling the resizeInput function on the blocking element (specifically the one with the "keymanweb-input" class).

1. ![before element is bigger](https://cloud.githubusercontent.com/assets/11654191/25452571/0ddded02-2a94-11e7-828d-7e58d527f66c.PNG)

2. ![after element is bigger](https://cloud.githubusercontent.com/assets/11654191/25452602/28ec9e7c-2a94-11e7-90b4-1ee3c7334dea.PNG)

3. ![after resizeinput](https://cloud.githubusercontent.com/assets/11654191/25452616/33fbf826-2a94-11e7-9309-52de77cdd99d.PNG)

**Comment by jahorton** [comment]
Recent fixes (as in PR #80) may address this issue, as we ran into similar problems when addressing the dynamic element addition and removal problems.

**Comment by jahorton** [comment]
A lot of work's been done since this was last directly addressed; at present, the undocumented `keyman.alignInputs(true)` should provide a way to forcibly trigger realignment of touch-alias elements over their base controls.  That chains to another internal method which performs the actual alignment on a per-control basis.  (`domManager.touchHandlers.updateInput(`_`element`_`)`).

With a bit of extra work, we can probably make both accessible as API functions to permanently provide them as a workaround to rotation and realignment issues in the future.

**Comment by jahorton** [comment]
To fully resolve this issue with additional API, we should be able to resolve that for 11.0.

That said, if finalizing the extra API function takes over a day's work, we'll push it back to 12.0.
