### ISSUE TITLE
bug(macOS): a log out or restart is needed for the locale switching to take effect

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#6527]
**Describe the bug**

While testing this PR (https://github.com/keymanapp/keyman/pull/6501), for the locale switching to take effect, the os is required to be logged out or restarted.

With the current latest beta version (15.0.232-beta), switch the system language to Amharic and see the error where the Keyman menu doesn't switch to the language (see below).

Right after switching the locale to Amharic (before logging out and/or restarting)

| Big Sur | Monterey |
| --- | --- |
| <img width="390" src="https://user-images.githubusercontent.com/28331388/163126841-83855409-1b3d-4815-9b62-2f154c337b22.png"> | <img width="390" alt="image" src="https://user-images.githubusercontent.com/28331388/163129112-a203b0fa-3af0-40bb-b118-9272bd6dcec2.png"> |

When logging out and logging back in, the menu is now shown in Amharic.
| Big Sur | Monterey |
| --- | --- |
| <img width="390" src="https://user-images.githubusercontent.com/28331388/163129299-54a3fdbe-f126-49bd-ab03-877b41942bd7.png"> | <img width="390" alt="image" src="https://user-images.githubusercontent.com/28331388/163131672-b6681a3c-a0ef-4083-a9e0-2b8e9ae02c94.png"> |

**Expected behavior**

The UI language should have switch to the select language immediately without logging out nor restarting the machine.

---

**Keyman for macOS:**
 - OS:  macOS Big Sur v11.0.1 and Monterey v12.3.1
 - Keyman version: 15.0.232-beta
 - Target Application: Keyman

**Comment by sgschantz** [comment]
@MakaraSok @bharanidharanj I don't believe this is a bug as the system provides a dialog that warns that a restart made may be needed:

![image](https://user-images.githubusercontent.com/89134789/165886895-a7ff514c-a431-4b98-9b42-39ff965b0b2c.png)

In the case of a system extension like Keyman, a restart seems reasonable, but there is also a helpful feature added in MacOS Catalina that is useful for testing. Users can add Keyman as an app in the Language & Region settings and set the language specifically for Keyman. When doing so, the system will ask if you want to restart the app. With this setting, I have not had to restart the Keyman, and it has applied the localization for the selected language.

![image](https://user-images.githubusercontent.com/89134789/165887133-dc0f36c7-80d1-47f3-b02e-2bf9b15ee0d3.png)

If there are issues with a restart being needed sometimes and sometimes not, then it may be because the language was added for the first time as opposed to just being moved up as the preferred language.

**Comment by MakaraSok** [comment]
Quoted from https://www.addictivetips.com/mac-os/change-language-mac/

> If the language that you install is fully supported, it will be installed as a primary language. Your system will need to restart to apply the change.
> If the language that you install is only partially supported, you do not need to restart the Mac.

This might be the confusing part.

Let's close this for now.
