### ISSUE TITLE
bug: Keyman engine start with keyboard selection in Windows

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#6769]
**Describe the bug**
Does Keyman engine start with keyboard selection in Windows?

**To Reproduce**
If the Keyman engine is stopped from the system tray. Does the Keyman engine start with keyboard selection in Windows?
I was thinking, this feature was introduced in few versions back. 

**Expected behavior**
If this is intended.
Keyman engine should start with selection of Keyman keyboard.

**Screenshots**

**Keyman for Windows/macOS/Linux:**
 - OS: Windows 10 (1802) x64
 - Keyman version: 15.0.243-beta
 - Target Application: System

**Comment by mcdurdin** [comment]
Yes, the start-on-demand feature was added in #3772 in alpha release for 14.0.172 but we disabled it by default in #4658 in 14.0.260 in beta release in because it caused a number of usability problems and depended on being started from Scheduled Tasks which proved unstable on many systems.

You can enable the functionality by setting the Keyman system flag `engine.compatibility.use_autostart_task` and play around with it if you want!

We may look at re-enabling it or redesigning it in a future release if we move to a service-based model for Keyman but any work like this is costly and risky...
