### ISSUE TITLE
Keyboard input developer platform

### ISSUE THREAD

**Issue by JanVeb** [keymanapp/keyman#6959]
Hi there, I'm sorry my question isn't directly related to Keyman, but i wanted to try anyway, maybe someone can give me some information I'm looking for

I'm looking for platform with which I can develop keyboard input method that support code in backend as well, it needs to include proper coding language so I can develop it to do stuff, like implement UI auto suggestions window, like when you type, under the cursor, window pops up with suggestions for possible words based on current sequence of letters. Similar how Swype keyboard on mobile devices will offer suggestions. Ability to import trie database, ability to remap keys (as far as I understand, keyman only alows you to remap keyboard keys?), etc.

I've developed this keyboard input in Flutter, while it's great because I can have it run on any OS, it works only inside of the flutter app, i would like to develop this input method so I could use it to type in visual studio, Word, web and everywhere I need to type.

Thought maybe someone seeing this would have some good recommendation or where should I look for it, or terms to search for.

Thank

**Comment by jahorton** [comment]
> so I can develop it to do stuff, like implement UI auto suggestions window, like when you type, under the cursor, window pops up with suggestions for possible words based on current sequence of letters.

We already have support for predictive text in our mobile app versions of Keyman, though we have yet to include this in the desktop/laptop versions.  That's on our radar, but not something we're currently prioritizing highly.

One note about our predictive-text support:  the 'dictionary' used for predictive text is completely detached from the keyboard.  They are 'linked' if they share a common language code; we landed upon this design because it allows a lexical model for one language to work with all keyboards for that language, not just a single one.  (This also keeps the end-user requirements for developing new lexical models lower than otherwise.)

One other note:  our predictive-text is still all "front-end."  There is no communication with a server after the dictionary has been downloaded.  Internally, our "back-end" for this is a client-local WebWorker.

> Ability to import trie database

Our current version of said feature is, in fact, Trie-backed.  That said, if you're willing to spend time and effort, it is possible to code a completely custom lexical model (i.e, dictionary) that our engine can tap into.  JavaScript and/or TypeScript would be the language for this, and you can see code for the lexical models we currently offer at https://github.com/keymanapp/lexical-models.  Most of them use our Trie-wordlist "template"; I don't know that anyone's actually made a fully-custom one yet.

> ability to remap keys (as far as I understand, keyman only alows you to remap keyboard keys?)

... what _other_ type of keys are you thinking of here?

Note that there is a "keyboard language" that Keyman's keyboard uses; it's not _just_ key remapping.  Based on the context of a keystroke, it is possible to write rules that will reorder a few of the most recent characters, combine a base letter with a diacritic mark, or even trigger a keyboard-internal 'flag' that can change the behavior of other rules.

**Comment by mcdurdin** [comment]
> I've developed this keyboard input in Flutter, while it's great because I can have it run on any OS, it works only inside of the flutter app, i would like to develop this input method so I could use it to type in visual studio, Word, web and everywhere I need to type.

This is the entire purpose of the Keyman project -- it's a huge project to support keyboard input anywhere on any platform; as you noted, it's relatively straightforward to do it within a single development environment such as Flutter.

You're welcome to fork the Keyman repo and do whatever you like with it (we use the MIT license) -- or we love pull requests to improve Keyman itself. Not sure we can give much more advice than that!

**Comment by jahorton** [comment]
One last note:  if this interests you or you want to ask questions for more details, please note our [Community site](https://community.software.sil.org/c/keyman/19) - a forum that's probably a little better suited for such a conversation.

**Comment by JanVeb** [comment]
Thank for detailed answer

Didn't know you have prediction already running, though just on mobile platform, would I be able to develop this for desktop from your code base, would need to do it in Pascal, I've never worked with Pascal before, is it hard to learn for someone with skills in Dart and JavaScript languages?

Also do you plan to add Swype functionality to your mobile platform?
This is somewhat similar functionality i need for my desktop keyboard, i know this sounds strange, I don't plan to Swype on physical keyboard, but rather this functionality is similar in nature to functionality i need in my keyboard.

I'll definitely look more into keyman, i like it for being multiplatform, if I could figure out how to work with codebase, maybe I could use it to develop my keyboard in it

**Comment by mcdurdin** [comment]
> would I be able to develop this for desktop from your code base, would need to do it in Pascal? I've never worked with Pascal before, is it hard to learn for someone with skills in Dart and JavaScript languages?

The predictive text engine would be in Javascript, with a wrapper in C++ for Windows, Linux, and probably ObjC + C++ for macOS.

> Also do you plan to add Swype functionality to your mobile platform?
> This is somewhat similar functionality i need for my desktop keyboard, i know this sounds strange, I don't plan to Swype on physical keyboard, but rather this functionality is similar in nature to functionality i need in my keyboard.

This is not currently on the roadmap. Swipe-style input depends heavily on high quality text predictions and AI methods to choose appropriate words. This is not something that most of our target language communities have the resources to develop -- the word-level predictions from a wordlist that we can already do are probably not going to be sufficient.

> Could you please point me into direction how could I implement prediction and pop-up window with predictions for desktop keyboard?

This is not going to be straightforward. We do have plans to add this to Keyman, but it depends on running a Javascript engine to load the predictive text models (as they are written in Typescript which compiles down to Javascript), so that's a big chunk of work to start with. Once we have a Javascript engine in place for each of Windows, macOS and Linux, then we need to integrate with the existing typing, and investigate how we integrate with the OS-level predictive services, if at all. It's probably a 1 year project...

In terms of a popup window, you could look at the Windows-only Simplified Chinese IMX ([Keyman Input Method eXtension](https://help.keyman.com/developer/current-version/guides/develop/imx/)) example which runs on Keyman and provides a popup window: [keyboards#64](https://github.com/keymanapp/keyboards/pull/64). Please note that this code is provided as-is and no guarantees that it works -- but it does show the possibilities.

If/when we do eventually support predictions on desktop, we'd also be supporting javascript-based IMXs, which would make a cross-platform IMX

**Comment by JanVeb** [comment]
This [keyboard#64](https://github.com/keymanapp/keyboards/pull/64) is this one?
https://github.com/keymanapp/keyboards/tree/b433371c3b5cab664a58c259db3a01baeb1c1f1b/legacy/c/cs-pinyin?

On windows it is kinda working, suggestion window pops up, right under cursor, just as I need it, but can't really type with it, can type only 1 letter, and when I type second letter, it replaces previous letter instead to add to it.

On macOs doesn't type at all.

But this is what I need, need this popup window, but from code I can't figure out how to implement this, I mean I can't even figure out where is code, I extract cs-pinyin.kmp file with zip extractor, but inside aren't code files but already compiled code...

Is there some guide on how to implement this popup window with Keyman?

Otherwise, I wanna develop 10 keys keyboard, basically, with 10 keys one is able to type all the letters and punctation, which when leaves loads of keys free, so I can then resign them to another functions, like delete key is then on [ key, so it is much closer and one doesn't have to move fingers to much.

Same can be done with arrow keys and, shift etc, so one can type faster. As said I've already developed this in flutter, and it works, I just want to develop it as keyboard input so I can use it in any text editor, rather than just in flutter app as it is now.

Is anyone from you interested in this? Would be great if I could get at least one more person to help me with that, to at least show me around with Keyman, once I figure it out I can develop it on my own, its rather simple to do, but potentially really powerful productivity boost.

**Comment by mcdurdin** [comment]
Note that Keyman may not be best suited to this project -- while we do allow for input on pretty much any key, we explicitly do not support emitting virtual key events such as arrow keys from the Keyman Engine itself. This is because emitting both characters and virtual keys is complex and the methodology varies dramatically between operating systems. Keyman's primary design goal is supporting languages that are not otherwise supported, so emitting virtual key events falls outside the scope of what we are trying to achieve. Other projects such as AutoHotKey may let you do what you are wanting?

Now in terms of your questions, yes, keymanapp/keyboards#64 is the right PR. The source is available in that PR; https://github.com/keymanapp/keyboards/blob/19e43d0ab898d0566b64e4bba8625f54dcd9c64d/release/c/cs_pinyin/source/keymanimx/KeymanIMX.cpp is the main source file. It is Windows-only (Keyman for macOS has zero support for IMX at present).

We are keen to develop IMX further but we have other priorities at present; we are a small, fully-committed team.

https://help.keyman.com/developer/15.0/guides/develop/imx/ has some documentation on IMX but we haven't touched it for a while.
