### ISSUE TITLE
bug: Failed to get ios Dependencies using carthage

### ISSUE THREAD

**Issue by khashashin** [keymanapp/keyman#7010]
**Describe the bug**
I created a new Swift project using Xcode and also created the `Frameworks` & `Keyboards` groups, as in the KMSample1 or KMSample2 projects.

In the root directory, where also the file `*.xcodeproj` is located, I created the file `Cartfile` with the following content (same as [here](https://github.com/keymanapp/keyman/blob/ios-release-stable-14.0.118/ios/Cartfile)
```
github "marmelroy/Zip"
github "DaveWoodCom/XCGLogger" ~> 6.1.0
github "dennisweissmann/DeviceKit" ~> 2.3
github "ashleymills/Reachability.swift"
github "getsentry/sentry-cocoa" ~> 4.4.3
```

Then I used the installation command:
```
carthage update --use-xcframeworks
```
And get following error:
```
*** Cloning XCGLogger
*** Cloning Zip
*** Cloning Reachability.swift
*** Cloning sentry-cocoa
*** Cloning DeviceKit
*** Checking out DeviceKit at "2.3.0"
*** Checking out sentry-cocoa at "4.5.0"
*** Checking out Reachability.swift at "v5.1.0"
*** Checking out XCGLogger at "6.1.0"
*** Checking out Zip at "2.1.2"
*** xcodebuild output can be found in /var/folders/v5/w0wc5zjs5x311qdlngmzsgkc0000gn/T/carthage-xcodebuild.fdPX3w.log
*** Downloading sentry-cocoa binary at "4.5.0"
*** Building scheme "DeviceKit" in CocoaPodsVerification.xcworkspace
*** Building scheme "Reachability" in Reachability.xcodeproj
*** Building scheme "Sentry" in Sentry.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/khashashin/Git/GitHub/chechen-latin-keyboard-layout/ios/Chechen\ Latin\ Keyboard/Carthage/Checkouts/sentry-cocoa/Sentry.xcodeproj -scheme Sentry -configuration Release -derivedDataPath /Users/khashashin/Library/Caches/org.carthage.CarthageKit/DerivedData/13.4.1_13F100/sentry-cocoa/4.5.0 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive VALIDATE_WORKSPACE=NO -archivePath /var/folders/v5/w0wc5zjs5x311qdlngmzsgkc0000gn/T/sentry-cocoa SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/khashashin/Git/GitHub/chechen-latin-keyboard-layout/ios/Chechen Latin Keyboard/Carthage/Checkouts/sentry-cocoa)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/v5/w0wc5zjs5x311qdlngmzsgkc0000gn/T/carthage-xcodebuild.fdPX3w.log
```

**To Reproduce**

1. Create Swift Project
2. Create `Carthage` file as described above
3. Run installation command as described above

**Expected behavior**
Successful installation of dependencies

**Screenshots**

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/17837758/181592778-1ce6dc47-6d3f-46a6-82a5-0f1cdd2c61fb.png">

---

**Keyman for iPhone/iPad:**
 - Device:  iPhone 13 Simulator
 - OS: 14
 - Keyman version 14.0.118
 - Target application: Safari

**Keyman Developer:**
 - OS: Windows 11 x64 -->
 - Keyman Developer version: 15

**Comment by jahorton** [comment]
There are a few things worth note here.

1.  This is distinctly a `carthage` error, with the build failure happening before you reach any Keyman code.  Please keep in mind that our help here will likely be more limited than what you could receive from the folks at https://github.com/Carthage/Carthage.
2. I see that you're compiling against Keyman 14.0.118.  It's worth note that we ourselves aren't successfully compiling it at this time due to Apple forcing updates to our toolchain.  I'd highly advise working with our `stable-15.0` branch.
3. As part of the last point, #5120 may be relevant for you; we're currently working with a more recent version of the Sentry dependency as of `stable-15.0`.  We don't have this issue when working with that version.
4. Note that whenever you do a `carthage install`, there's also a `Cartfile.resolved` file that gets generated.  If you want to ensure a perfect match against the versions we're using, you should be able to edit the versions it picked there and re-attempt the `install`.

A bit more on point 3 above - Sentry 4.x is old enough that its Xcode project may not be able to support the .xcframework feature that was added to Xcode relatively recently.  If I had to guess, that's probably going to be your biggest sticking point at present.  Noting that you're targeting deployment for iOS 14 and higher, Keyman 15.0 and its updated Sentry version should pose no compatibility issues for your current compile-target settings; Keyman 15.0 is set to support versions as low as iOS 12.0.

**Comment by khashashin** [comment]
@jahorton thank you very much for this detailed description. I have just followed the instruction on keyman [help ](https://help.keyman.com/developer/engine/iphone-and-ipad/15.0/guides/system-keyboard/) website, if I understood you correctly, we need to use the latest version of the Keyman repository, i.e. the `stable-15.0` branch. What confused me especially are the tags, since there are `ios-release-...` tags.

**Comment by khashashin** [comment]
This link point to version 14 

https://help.keyman.com/developer/engine/iphone-and-ipad/15.0/guides/system-keyboard/
![image](https://user-images.githubusercontent.com/17837758/181658568-03958c8e-426b-4883-83ca-0b2fa7cc8d7a.png)

**Comment by jahorton** [comment]
> @jahorton thank you very much for this detailed description. I have just followed the instruction on keyman [help ](https://help.keyman.com/developer/engine/iphone-and-ipad/15.0/guides/system-keyboard/) website, if I understood you correctly, we need to use the latest version of the Keyman repository, i.e. the `stable-15.0` branch. What confused me especially are the tags, since there are `ios-release-...` tags.

Those tags indicate the state of the repo when we release each specific version of Keyman.  So, `ios-release-15.0.10`, if it exists, corresponds to when we finalized 15.0.10 (an alpha version).  The _branches_ correspond to the latest state of the corresponding major version.

> This link point to version 14

:+1: Ah, looks like we missed that when updating help for the new version.  We'll get that fixed.

**Comment by mcdurdin** [comment]
FWIW, we stopped using per-platform tags (e.g. `ios-release-x.y.z`) a couple of years ago: all platform releases are simultaneous for a given version. (We do not currently use the releases feature on GitHub; we may start using it again in the future, as we now have unified releases on all tiers - alpha, beta, and stable.)

Release tags are available for each release, e.g. `[release-15.0.267](https://github.com/keymanapp/keyman/releases/tag/release-15.0.267)` corresponds to 15.0.267 on the `stable-15.0` branch. Any release tag without a `-` suffix is a stable release.

**Comment by khashashin** [comment]
I think this issue can be closed as it is not worth investing the time to fix the build process in such an old version. so just for the conclusion use the latest stable version of keyman especially if it is a new project.
