### ISSUE TITLE
bug(android): the word selected off of the suggestion banner doesn't get searched in webonary.org [OBU]

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#7141]
**Describe the bug**

on behalf of a user:

> When I typed a word into the Webonary search box I noticed that there's something strange going on with some words selected by predictive text in Keyman. 
> 
> For example, if I select the word នតាម់ from the predictive text bar (see red highlight in the attached screenshot), the dictionary search doesn't find the word. 

**To Reproduce**

1. type នតាម using Bunong (SIL) keyboard on [https://www.webonary.org/bunong/](https://www.webonary.org/bunong/)'s search box
2. pick នតាម់ and click to search
3. See error of no search result for the word 

The result will be shown after deleting the invisible trailing space, i.e. ZWSP. Or typing the whole word manually without using the word from the suggestion bar.

---

**Keyman for Android:**
   Device:              Emulator
 - OS:                  Android 11
 - Keyman version:      15.0.268
 - Target Application:  https://www.webonary.org/bunong/

---

**Keyboard**
 - Keyboard name:     sil_bunong
 - Keyboard version:  1.4
 - Language name:     Central Mnong

**Additional context**

**Comment by mcdurdin** [comment]
This is one of those tricky things to figure out which app is responsible. In normal use, appending a ZWSP is useful for the keyboard, because that allows for good word wrapping in the absence of a system word wrapper for the language. But it's a little tricky because many apps don't really have any awareness of ZWSP, and so we may see similar outcomes with e.g. search engines etc.

In this case, I think I would encourage webonary to strip all whitespace (including zwsp) from beginning and end of input. Perhaps you can open an issue at https://github.com/sillsdev/webonary/issues and reference this one?

**Comment by darcywong00** [comment]
From team standup, I think @MakaraSok reported this is an issue on Webonary that their team will handle.

**Comment by mcdurdin** [comment]
Closing here as this will be resolved on webonary side.
