### ISSUE TITLE
[windows] Not seeing installed "Jorai" keyboard in Configuration

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#715]
The Jorai desktop keyboard doesn't appear in Keyman Desktop Configuration.

## OS configuration
On Windows 10 that has Keyman Desktop 10.0.1055.0 Beta and Keyman Developer 10.0.1055.0 installed

## Steps to reproduce
1. From Keyman Desktop Configuration, select "Download keyboard..."
2.  In the search dialog, choose "Jarai" (Jorai keyboard) --> "Jorai for Windows" and install the keyboard

 
![layouts](https://user-images.githubusercontent.com/7358010/37949597-8820d7ea-31bf-11e8-8a9c-1ea14f8db969.png)

3. In the Windows toolbar, click Keyman Desktop add see other keyboard (Khmer) is an option, but not Jorai.

![configuration options](https://user-images.githubusercontent.com/7358010/37949697-ee10a7f6-31bf-11e8-88a2-7902258c63bc.png)

Is this an issue of "Jorai" not appearing as a language in the keyboard layout tab?

**Comment by mcdurdin** [comment]
Okay, part of the issue here is the language tag for the keyboard should be `jra-Latn`, not just `jra`. For now, we will require keyboard developers to specify script if suppress-script is not defined for the given language tag. See related issue keymanapp/keyboards#259.

Manually adding the language is resolved with #827

**Comment by mcdurdin** [comment]
Fixed with #892
