### ISSUE TITLE
bug(android): polish - toast notifications when there’s nothing to update are annoying

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7170]
**Describe the bug**

From a team review of the Keyman for Android UX (#7161)

There is no need to show a toast about checking for updates, nor the outcome of the update check. Particularly because these toasts can appear when using the system keyboard, which is then completely out of context for the user.

We should reserve toasts only for user-initiated actions that have a delayed asynchronous result, and perhaps for serious errors.

---

**Keyman for Windows/macOS/Linux/iPhone/iPad/Android:**
 - Device:             Samsung A90 5G 
 - OS:                 Android 12 
 - Keyman version:     15.0.269-stable

**Comment by darcywong00** [comment]
Can you clarify the desired UX for these two cases? (since they involve checking if there's an associated dictionary to download and involve the same cloud queries)

## Keyman app after installing a keyboard package
* Toast notification about "Checking for associated dictionary to download"
* Toast notification  "No dictionary to download"

## Language Settings menu

* User clicks the bottom link "Dictionary - Check for available dictionary"
* Toast notification about "Checking for associated dictionary to download"
* Toast notification that "No associated dictionary to download"

This seems to require some acknowledgement of the user clicking the menu
But all the other times, maybe we remove all Toasts about checking for available dictionaries and providing status?

**Comment by mcdurdin** [comment]
> Keyman app after installing a keyboard package

In this case I don't think we need any toasts except one for "new dict has been installed".

> Language Settings menu

Perhaps this would be better shown in a popup rather than fully background with toasts, long term (or at least a banner). But happy to leave these toasts for now.

**Comment by darcywong00** [comment]
> I don't think we need any toasts except one for "new dict has been installed".

:+1: 

Maybe for Language Settings menu, I just combine the feedback of the two Toasts into a single
"Keyman will download associated dictionary if it's available"?

**Comment by mcdurdin** [comment]
OK
