### ISSUE TITLE
bug(web): Rapid typing on first caps letter sometimes gives TWo cap letters (touch) 🐵

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7173]
**Describe the bug**

Repro: Press Shift, type two letters very rapidly. They will both get capitalized. (Two thumb typing)

Per @jahorton:
* [JH] Does repro on iOS.
* [JH] I suspect it’s due to how the Web OSK operates - for this scenario, the user does press both shift-layer keys before the display-layer is updated.

**Screenshots**

https://user-images.githubusercontent.com/4498365/187534413-92cf5c92-5c95-40bb-b226-e85eef21b61c.mp4

---

**Keyman for Windows/macOS/Linux/iPhone/iPad/Android:**
 - Device:             Samsung A90 5G 
 - OS:                 Android 12 
 - Keyman version:     15.0.269-stable

**Comment by jahorton** [comment]
> I (@jahorton) have been able to confirm that this Sentry event is highly related.
> 
> Sentry issue: [KEYMAN-WEB-4J](https://sentry.io/organizations/keyman/issues/3413613013/?referrer=github_integration)

A bit of further thought here:  a similar (Sentry) issue arose with #6898, which has been mitigated by #7543.  In _that_ case, the issue arises from the wholesale swapping of the active keyboard - an operation that is particularly asynchronous if the keyboard being swapped in has not yet been loaded.  In this case, the issue is that we're swapping the _layer_ during JS event processing, rather than the keyboard - but the overall pattern is the same - a swap in active state occurs during JS event processing before the second event has a chance to start, especially since JS is explicitly single-threaded and doesn't do interrupts.

Noting the mitigation strategy taken by #7543, a similar strategy (using closure-based handlers that lock in the touch's original active layer) could be used to nullify the Sentry error report linked above.  That said, the base issue posted here - the "TWo caps letters" issue - would remain.

**Comment by jahorton** [comment]
A possible strategy to resolve the "TWo caps" issue instead would require a bigger rework, but it's something that the `feature-gestures` branch is decently poised to do come integration time.

Part of our fat-finger algorithm is quite well-suited to detecting the closest key to an incoming touchpoint.  If we ignored the TouchEvent's target-element metadata and instead relied entirely on that touch-proximity algorithm, that _would_ dynamically adjust correctly (to user expectations) after a layer swap.  That said, this is _**almost definitely not**_ a change we should "throw in" this late in the release cycle.

**Comment by mcdurdin** [comment]
Seems like a good possibility.

> That said, this is _**almost definitely not**_ a change we should "throw in" this late in the release cycle.

Agreed.

**Comment by bharanidharanj** [comment]
@mcdurdin I am able to reproduce this issue with the latest Keyman 17.0.205 alpha build in Android OS . (Version 5, 9 and 12)

**Comment by jahorton** [comment]
That sounds correct; the fixes are currently only on the feature-gestures feature branch.

**Comment by mcdurdin** [comment]
@jahorton this apparently failed with 17.0.238-alpha (see #10598), but this was apparently fixed with 17.0.230-alpha with the merge of #7324. Are you able to follow up with @bharanidharanj?
