### ISSUE TITLE
Khmer characters on each key are too big and they can't be seen

### ISSUE THREAD

**Issue by darcywong00** [keymanapp/keyman#74]
Original issue: https://github.com/sillsdev/keyman-archive-android/issues/7
Then opened as https://github.com/sillsdev/keyman/issues/10 (refer for more screenshots)

<a href="https://github.com/MakaraSok"><img src="https://avatars0.githubusercontent.com/u/28331388?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [MakaraSok](https://github.com/MakaraSok)**
_Thursday May 11, 2017 at 02:52 GMT_
_Originally opened as https://github.com/sillsdev/keyman-android/issues/7_

----

The Khmer characters on each key are too big and they can't been seen. This is with the Khmer NiDA keyboard from the Keyman keyboard repository.

Please see the screenshot here:

![image](https://cloud.githubusercontent.com/assets/4498365/25930467/86026522-3630-11e7-8c34-29cf3c2febf4.png)

**Comment by jahorton** [comment]
This appears to be caused due to a deficiency in the font we're using... it seems that its internal layout data either got corrupted or is being read incorrectly.

Swapping the font out with, for example, the font listed [here](http://www.selapa.net/khmerfonts/fontinfo.php?font=89) corrects the issue within KeymanWeb.

It's not so much a problem with KeymanWeb as much as it is with the keyboard management database/repo.
