### ISSUE TITLE
[Web] If the sp member of a key in the touch layout is not a string, then the key will display incorrectly

### ISSUE THREAD

**Issue by jahorton** [keymanapp/keyman#743]
From the recent Keyman Consultation Training workshop:

During a live demo, we noticed that Developer's KMW testing page didn't properly replace the special `*modifier*` codes with their PUA equivalents.  The standard 'space' wasn't done quite right, either.

We noted this may be a bug with the default ('traditional') template when filling from the Desktop OSK.

**Comment by mcdurdin** [comment]
Need to find a repro for this one.

**Comment by mcdurdin** [comment]
This arises when the `"sp"` member of the touch keyboard JSON is a number and not a string, e.g.:

```
              {
                "id": "K_BKSP",
                "text": "*BkSp*",
                "width": 100,
                "sp": 1
              }
```

The proper place for a full for fix for this is in KeymanWeb. See also #119. A partial fix will be made to the 'Import' routine in Keyman Developer so that imported keyboards get the string treatment for now.

**Comment by jahorton** [comment]
Now that Developer-side work has been completed for this issue, the remaining work is a duplicate of #119.  The new, highly-related extra detail (regarding 'sp') has been documented on that issue.
