### ISSUE TITLE
bug (linux): Keyboard display name starts with first listed supported language

### ISSUE THREAD

**Issue by rik-shaw** [keymanapp/keyman#7548]
### Describe the bug

We may be using Keyman in a "non-recommended" approach, having broad keyboards based on a script (SIL Ethiopic, for example) or instead have a country-wide latin keyboard (SIL EL - Ethiopian Latin) supporting many languages. With this approach, in Linux, the negative is that the underlying ibus system displays the first listed language at the beginning of the keyboard name. So for SIL Ethiopic, for example, the keyboard display name in the ibus selection list is "Amharic - SIL Ethiopic", for example. See screenshot:
![sil ethiopic display name](https://user-images.githubusercontent.com/2560632/198067552-09de0cba-d503-4528-8c32-274b68252d86.png)

Or here is how SIL EL - Ethiopian Latin looks in the ibus keyboard selection list:
![sil el display name](https://user-images.githubusercontent.com/2560632/198067678-10c45d4f-828b-48cb-bf8c-718020eb94df.png)

Note: the "Other - xxyyzz" items in the ibus keyboard selection list are ibus-kmfl keyboards, which all get categorized under the generic language name of "Other": also not ideal but at least not frustrating for users that are confused or even offended to see a different language name associated with their keyboard.

Possibly an adjustment as to what languages are supported by the keyboard needs to be made, could possibly some generic reference be made there that would show something like "Multiple - SIL Ethiopic" or "Saba - SIL Ethiopic" ("Saba Script" is a common understood name for the Ethiopic script in Ethiopia). Maybe "Ethiopic - SIL Ethiopic". Similarly, maybe "Latin - SIL EL - Ethiopian Latin" could be displayed. Yes these suggestions are a bit redundant, but better than displaying only a single language name? 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.271-1+focal1

### Operating system

Ubuntu / Wasta-Linux - Cinnamon DE

### Device

Linux laptop

**Comment by mcdurdin** [comment]
Thank you for this report. I have initially tagged this to be resolved in 17.0, but bear with us as we will be working through a re-triage of open issues shortly. @ermshiperete will also review this when he returns from vacation.

**Comment by ermshiperete** [comment]
@rik-shaw How do you install the keyboards? If you use the Download button in `km-config` (or search on keyman.com) and search for a language and then select and install a keyboard for that language, the keyboard will get installed for that language.

However, if you search for the keyboard instead of the language it'll install the keyboard for the first language.

You can also do it from the command line, e.g.

```
km-config -i keyman://download/keyboard/sil_el_ethiopian_latin?bcp47=ssy-latn
```

If you have a local .kmp file you can also append the bcp47 tag:

```
km-config -i Downloads/sil_el_ethiopian_latin.kmp?bcp47=ssy-latn
```

**NOTE** that the specified bcp47 tag needs to be one of the languages the keyboard lists.

If you use `km-package-install` (which is the only way you can install into the shared area) there's currently no way to specify the language. I'll add an option for that.

**Comment by ermshiperete** [comment]
Created #7725 for adding a bcp47 parameter to `km-package-install`.

**Comment by rik-shaw** [comment]
@ermshiperete thanks for the explanation above. In our case we use more of a "regional keyboard" ("Ethiopian Latin" is the main one used that supports all Latin orthographies in Ethiopia, for example) and have it pre-installed in all Ethiopia computers. So at the time of creating the ISO what of the many supported languages will be used by the end user.

I understand our keyboards go against Keyman design which assumes you first find your language then you choose what keyboard you want to use. Personally I would prefer nothing but keyboard name showing, but second preference would be a more general sort of tag (maybe of the script, so `Latin - SIL EL - Ethiopian Latin` or `Ethiopic - SIL Ethiopic`). As you can see I have included the script name in the keyboard names making that redundant but again it would be better than showing a language not used by the end user.

Hmm I'll have to think about this a bit more but any suggestions are welcome!

**Comment by rik-shaw** [comment]
Maybe I should learn more about BCP47, my search brought me here: http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry

In that list I found this:
```
Type: script
Subtag: Ethi
Description: Ethiopic
Description: Geʻez
Description: Ge'ez
Added: 2005-10-16
```

So would it be possible to use such a "script" tag of "Ethi" so that Keyman would display it as "Ethiopic - SIL Ethiopic"? Or, for the Latin based keyboard use this:
```
Type: script
Subtag: Latn
Description: Latin
Added: 2005-10-16
```
So it would display as "Latin - SIL EL - Ethiopian Latin"?

**Comment by mcdurdin** [comment]
The basic issue you're running up against is that BCP 47 language tagging has become a standard across all platforms. This is a good thing: tagging text with the correct language helps future text processing -- spell checking, auto correction, text suggestions, sorting, etc.

This is something that is implemented at the system level -- it's not just Keyman.

BCP 47 tags _must_ include a language subtag, and can optionally include script, region and other subtags. So you can't get away from specifying a language.

In my opinion, a generic script tag is helpful for _us_ because we are making generic solutions for many or even all languages for a given script, but is a negative for our _users_, who are generally working in a subset of those languages. (Similarly, a generic Ethiopic script keyboard is a good starting point, but not necessarily the ideal solution for the user, because it will include letters that are probably not relevant or not optimally placed for the specific language(s) the user wants to use.)

How to solve? Given you cannot know which language(s) your users are wanting to work in, ideally, your ISO includes a pick-your-input-method-language (and for even more points, pick your UI language!) setup screen, just like Windows, macOS and Ubuntu (from memory) do at the first step of installation. Users can then optionally add other languages, or perhaps you would also slipstream in majority languages for the region.

The simpler alternative is to just add the keyboard with, say, Amharic as the most widely spoken language, but that may not be much more palatable than linking to the first language by alphabetic order!

Caveats:
* The level to which language tagging is applied to data varies wildly across applications today, but the more we can do to tag the data correctly, the better.
* [Code switching](https://en.wikipedia.org/wiki/Code-switching) is a thing. The pattern of tagging text for language is probably too simplistic because it doesn't really cope with this. But that's a problem for another day!
* And yes, many people are working across multiple languages with non-identical character repertoires, making keyboard choices even harder.

**Comment by ermshiperete** [comment]
Feel free to request re-opening or create a new issue if you think the suggested solutions won't work.

**Comment by rik-shaw** [comment]
@mcdurdin thanks for the detailed feedback above. A keyboard picker dialog could be helpful, and I will consider if there is any way to consider that in the future. For now I think I need to get a working solution that will have Keyman keyboards pre-installed at the system level. Our IT but also language consultants and advisors all help support new users (and even old users), and often these users benefit from the broader consistency of how to type that someone working in other languages can guide them with to make "special characters". So the standardization is helpful, even  though yes as you note it means the keyboard can make many characters they won't use, and may have some of their characters be ergonomically unfriendly. So certainly custom keyboards would be the best solution, and I should work to make sure they are available. But also having universal keyboards in addition / or as a "foundation" are helpful.

My new proposal for your consideration is to do this: use the language name of the "original / old language of the script": all languages using Ethiopic script (or Saba, more correctly named) would universally agree (and not have political associations) with Ge'ez (effectively "Ethiopic Latin", not commonly used by modern languages). Similarly, Latin based Ethiopian languages would not have problems with "Latin" being the identified language.

So my SIL Ethiopic keyboard would use this:
```
Type: language
Subtag: gez
Description: Geez
Added: 2005-10-16
```
and would then have this display in the keyboard menu: `Geez - SIL Ethiopic`

Similarly, my SIL EL - Ethiopian Latin keyboard would use this:
```
Type: language
Subtag: la
Description: Latin
Added: 2005-10-16
Suppress-Script: Latn
```
hopefully that would then display this in the keyboard menu list in Cinnamon: `Latin - SIL EL - Ethiopian Latin`

I will make some local tests of this to consider (not certain, for example, if the `Suppress-Script: Latn` will cause any issues)

**Comment by mcdurdin** [comment]
I understand why you are looking at doing this but I don't know if I really want to support it. I think in reality this is trying to solve a limitation in Wasta and the install experience in the wrong place (by patching around the problem in the keyboard metadata).

FWIW, we have spent a _lot_ of time unwinding hacks like this which have been pragmatic and quick solutions at the time, and so I am not enthusiastic. Doing this leads to long term data quality problems, because all the language data gets tagged with `gez` or `la` (or `gez-Latn`, see below) -- particularly bad where there is more than one language in use in a document. Generally it has to be right at input time because the cost of fixing it in existing data in the future is too high.

This solution will also causes problems on other platforms and in our keyboard database on keyman.com. For example, the Ethiopian Latin keyboard appear in our keyboard search under 'Latin' language, which is just wrong and will lead to confusion.

A mitigation for the hack, which is still not the right answer: could you use `gez-Latn` instead of `la`? It's still wrong but it least it is the right continent.

Philosophy: as the system developers, I think we have a responsibility to build systems which address these problems, rather than patching around them. Our users are not going to understand the issues, and shortcuts which _we_ have taken in the past have had significant costs. This is an ongoing story for minority and Indigenous languages. This was particularly bad in Windows days in the past where language codes were defined in a spreadsheet held in Redmond, but with open source, we have the opportunity to do this the right way now.

**Comment by rik-shaw** [comment]
@mcdurdin thank you for your patience with me and your time taken to consider and reply. `mul (Multiple languages)` does seem like a good compromise. I think from the explanation on #8598 in order for it to be possible in Linux (ibus) I need to define `mul` as a 'supported language`. Would this be accepted by Keyman if I add `mul`? I would follow the same approach with the 2 SIL Ethiopic keyboards.

Your notes about text-to-speech, machine translation, etc. needing the text correctly tagged with language metadata makes sense looking ahead. As a comment on this "eventual bigger picture reality" I think a good way for me to look at it is to have SIL EL and SIL Ethiopic installed as "lowest common denominator" keyboards that can be pre-installed on systems but work toward each language having its own keyboard as well, which is what I think you have been trying to encourage me to do for some years. Rest assured you have made a convincing case for this, albeit one I will need some time to implement.

Regarding not including English, I can accept that, but I also do note that some users will type English documents with the EL keyboard. An initial design goal (that users love, flawed as it may be) was to be able to use the single EL keyboard for all their "Latin-based text needs."

**Comment by mcdurdin** [comment]
> I think from the explanation on #8598 in order for it to be possible in Linux (ibus) I need to define `mul` as a 'supported language'. Would this be accepted by Keyman if I add `mul`? I would follow the same approach with the 2 SIL Ethiopic keyboards.

Yes, that's an acceptable compromise from my perspective.

> An initial design goal (that users love, flawed as it may be) was to be able to use the single EL keyboard for all their "Latin-based text needs."

Yep -- I think that Keyman for Linux doesn't allow installing the same keyboard for multiple languages (@ermshiperete is this right?), and if this is the case, then that's a gap we should also address, because there will be a user at some point who wants to do things the "right way" (aka the lang-tagging way).

**Comment by ermshiperete** [comment]
> Yep -- I think that Keyman for Linux doesn't allow installing the same keyboard for multiple languages

I thought that would be possible, but you're right, @mcdurdin, this doesn't currently work if you use `km-config` or `km-package-install`. I created #8619.

However, you can manually add the keyboard for additional languages in the system keyboard settings (if the languages are listed under 'supported languages' in the keyboard).
