### ISSUE TITLE
bug(android): Inconsistent behavior of Shift Key while using Keyman with external USB Keyboard

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#7721]
### Describe the bug

Pressing a letter from OSK outputs Capital letter, when the Shift Key is in enabled state. While using External Bluetooth Keyboard or External USB Keyboard, Pressing a letter from the Keyboard outputs Small letter, even the Shift Key is in enabled state. 

### Reproduce the bug

1. Install Keyman 16.0.102- beta build in Android Mobile device. (Here, I am using Redmi Note 8 Pro - Android 11.0 Version).
2. Connect the mobile device (via USB connector) with an external USB Keyboard. 
3. Open Keyman In-App. 
4. Verify that the default (sil_eurolatin) OSK appears on the device. 
5. Verify the Shift key is in the enabled state. (ie., it appears in the blue colour).
6. Press 'a' from the OSK. 
7. Verify the letter 'A' appears on the text area. 
8. Clear the text and verify the Shift key is in the enabled state. 
9. Type 'a' from the USB keyboard. 
10. Here, I noticed that small letter 'a' appears on the text area. 

..using OSK

https://user-images.githubusercontent.com/19683143/201939676-a606fe95-557e-437e-9ac6-74186f41bce0.mp4

..using external USB keyboard

https://user-images.githubusercontent.com/19683143/201939716-1dff1fa8-b9f6-4bb0-8519-767f6e87a194.mp4

### Expected behavior

Typing 'a' from the external USB keyboard should produces letter 'A' on the text area, when the Shift key is in enabled state. 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.102-beta

### Operating system

Android 11.0

### Device

Redmi Note 8 Pro 

### Target application

Keyman In-App

### Keyboard name

English - EuroLatin (SIL)

### Keyboard version

2.0

### Language name

English

**Comment by mcdurdin** [comment]
Thanks for the report. This is actually by design. The touch keyboard layers do not have a 1-to-1 correspondence to the modifier keys on a physical keyboard. It becomes hard to know what to do if a user clicks the Shift key on the touch keyboard, then also presses Shift on the physical keyboard, and so on.

So, the shift, caps, ctrl, alt etc on the physical keyboard have no effect on the touch keyboard. Likewise, the shift, numeric, symbol, caps etc on the touch keyboard have no effect on the physical keyboard.

This is unlike the "On Screen Keyboard" on desktop devices, which present an on screen version of the physical keyboard, and which have a one-to-one correspondence with modifiers. The "On Screen Keyboard" does interact with the modifier keys on the physical keyboard, and vice-versa.
