### ISSUE TITLE
bug(windows): backspace with selected text deletes an extra character in TSF only

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#7870]
### Describe the bug

Per Jeff Heath at https://community.software.sil.org/t/ios-and-android-undesirable-behaviour-with-selected-text/6986/2:

> ... unexpected behavior on Windows 11 (but I believe also on Windows 10 as well) when I have some text selected and I press backspace. It deletes the selected text, but also the previous character.
>
> ...
>
> I can demonstrate the behavior right now in Word 2019. With my keyboard activated, type “A test”, select “test” and type backspace, and the space is deleted as well. It doesn’t do this in LibreOffice Writer.
>
> I have seen this behavior for quite some time, maybe a year, but I don’t remember it happening before that. So I think it must have happened with some Keyman version change.

This looks like a regression, perhaps in Keyman 15? We should track down the exact release where this behaviour changed.

### Related issues

* #7865 
* #7866

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

15.0.274

### Operating system

Windows 11

**Comment by mcdurdin** [comment]
* Tested and replicated on Keyman 16.0.119-beta, with both Keyman Core on and off.

**Comment by rc-swag** [comment]
These are just some notes I have as much for myself to investigate further. 
As noted a long-standing issue with the TSF.
To Investigate 
 - How is Keyman is using the TSF (interface) to interact with select text (if at all) Verses how the TSF applications expect it to act with selected text and backspace.  For example I can see there is a `SetText` range command. 
 
I noticed select text and pressing delete, just deletes the text select and select text and pressing a character key causes the replication of the selected text.

**Comment by rc-swag** [comment]
Further information from a new community site [post](https://community.software.sil.org/t/extra-character-deleted-with-selected-text-in-microsoft-word/8846)  points out the direction of the selection determines which extra character is deleted. 

> When I select a text in Microsoft Word, BACKSPACE deletes selected texts + an extra character (the previous or following one, depending on what direction I selected the text. 

@Nnyny  has also created steps to reproduce. 

I was investigate on a community site [post](https://community.software.sil.org/t/extra-character-deleted-with-selected-text-in-microsoft-word/8846) and able to reproduce a similar behavior on my computer. Whether I selected from left or right, it will delete the extra character(or a space) at the left. 

### Reproduce the bug

1. Open MS Word
2. Type 'mySchool'
3. Select 'School' and click backspace to delete it 
4. Show only the letter 'm' 

### Expected behavior

'School' got deleted and we get 'my'

### Related issues

_No response_

### Keyman apps
- [X] Keyman for Windows

### Keyman version

17.0.326

### Operating system

Windows 11 Home Single Language 22H2

### Target application

Microsoft Word 2019

### Keyboard name

US Basic

**Comment by rc-swag** [comment]
With logging today I can see an issue with how the Windows engine is interacting with the core. The windows is setting the context in the core `km_core_state_context_set_if_needed` with the context preceding the selected text. The core then returns the text do delete to be the last letter of that context which is the text before the selected text. I further inestigation to complete to see how the windows engine should be interacting with the application. Just recording this info here.

**Comment by Nnyny** [comment]
More information from the [post](https://community.software.sil.org/t/extra-character-deleted-with-selected-text-in-microsoft-word/8846/7): 

> Hello! I’d like to report another bug, hoping this is useful. It’s a similar issue: when selecting a text and there’s no character to delete, the text formating is deleted instead.
> 
> For example, if a text is bold and in italics, and I double click on it to overwrite it with new text, it comes out as regular (again, if there’s no extra character to delete, e.g. at the beginning of a paragraph.



![c8b32e74929961498fe172ed11f78151ca192bfd](https://github.com/keymanapp/keyman/assets/123520338/896b29f4-6938-4310-8b7f-5a9e28e739d6)
