### ISSUE TITLE
Feature request: CAPS LOCK number pad

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#794]
Hello,

Number row is required to be separately treated in CAPS LOCK state.

This way, we can use the CAPS LOCK for Hindu-Arabic or International numbers and normal state for the intended language numbers.

Apple XML based keyboard support this.
https://developer.apple.com/library/content/technotes/tn2056/_index.html

Thanks.

**Comment by jahorton** [comment]
This is already supported in the Keyman keyboard definition language - you can check for either `[CAPS]` or `[NCAPS]` as part of a rule's modifier set for a keystroke.  For example,

```
+ [NCAPS K_1] > '1'     c Only matches the '1' key if CAPS_LOCK is not pressed.
+ [CAPS K_1] > 'i'      c Only matches the '1' key if CAPS_LOCK is pressed.
+ [NCAPS K_2] > '2'
+ [CAPS K_2] > 'ii'
```

Without specifying either `NCAPS` or `CAPS`, a rule will apply regardless of CAPS_LOCK state.  That is,
```
+ [K_3] > '3'           c Ignores CAPS_LOCK, outputting '3'.
```

Do note that the following combination is illegal because both rules would apply when CAPS_LOCK is on:
```
+ [K_4] > '4'           c Matches the '4' key regardless of CAPS_LOCK state.
+ [CAPS K_4] > 'iv'     c ERROR: Conflicts with previous rule; both match K_4 with CAPS_LOCK on.
```

**Comment by MayuraVerma** [comment]
thanks

**Comment by MayuraVerma** [comment]
+ [NCAPS K_1] > '1'     c Only matches the '1' key if CAPS_LOCK is not pressed.
+ [NCAPS K_2] > '2'
+ [CAPS K_1] > 'i'      c Only matches the '1' key if CAPS_LOCK is pressed.
+ [CAPS K_2] > 'ii'
+ [SHIFT K_1] > 'a'  
+ [SHIFT K_2] > 'b'

This is working in debugging. It is not working , when installed.

Issue is
------
CAPS locks state is picking same as NCAPS state when installed.
------
Please check

**Comment by mcdurdin** [comment]
@MayuraVerma Can you try with 10.0.1081.0 beta please?
