### ISSUE TITLE
chore(windows,developer):  Use VsDevCmd.bat as replacement for vcvarsall.bat

### ISSUE THREAD

**Issue by SabineSIL** [keymanapp/keyman#8076]
In `developer/src/kmcmplib/build.bat`  (l.110) we have a comment about `vcvarsall.bat` stating we would need to find a different solution for this.:
```
rem Standalone build, so we'll make the environment available to the caller
rem Also setup
rem Note: Visual Studio 2022 doesn't provide vcvarsall.bat, so we'll have to find a different solution

```
There there is **VsDevCmd.bat** available in VS2022. This might be used instead. 

See comment **https://github.com/keymanapp/keyman/pull/6980#discussion_r1060401824   in feat(developer): cross-platform kmx compiler 🚑 https://github.com/keymanapp/keyman/pull/6980**

**Comment by mcdurdin** [comment]
We need to fix these paths on the build agents as well, as they have hard-coded refs to 2019 in about 4 build steps...

**Comment by mcdurdin** [comment]
Build agents fixed in 7 configs:

* Keyman for Windows Release (two steps)
* Keyman for Windows Test OSK Render
* Keyman for Windows Test
* Keyman Developer Release (two steps)
* Keyman Developer Test
* Keyboards Test (was on 2017)
* KeymanWeb Test PR Regressions (was on 2017) -- currently disabled

Replaced the following (or similar):

```bat
CALL "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsamd64_x86.bat"
```

with:

```bat
CALL %VisualStudioEnvSetupBat%
```

Where `VisualStudioEnvSetupBat` has been configured as a Keyman project-wide parameter:

```
"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\vsdevcmd.bat" -no_logo -startdir=none
```
