### ISSUE TITLE
bug(iOS): Crash while trying to open Keyman 17.0.38 Alpha build 

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8128]
### Describe the bug

After installing Keyman 17.0.38 alpha build from Keyman Site, Crash happens while trying to open the Keyman app. 

### Reproduce the bug

1. Download Keyman 17.0.38-Alpha iOS build from Keyman Status Site. 
2. Install the build in iOS 16.2 / iPhone 14 Pro Max Simulator. 
3. Click or Double click on the Keyman App in the home screen leads to crash with an error message. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/215731980-aab83087-f17d-4e2a-9f37-fb76ce2805a2.png">

I have attached error text file for reference. 

[Keyman17038.txt](https://github.com/keymanapp/keyman/files/10545329/Keyman17038.txt)

### Expected behavior

The Keyman App should open immediately after clicking on the Keyman icon. 

### Related issues

#8118 

_No response_

### Keyman apps

- [ ] Keyman for Android
- [X] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.038 Alpha

### Operating system

iOS 16.2

### Device

iPhone 14 Pro Max Simulator

### Target application

Keyman App

**Comment by MayuraVerma** [comment]
This is the same issue in 16.0.135, 17.0.36, 17.0.35, 17.0.34

**Comment by mcdurdin** [comment]
This should be resolved in 17.0.39-alpha and 16.0.136-beta -- it was due to #8118 being triggered by sil_euro_latin 2.0.1 release. We fixed it in [sil_euro_latin 2.0.3](https://github.com/keymanapp/keyboards/pull/2141) which is bundled in 17.0.39-alpha and 16.0.136-beta. The fix in iOS to prevent this happening again in the future is in #8125, which will be merged into 17.0 soon.
