### ISSUE TITLE
bug(windows): Old Hungarian layout produce English output on Windows

### ISSUE THREAD

**Issue by rovasiras** [keymanapp/keyman#8238]
### Describe the bug

For some time the Old Hungarian keyboard has been working as an English keyboard on Windows with a Hungarian interface.
I also reported the bug to the keyboards project, it works for them. We used/use the Old Hungarian keyboard standalone installer.
I ran a diagnostic on the keyman, but it did not find a fault.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16

### Operating system

Windows 10 21H2

### Device

Windows 10 desktop

### Target application

Notepad (MS Office doesn't support yet this capatilibity)

### Keyboard name

old_hungarian

### Keyboard version

1.4

### Language name

Old Hungarian

**Comment by rovasiras** [comment]
This problem is not the keyman's problem.

**Comment by soosistvangithub** [comment]
I think, it's a real problem.

**Comment by rovasiras** [comment]
@soosistvangithub I reopened it.

**Comment by soosistvangithub** [comment]
@ermshiperete We are desperate. We have extended the keyman Old Hungarian keyboard and now it does not work correctly. It is not a solution to run the diagnostics for all users, then use the notepad program to force it to work correctly.
Many people do not speak English. They are users, not developers. Hungarian Windows does not use utf encoding by default. When running, you can force utf-16 encoding.

**Comment by rc-swag** [comment]
@soosistvangithub  Can you please send me a Direct Message via the community site at this [link](https://community.software.sil.org/u/ross) I would like to organise a support call.

**Comment by soosistvangithub** [comment]
> @soosistvangithub Can you please send me a Direct Message via the community site at this [link](https://community.software.sil.org/u/ross) I would like to organise a support call.

@rc-swag 
DO YOU THINK THAT WE DO NOT KNOW THAT THE OLD HUNGARIAN LAYOUT NEEDS OLD HUNGARIAN FONT?

**Comment by mcdurdin** [comment]
> DO YOU THINK THAT WE DO NOT KNOW THAT THE OLD HUNGARIAN LAYOUT NEEDS OLD HUNGARIAN FONT?

@soosistvangithub I understand that you are frustrated but 'shouting' is unhelpful -- see our [code of conduct](https://github.com/keymanapp/keyman/blob/master/CODE_OF_CONDUCT.md).

We still are unclear about the circumstances in which Keyman is not working correctly for you. You tell us it isn't working correctly. We cannot reproduce the problem here.

@rc-swag is trying to assist you by watching the problem happen on your screen. Then he would be able to understand the root cause of the problem.

We use notepad as a baseline test because it avoids many other potential compatibility issues. We are _not_ suggesting that you need to use notepad for real work with Old Hungarian, just as a test. In the same way, we asked for a diagnostic report to try and find the cause of the issue. We are _not_ suggesting that you need to send a diagnostic report every time you want to work in Old Hungarian.

**Comment by rc-swag** [comment]
> @rc-swag
> DO YOU THINK THAT WE DO NOT KNOW THAT THE OLD HUNGARIAN LAYOUT NEEDS OLD HUNGARIAN FONT?

@soosistvangithub 
I will attempt to summarise the current status. In your previous message, you stated that it is working on your PC.
The sequence of steps followed was:

* Use the Keyman Configuration to send a diagnostic report
* Reboot Windows (with Hungarian interface) 
* Open Notepad, selected an Old Hungarian Font and typed the text 
- **Result:** now working as expected.

The diagnostic report does not make any changes to the system. 
This is the reason I suggested that those steps listed would probably work without the first step of running the diagnostic report. For example, it could be the rebooting of Windows. 

I would like to understand what outstanding issues you have.

Are there users for which it is still not working as expected? If so are any of them willing to have a support call so I can see their screen to give insight into the root cause of the issue?

**Comment by rovasiras** [comment]
This is a sterile debate. It works for some and not for others. I close it

**Comment by rc-swag** [comment]
Thanks for the update @rovasiras. Obviously, we want it to be working for everyone. If more information becomes available this issue can be opened.
