### ISSUE TITLE
chore(linux): cleanup deep dependencies on core in tests

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#8309]
Currently, the Linux tests make use of a test-suite library in Core (kmx_test_source.cpp/.hpp), and also the set of .kmx files.

This deep dependency is fragile -- changes to Core tests should not require changes to the Linux codebase. The .kmx files included in Core have a specific purpose for testing Core functionality, and we need to consider how well these fit the Linux tests into the future.

Suggest that the source files should be refactored to common/ and the .kmn/.kmx files also.

However, we need to be careful when doing this, because there is potential for further maintenance issues either way.

@ermshiperete fyi

**Comment by ermshiperete** [comment]
> The .kmx files included in Core have a specific purpose for testing Core functionality, and we need to consider how well these fit the Linux tests into the future.

The .kmx files in `core/tests/unit/kmx` exercise different edge cases of the KMX spec, so AFAICT they are not specific to Core. Every engine has to be able to work with these, so they are a good set of integration tests that can show holes in the engine implementation. 

However, I agree that the location of these test files under core is not ideal, and there might be cases missing. Also, since on the Linux side they are more integration than unit tests it's debatable whether or not they should run with each test build, but they should run regularly and test failures be prominently visible.

**Comment by mcdurdin** [comment]
Tests have been moved so this is done.
