### ISSUE TITLE
test(windows): Regression Test Report 17.0.66-alpha (0 failures)

### ISSUE THREAD

**Issue by sillsdev-dondillard** [keymanapp/keyman#8411]
### Describe the bug

Test Suites
Execute Test Lodge tests. Test suite name(s):
      Regression
o	Windows
These test were executed on Windows 10 and Windows 11

Test Report for Keyman 17.0 Windows
Results  
     Expected Test Pass Duration		1 day(s)
     Actual Test Pass Duration			1 day(s)

     Expected Start Date			3/9/2023
     Actual Start Date			3/9/2023

     Overall Results: 			100% (68/68 passed)
     Regression 					
Windows 10					100% (34/34 passed)
Windows 11					100% (34/34 passed)

Issues Found

	None

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [X] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0

### Operating system

Windows 10 and 11

### Device

PC

**Comment by mcdurdin** [comment]
Thank you for this. Looking good.

A few thoughts:

1. Probably paste the content into a [blank issue](https://github.com/keymanapp/keyman/issues/new) rather than the Bug Report template -- most of the bug report template fields are irrelevant.
2. Make sure you include the full version number in the report, e.g. 17.0.66-alpha
3. Title should be `test(windows): Regression Test Report 17.0.66-alpha (## failures)`
4. It should be fine to go ahead and close the issue immediately (we'll still be notified of it, but it won't clutter our bug lists) -- even if there are failures; see below.
5. I'm not sure if you have access to set labels, but if you do, add the `tests` label and the label for the scope (e.g. in this case `windows/`). Don't use the `bug` label.

## Dealing with test case failures

* Each individual failure should be broken out into a separate Bug Report issue.
* After creating the Bug Report issue (using the Bug Report issue template this time), ensure that its issue number is referenced in the regression test report. 
* Don't create multiple issues for the same bug -- just reference the existing issue number in follow-up regression test reports.

**Comment by mcdurdin** [comment]
One last thought: surround the content with [triple backticks](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) so that it is formatted as monospace, as otherwise it becomes a strange mix of formatting.
