### ISSUE TITLE
test(common): Mobile app compatibility tests - USX Editor

### ISSUE THREAD

**Issue by MakaraSok** [keymanapp/keyman#8461]
The basic idea is to load the app (or test page), and then test input with latest release version of Keyman apps and a variety of keyboards.

## Gather Assets for Testing
Install the following keyboards and have the test page link ready to load on the respective browser.
* Keyman app - Latest version (please record the version in the test results)
* Khmer Angkor keyboard [package](https://keyman.com/go/package/download/khmer_angkor?version=1.3&tier=stable)
* EuroLatin (SIL) keyboard [pagekage](https://keyman.com/go/package/download/sil_euro_latin?version=2.0&tier=stable)
* Galaxie Hebrew (Positional) keyboard [package](https://keyman.com/keyboards/galaxie_greek_hebrew_positional)
* IPA (SIL) keyboard [package](https://keyman.com/go/package/download/sil_ipa?version=1.8.6&tier=stable)
* USX Editor test [page](https://usxeditor.web.app): delete the first line and type in the text area to test
<img src="https://user-images.githubusercontent.com/28331388/221121515-2e4ebcde-7797-4495-90d0-e60d29accec2.png" width="400">

## User Testing
The app may need to be tested in multiple environments. Each environment can be defined as a group here. For example, if you wanted to test a web app, you may have the following groups:
* GROUP_IOS_SAFARI: iOS / Safari browser
* GROUP_IOS_CHROME: iOS / Chrome browser
* GROUP_ANDROID_CHROME: Android / Chrome browser
* GROUP_ANDROID_FIREFOX: Android / Firefox

Load "the app or 'test page' being tested" on the respective OS (and browser) to test the followings:
   * TEST_KHMER_ANGKOR: Khmer Angkor
      * Ensure longpress on <kbd>ស</kbd> and choose <kbd>ឞ</kbd> to produce `ឞ`.
      * Type <kbd>ស</kbd> <kbd>ុ</kbd> <kbd>្រ</kbd> (longpress of <kbd>រ</kbd>) <kbd>ក</kbd> to produce `ស្រុក`.
   * TEST_SIL_EURO_LATIN: SIL Euro Latin
      * Longpress on <kbd>a</kbd> and choose <kbd>ǎ</kbd> to output `ǎ`
   * TEST_GALAXIE_HEBREW: Galaxie Hebrew mentioned above and here is [how to](https://docs.google.com/spreadsheets/d/e/2PACX-1vS6GnYMo3WB-m7Mj8_4IMzz54MCDNECh01bsuI5epx7LJo28VMSJY8aT9WRbGms6bb_k4DSbNrf7uHZ/pubhtml?gid=0&single=true) type each key.
      * Type <kbd>b</kbd> <kbd>\\</kbd> <kbd>=</kbd> <kbd>r</kbd> <kbd>@</kbd> <kbd>a</kbd> <kbd>v</kbd> <kbd>!</kbd> <kbd>y</kbd> <kbd>t</kbd> to output `בְּרֵאשִׁית`. FAILED if the output is different.
   * TEST_SIL_IPA: sil_ipa
      * Ensure the key sequence <kbd>n</kbd> <kbd>></kbd> (long press of <kbd>]</kbd> on `123` layer) produces `ŋ`.
   * TEST_INTERACTION_WITH_TEXT_FORMATTING: 
      * (n/a for the time being)
   * TEST_CJK_IMX: 
      * (n/a for the time being)

**Comment by bharanidharanj** [comment]
### GROUP_ANDROID_FIREFOX: Android / Firefox

* **TEST_KHMER_ANGKOR (PASSED):**  Tested with the latest Keyman 17.0.69-alpha build in Android 12 / API 31 emulator in Firefox browser and it is showing the correct output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/225881033-28667a9f-b27b-4cb4-9b79-d93a38d1d6aa.PNG">

* **TEST_SIL_EURO_LATIN (PASSED):**  Tested with the latest Keyman 17.0.69-alpha build in Android 12 / API 31 emulator in Firefox browser and it is showing the correct output.

    <img width="300" src="https://user-images.githubusercontent.com/19683143/225881131-4d09ffec-72a5-4a32-b8d2-e785e82b38ef.PNG">


* **TEST_GALAXIE_HEBREW (PASSED):**  Tested with the latest Keyman 17.0.69-alpha build in Android 12 / API 31 emulator in Firefox browser and it is showing the correct output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/225881167-b8d424bf-f6cd-476a-9fe0-2d9c71431202.PNG">

* **TEST_SIL_IPA (FAILED):**  Tested with the latest Keyman 17.0.69-alpha build in Android 12 / API 31 emulator in Firefox browser and I noticed that letters are disappearing after I typed.  Seems to be an issue. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/225881206-44141e12-f2c4-4981-b805-fce8e72486c5.PNG">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (SKIPPED):** Skipped this test since it is not ready for testing.

* **TEST_CJK_IMX (SKIPPED):** Skipped this test since it is not ready for testing.

**Comment by bharanidharanj** [comment]
### GROUP_IOS_SAFARI: iOS / Safari browser

* **TEST_KHMER_ANGKOR (PASSED):** Tested with the latest Keyman 17.0.69-alpha build in iOS 16.2 \ iPhone 14 Pro Max Simulator in Firefox browser and it is showing the correct output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/225895200-eaca01d9-387e-4284-89cc-4646d607585a.png">

* **TEST_SIL_EURO_LATIN (PASSED):** Tested with the latest Keyman 17.0.69-alpha build in iOS 16.2 \ iPhone 14 Pro Max Simulator in Firefox browser and it is showing the correct output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/225895414-42a549db-650f-4d9a-9b3d-be4a87e75547.png">

* **TEST_GALAXIE_HEBREW (PASSED):** Tested with the latest Keyman 17.0.69-alpha build in iOS 16.2 \ iPhone 14 Pro Max Simulator in Firefox browser and it is showing the correct output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/225895448-9bf613d0-1621-4dd2-9364-846e25eb9274.png">


* **TEST_SIL_IPA (PASSED):** Tested with the latest Keyman 17.0.69-alpha build in iOS 16.2 \ iPhone 14 Pro Max Simulator in Firefox browser and it is showing the correct output.

   <img width="300" src="https://user-images.githubusercontent.com/19683143/225895483-f8f09401-db6d-45ed-940f-21c36f68e3d3.png">


* **TEST_INTERACTION_WITH_TEXT_FORMATTING (SKIPPED):** Skipped this test since it is not ready for testing.


* **TEST_CJK_IMX (SKIPPED):** Skipped this test since it is not ready for testing.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_IOS_CHROME: iOS / Chrome browser

* **TEST_KHMER_ANGKOR (SKIPPED):** Chrome browser is pretty similar to Safari browser. Hence, the results I have posted in Safari browser will be the same in Chrome If run it. Since, I don't have chrome browser in the iPhone Simulator, I skipped the test. 
* **TEST_SIL_EURO_LATIN (SKIPPED):** Chrome browser is pretty similar to Safari browser. Hence, the results I have posted in Safari browser will be the same in Chrome If run it. Since, I don't have chrome browser in the iPhone Simulator, I skipped the test. 
* **TEST_GALAXIE_HEBREW (SKIPPED):** Chrome browser is pretty similar to Safari browser. Hence, the results I have posted in Safari browser will be the same in Chrome If run it. Since, I don't have chrome browser in the iPhone Simulator, I skipped the test. 
* **TEST_SIL_IPA (SKIPPED):** Chrome browser is pretty similar to Safari browser. Hence, the results I have posted in Safari browser will be the same in Chrome If run it. Since, I don't have chrome browser in the iPhone Simulator, I skipped the test. 
* **TEST_INTERACTION_WITH_TEXT_FORMATTING (SKIPPED):** Chrome browser is pretty similar to Safari browser. Hence, the results I have posted in Safari browser will be the same in Chrome If run it. Since, I don't have chrome browser in the iPhone Simulator, I skipped the test. 
* **TEST_CJK_IMX (SKIPPED):** Chrome browser is pretty similar to Safari browser. Hence, the results I have posted in Safari browser will be the same in Chrome If run it. Since, I don't have chrome browser in the iPhone Simulator, I skipped the test.

**Comment by MakaraSok** [comment]
### GROUP_IOS_CHROME: iOS / Chrome browser

Tested with the  latest Keyman 17.0.86-alpha build in iOS 16.4.1 /  iPad mini 6 and it is showing the correct output. 
Chrome version 112.0.5615.46

<img width="300" src="https://user-images.githubusercontent.com/28331388/231635292-3fd5fd6e-35a4-45bb-835c-2c1407e27fe6.PNG">


* **TEST_KHMER_ANGKOR (PASSED):** 
* **TEST_SIL_EURO_LATIN (PASSED):** 
* **TEST_GALAXIE_HEBREW (PASSED):** 
* **TEST_SIL_IPA (PASSED):** 

### GROUP_ANDROID_CHROME: Android / Chrome browser

Tested with the  latest Keyman 17.0.86-alpha build in Android 10 /  Samsung Galaxy S9+ and it is showing the correct output. 
Chrome version 112.0.5615.46

<img width="300" src="https://user-images.githubusercontent.com/28331388/231645961-180a9d7c-140e-4fb2-ab6b-6900fc493e71.png">


* **TEST_KHMER_ANGKOR (PASSED):** 
* **TEST_SIL_EURO_LATIN (PASSED):** 
* **TEST_GALAXIE_HEBREW (PASSED):** 
* **TEST_SIL_IPA (PASSED):**

**Comment by MakaraSok** [comment]
@keymanapp-test-bot retest GROUP_ANDROID_FIREFOX TEST_KHMER_ANGKOR TEST_SIL_EURO_LATIN TEST_GALAXIE_HEBREW TEST_SIL_IPA

**Comment by MakaraSok** [comment]
@bharanidharanj Could you please help and retest this group as it was not behaving as expected for me on Android 10.

**Comment by bharanidharanj** [comment]
# Test Results

### GROUP_ANDROID_FIREFOX: Android / Firefox

* **TEST_KHMER_ANGKOR (FAILED):** Tested with the latest Keyman 17.0.86-alpha build along with Firefox Focus browser in Android 12 / API 31 emulator and here is my observation: 1. After selecting the subkey menu from the Khmer Angkor keyboard, the cursor misplaced with some other letter. Seems to be an issue. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/231729956-af7ddb41-70d8-43d5-8814-f12cf0487526.PNG">

* **TEST_SIL_EURO_LATIN (PASSED):** Tested in the Firefox Focus browser in Android 12 / API 31 emulator and it is showing the correct output. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/231730039-a71d76ea-70a1-47c0-a991-a268b2e2432f.PNG">


* **TEST_GALAXIE_HEBREW (PASSED):** Tested in the Firefox Focus browser in Android 12 / API 31 emulator and it is showing the correct output. 
   
  <img width="300" src="https://user-images.githubusercontent.com/19683143/231730070-6cb6e121-4808-4027-a46d-d3fc56698969.PNG">


* **TEST_SIL_IPA (FAILED):** After pressing > symbol from the keyboard, the whole letter disappear from the text area. Seems to be an issue. 
   
   <img width="300" src="https://user-images.githubusercontent.com/19683143/231730093-62c9af42-1956-4dad-b205-74aca54468f1.PNG">

**Comment by MakaraSok** [comment]
- [x] verification test
- [x] no more retest requested
