### ISSUE TITLE
Feature request: Internationalize Keyman Desktop installer

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#850]
Hello,

Request is to make keyman complete internationalization. So, we can localize the keyman from installation to uninstall in our local.

Thanks,
Mayura.

**Comment by mcdurdin** [comment]
Yes, this needs to happen before release. I would like to do it when all strings are stable; I think we are at that point about now.

**Comment by mcdurdin** [comment]
Duplicates #780

**Comment by MayuraVerma** [comment]
This is not duplication of localization request of 10.

The request was add localization ability for installation also.

**Comment by mcdurdin** [comment]
Okay, I'm not understanding what you are wanting then?

**Comment by MayuraVerma** [comment]
localization of installation wizard to un-installation.
I don't recall if it was in community forum, we had a discussion of this topic. There were few more places were localization was missing for Keyman applicaiton.
You had advised me to submit a feature request to scope it to future version.

**Comment by mcdurdin** [comment]
Righto. Sorry about the confusion. I've marked this as a future feature, because it's non-trivial to add a language selection phase into the existing setup for Keyman Desktop.

Note that custom build packages can already localize all strings for the installer. See https://help.keyman.com/developer/10.0/reference/file-types/kps  When you then build a package installer, those strings will override the defaults.

**Comment by MayuraVerma** [comment]
Thanks. I will try to use it.

**Comment by mcdurdin** [comment]
This has been completed with Keyman 14. See https://translate.keyman.com :)
