### ISSUE TITLE
[Windows] Icons incorrect in Keyman Configuration, shortcuts tab

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#858]
1. All the keyboards installed in system are showing the icons of keyman keyboard installed under "Keyboard Shortcuts" in configuration. This was functioning properly in version 9.0

![screen shot 2018-05-11 at 12 30 45 am](https://user-images.githubusercontent.com/14062593/39908212-abb4cde0-54b2-11e8-83b3-631d54a63fa4.png)

2. There used to be a "?" link to open readme and more info on the keyboard at the top hand corner of the keyboard. It used to display "Read me" and "Details" in version 9.0 and this is still present in mac version. This feature is removed in 10. I am not if this is intended.

![screen shot 2018-05-11 at 12 34 08 am](https://user-images.githubusercontent.com/14062593/39908352-63ea4d18-54b3-11e8-9e41-0d8745e11501.png)

**Comment by mcdurdin** [comment]
The screenshots are too small for full context. Can you send full screenshots and attach a Keyman diagnostic report to this issue?

**Comment by MayuraVerma** [comment]
![capture1](https://user-images.githubusercontent.com/14062593/40097125-095f3e9a-589a-11e8-8261-e883feed222c.PNG)
"More info" link is missing
![capture2](https://user-images.githubusercontent.com/14062593/40097126-096edee0-589a-11e8-9b00-7093f307c81e.PNG)


[diagnostic.zip](https://github.com/keymanapp/keyman/files/2007542/diagnostic.zip)

**Comment by mcdurdin** [comment]
In opposite order:

# Missing `[?]` button

The missing `[?]` button is because the keyboards are installed without documentation. If you install a package that includes documentation, the `[?]` button will appear.

# Incorrect icon

The incorrect icon in the hotkeys tab is a little more difficult. The diagnostic did not illuminate the issue any further. Two options:

1. Uninstall and reinstall the beta to see if that resolves the problem, or
2. If you can capture the temporary files used to generate the configuration dialog, we can test further.

To capture temporary files used to generate the configuration dialog:

1. Close all other running apps.
2. Open Registry Editor, and create the key `HKEY_CURRENT_USER\Software\Keyman\Debug`. In this key, add the **String** value `Debug_XMLRenderer` with the value `1` (string type even though it is a number).
3. Press Win+R, type `%temp%` and press Enter. You may want to remove any files that are there to avoid confusion (warning: removing temporary files may cause trouble with apps that are currently running).
4. Start Keyman Configuration. In the temp folder, a set of files starting with `kmn` should appear, e.g. 
![image](https://user-images.githubusercontent.com/4498365/40098925-06db3ff2-5908-11e8-8150-45c8d2037de9.png)
5. Zip those files and attach them to this case.
6. Finally, remove the `Debug_XMLRenderer` value from the registry again.

**Comment by MayuraVerma** [comment]
1. Reinstalling didn't resolve the issue.

2. Below are the files
![image](https://user-images.githubusercontent.com/14062593/40234082-07a26d66-5a6b-11e8-8d35-f9a667ac12ff.png)

[files.zip](https://github.com/keymanapp/keyman/files/2016785/files.zip)

**Comment by MayuraVerma** [comment]
Missing [?] button is resolved.
It is available with the package.

**Comment by mcdurdin** [comment]
Unfortunately, you captured the files for the startup "Splash" screen rather than the Configuration dialog. Can you try again? Make sure you have opened Keyman Configuration itself before collecting the files to send. Note that the .xml file should be called kmnXXXX.Keyman.xml (where XXXX is 4 random hexadecimal digits).

**Comment by MayuraVerma** [comment]
Hello @mcdurdin 

I have uploaded files as you needed.

Please let me know if you need any additional info.

[temp.zip](https://github.com/keymanapp/keyman/files/2035451/temp.zip)
![image](https://user-images.githubusercontent.com/14062593/40487586-49f0ad18-5f2a-11e8-99f1-32e795814d07.png)

**Comment by mcdurdin** [comment]
Sadly, that file temp.zip is an empty file. Can you try again?

**Comment by MayuraVerma** [comment]
sorry my mistake try this


[temp.zip](https://github.com/keymanapp/keyman/files/2038018/temp.zip)

**Comment by mcdurdin** [comment]
That zip still doesn't contain the right files :( Make sure Keyman Configuration is still running (and no other programs) when you try to get the files from the temporary folder. The screenshot you showed looked like the files I would expect to see, so I'm not sure how the zip file didn't include those files!

**Comment by MayuraVerma** [comment]
Please try this.
I had closed all apps and open keyman configuration
Here are the files.

![image](https://user-images.githubusercontent.com/14062593/40543681-167b25be-5feb-11e8-92dc-50afa9230e67.png)
[Temp.zip](https://github.com/keymanapp/keyman/files/2039227/Temp.zip)

**Comment by mcdurdin** [comment]
Great, thank you, that collected the right files and gave me enough detail to trace the issue.

**Comment by MayuraVerma** [comment]
@mcdurdin this seems to be resolved in 1096 build.

Please close this issue, if you think the same.

**Comment by mcdurdin** [comment]
Yes, it should be resolved there. Still need to refresh the history.md to reflect this. We will close the issue when the fix lands in the 11.0 alpha master branch.
