### ISSUE TITLE
bug(linux): Installed keyboard with language tag `mul` specified doesn't show up in available keyboards

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#8620]
I created a keyboard with BCP47 tag `mul` to indicate that it supports multiple languages. After installing that with `km-package-install -f itrans_devanagari_sanskrit_vedic.kmp -l mul` I noticed that it doesn't show up in the keyboards dropdown. Looking in the system keyboard settings shows that it gets installed with `mul-Zyyy`. Manually changing that in dconf Editor to `mul` will make it show up.

**Comment by rik-shaw** [comment]
@ermshiperete sorry I am a bit confused. I just modified my keyboard to list `mul` as a "supported language" in the `.kps` and the `.keyboard_info` files (and listed it as the first language so if no bcp47 identifier was used it would show "Multiple languages" in the ibus menu. I think this bug is about being able to install using the `mul` tag even if `mul` isn't defined in the keyman keyboard files?

Here's my newest `SIL EL - Ethiopian Latin` keyboard for reference: https://keyman.com/keyboards/sil_el_ethiopian_latin

**Comment by rik-shaw** [comment]
In addition, attempting to install using `--bcp47 mul` also results in the same error that `mul-Zyyy` can't be found.

**Comment by mcdurdin** [comment]
Yay, BCP-47 comes back to bite us again 😢  This may mean _another_ update to your keyboard, @rik-shaw, as it will take time for a patch to Keyman to filter through.

**Comment by rik-shaw** [comment]
> Yay, BCP-47 comes back to bite us again cry This may mean _another_ update to your keyboard, @rik-shaw, as it will take time for a patch to Keyman to filter through.

No problems here, since I added `mul` as the first "supported language" it means when not specifying a language it installs as "Multiple languages" so I am happy enough for now :-)
