### ISSUE TITLE
bug(android): Shift layer is not working if we attach an external(USB) keyboard to mobile

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8701]
### Describe the bug

I noticed that even though the shift layer is on in the default keyboard (sil_euro_latin keyboard) and If I press a letter from an external keyboard, the output shows in 'small' letter. ie., the shift layer changed to base layer. 

### Reproduce the bug
1. Install the latest Keyman 17.0.97 build in a Mobile device.
2. Connect an external (USB) keyboard to Mobile. 
3. Open Keyman In-App.
4. Verified that the Keyboard is in Shift layer. 
5. Type letter "T" from external keyboard. 

Here, I noticed that the shift layer immediately changes to the default layer and the output shows 't' in the input text screen. 

I have attached the Screenshot for reference. 

   <img width="300" src="https://user-images.githubusercontent.com/19683143/235699748-fa26e6f7-9483-481a-83ad-814e5ef69f53.jpg">

### Expected behavior
When the default keyboard is in Shift layer, pressing a letter key from an external keyboard the input screen outputs the capital letter. 

### Keyman apps

- [x] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version
Keyman 17.0.97-alpha build

### Operating system
Android 5.0, Android 9.0, Android 12.0

### Device
Redmi Note 8 Pro, External USB keyboard

**Comment by mcdurdin** [comment]
This is by design.

It's tricky, because the modifier keys on the touch keyboard do not impact the physical keyboard, on purpose: it seems to make sense initially for alphabetic keys and Shift, but even the digit keys are modified by Shift on a physical keyboard, whereas they are not necessarily for touch. Furthermore, what do you do with the Numeric/Symbols layer switch on the touch keyboard.

It ended up being clearer just keeping the modifier keys on the physical keyboard completely separate from the touch keyboard layer switch keys.
