### ISSUE TITLE
[Mac] font being reset when typing using Keyman

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#872]
Hello,

Keyman keyboard remembers a font for the language, perhaps the system default font for the language in system. 

In Pages and Keynotes, even if the font is different, second keystroke will replace the font in application by the keyman keyboard.

I have an equivalent keyboard xml based, it doesn't do it.

So, I am pretty sure its the keyman that is changing the font in the applications.

**Comment by MayuraVerma** [comment]
This seems to be resolved in latest build. Still this is worth looking into

**Comment by tombogle** [comment]
I can reproduce this. The problem is that when there is preceding text with a particular font and then you choose a new font to be applied to the next character(s) you type. If, after setting that new font, the very first character sequence you type is one that outputs character(s) but then does a replacement, the process of deleting the previous character(s) causes Pages, Keynote or any similar application to forget the selected font because the characters that carried that font information have all been deleted.

**Comment by tombogle** [comment]
Same problem in Mail. Interestingly, LibreOffice Vanilla, OpenOffice and Word handle this correctly. Off hand, I can't think of a good way of tricking these apps into working differently. Some apps apparently hold onto the phantom font information when the last bit of text has been deleted, and others don't.

**Comment by tombogle** [comment]
But FWIW, I just tried to simulate this in Mail by deleting the character myself and then typing another character, and that does work. So I guess I could treat those apps as "legacy" and maybe they would work correctly...

**Comment by tombogle** [comment]
I have a fix for Pages and Keynote. Unfortunately, the "legacy" approach does not work in Mail.

**Comment by tombogle** [comment]
Hmm... I have just created a version of Keyman to revert those changes (because they caused other problems), but now I can't reproduce the problem, even in Mail. I wonder if Apple fixed those programs or if I'm forgetting how to reproduce the problem.
