### ISSUE TITLE
bug(android): Keyboard is flashing behind the Keyboard picker menu after clicking the Info icon

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#8868]
### Describe the bug

I noticed that the keyboard background is blinking every time whenever I click the keyboard info icon in the Keyboard Picker menu.

### Reproduce the bug

1. Install Keyman 17.0.113-alpha build.
2. Open Keyman In-App. 
3. Download and install Khmer Angkor keyboard. 
4. Long press the globe key to open the Keyboard picker menu. 
5. Click the Info (i) icon against the Central Khmer (Khmer, Cambodia..) label name. 
6. Here,  I noticed that the Keyman app which is running behind the Keyboard picker menu is blinking.

I have attached the video file for reference. 

https://github.com/keymanapp/keyman/assets/19683143/e39e08ce-cf2e-4d12-8f3a-0a688db7448f

### Expected behavior

Clicking the Info icon in Keyboard picker menu should not affect the Keyman keyboard background. 

### Related issues
#8007 

### Keyman apps

- [X] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.113-alpah build

### Operating system

Android 5.0, 9.0, 12.0

### Device

Redmi Note 8 Pro, API 31 emulator

**Comment by jahorton** [comment]
After fixing #8534 and synchronizing all pending entries in the JS queue as they come in, I did an analysis of all the re-layout calls for the keyboard for three cases.  I'll log the entries and relevant call-stack data below:

## App Load

First setLayoutParams call:

- initKeyboard:631, KMManager (com.keyman.engine)
  - page hasn't even had a -chance- to load yet.
  - have not yet connected:
    - WebView client
    - JS interface object
    - no `loadKeyboard()` call yet
      - which doesn't even try to directly load the user's kbd.
- initialize:410, KMManager (com.keyman.engine)

Second:
- during creation of the MAIN app view.  It's a big stack that's not terribly informative otherwise.

Third:

- onConfigurationChanged:750, KMManager (com.keyman.engine)
- onResume:272, MainActivity (com.tavultesoft.kmapro)

Fourth:

- onConfigurationChanged:419, KMKeyboard (com.keyman.engine)
- onConfigurationChanged:751, KMManager (com.keyman.engine)
- onResume:272, MainActivity (com.tavultesoft.kmapro)

** Main app screen finally appears, Get Started shows. **

Fifth:

- registerLexicalModel:1335, KMManager (com.keyman.engine)
  - have not inspected the properties of the params or the sources at this stage.
  - Upon drill-down, is dependent upon the state of KMKeyboard.java, field `currentBanner`.
  - No clear, direct update of its state by `registerLexicalModel`, though.
- registerAssociatedLexicalModel:1399, KMManager (com.keyman.engine)
- pageLoaded:105, KMKeyboardWebViewClient (com.keyman.engine)
  - is after the `setKeyboard` call, but synchronous.
- shouldOverrideUrlLoading:139, KMKeyboardWebViewClient (com.keyman.engine)
- onPageFinished:63, KMKeyboardWebViewClient (com.keyman.engine)


Sixth:

(System keyboard) is active; the actual desired keyboard hasn't shown yet.

- shouldOverrideUrlLoading:179, KMKeyboardWebViewClient (com.keyman.engine)
  - branch: refreshBannerHeight
  - this branch sets the previously-noted `currentBanner` _just_ before triggering the Android-side re-layout.
- onPageFinished:63, KMKeyboardWebViewClient (com.keyman.engine)
  - Appears to be triggered by the page:  
    url: file:///data/user/0/com.tavultesoft.kmapro.debug/app_data/keyboard.html#refreshBannerHeight-2+change=active
  - Thus... the webview hasn't _visibly_ updated, but the model loaded.
    - ... and it's the model's load that triggered the final check.
    - triggered by `android-host.js`, `onStateChange`, a handler that detects when the prediction mode changes within Web.

There is no seventh.

## Keyboard with predictions -> keyboard without predictions
*sil_euro_latin -> sil_ipa*

First:

- shouldOverrideUrlLoading:179, KMKeyboardWebViewClient (com.keyman.engine)
  - branch: refreshBannerHeight
- onPageFinished:63, KMKeyboardWebViewClient (com.keyman.engine)

And that's it!

## Keyboard without predictions -> keyboard with predictions
*sil_ipa -> sil_euro_latin*

First: 

- registerLexicalModel:1336, KMManager (com.keyman.engine)
- registerAssociatedLexicalModel:1401, KMManager (com.keyman.engine)
- switchToNextKeyboard:1614, KMManager (com.keyman.engine)
- doGlobeKeyShortpressAction:568, KMManager (com.keyman.engine)
- ... (triggered by globe-key press)

Second:

- shouldOverrideUrlLoading:179, KMKeyboardWebViewClient (com.keyman.engine)
- onPageFinished:63, KMKeyboardWebViewClient (com.keyman.engine)

---

Note:  no device rotations were performed during this investigation; I imagine that's covered by `onConfigurationChanged`, but am presently not 100% sure about that.
