### ISSUE TITLE
bug(linux): Error message appears in the terminal window after uninstalling the shared keyboard using command line in Wasta Linux

### ISSUE THREAD

**Issue by bharanidharanj** [keymanapp/keyman#9213]
### Describe the bug

I noticed that in Wasta 20.04 Linux OS, after uninstalling the shared keyboard using command line in terminal window, it is showing an error message. 

### Reproduce the bug

1. Install 17.0.134-alpha in Wasta 20.04 Linux OS.
2. Open Keyman Configuration dialog. 
3. Download and install French and Spanish with EuroLatin(SIL) keyboards. 
4. Open Terminal window. 
5. Install Swedish EuroLatin(SIL) keyboard using 'sudo km-package-install -p sil_euro_latin -l sv --shared' command.
6. We may notice that the shared Swedish keyboard is installed in the Configuration dialog. 
7. Uninstall shared keyboard using 'sudo km-package-uninstall --shared sil_euro_latin' command. 

Here, I am getting a warning message 'WARNING:root:could not find connected IBus.Bus' 

8. Again, I gave the same command line in the terminal window. 

I noticed that the there is an error message appears along with warning message. 

I have attached the Screenshots for reference. 

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/9aadf97d-47a3-44cc-8e8e-0d4d6c0d99e6">

   <img width="300" src="https://github.com/keymanapp/keyman/assets/19683143/d9a5685d-51f3-499c-b59e-3f30b37b3827">

### Expected behavior

It would be better if it should throw any error message in the terminal window. 

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [X] Keyman for Linux
- [ ] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

17.0.134-alpha

### Operating system

Ubuntu Wasta 20.04 Linux OS

**Comment by ermshiperete** [comment]
Completely suppressing the message as suggested doesn't seem to be the right way: the user wouldn't get any feedback that the uninstall failed, yet the keyboard is still there → would seem that Keyman doesn't work. 

The reason for the error in the case above is that the shared keyboard has already been uninstalled, trying to uninstall the _shared_ keyboard again tries to uninstall a non-existing keyboard. The keyboard that is still there is in the User area, i.e. omitting the `--shared` parameter (and `sudo`) would successfully uninstall it.

Instead #9312 rewords the message, includes the area (shared/local) and outputs it as a warning instead of an error. Hopefully this will make things a bit clearer for the user.
