### ISSUE TITLE
[Developer] Enhancement: output normalised .kvks file

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#934]
It would be helpful for version control purposes if the XML output to the .kvks file were in a consistent order (alphabetical by vkey string, for example, or in order by physical keyboard layout). Currently a diff between two .kvks files can be difficult to interpret.

**Comment by mcdurdin** [comment]
I'm going to classify this as a bug. The key order should be consistent, I agree. And it should be a very simple fix in the Save routine in Keyman Developer, so it may even squeak into 10.0 stable. No promises!

**Comment by mcdurdin** [comment]
Can you give an example file that I can test with?

**Comment by darcywong00** [comment]
Adding a data point.

When I converted from .kvk to .kvks on keymanapp/keyboards#248 using Developer's "fill from layout", the kvks file originally was sorted alphabetically `K_A` to `K_Z`. I manually rearranged the keys according to physical keyboard to match the order in the "code" view for the original kvk file.

**Comment by DavidLRowe** [comment]
This was indeed the keyboard where I had difficulties comparing two versions of the file to see what had changed. So perhaps Developer is already doing the right thing in writing a .kvks file in a consistent manner, but in this case the input was in a different order.

**Comment by mcdurdin** [comment]
Okay, given this discussion and the potential for larger issues, I'd like to postpone this change for now. Moving to future.

**Comment by DavidLRowe** [comment]
Additional data point: See keyboards PR 879, with .kvks file created Sep2019 with Developer 11.0.1356.0. In the .kvks file, three characters were added to the end of the shift layer. (There seems to be some ordering of alphabetic characters according to the corresponding Greek output character, but the remainder of the characters don't seem to be ordered.

This is probably not a high priority, and might upset people who have put their characters in a specific order.

**Comment by DavidLRowe** [comment]
Additional data point: See keyboards PR 1519 and look at the diff for the .kvks file (https://github.com/keymanapp/keyboards/pull/1519/files?file-filters%5B%5D=.kvks). On the shift layer, three of the changed keys were left in the same position, while three others were moved to the end of the shift layer.

**Comment by DavidLRowe** [comment]
@mcdurdin I'm looking at keyboards PR 1781 (https://github.com/keymanapp/keyboards/pull/1781). The Q and X keys on the shift layer changed, but the new values are added at the bottom of the list. This makes it harder to see how the keys have changed.

How many people put their characters in a specific order? What if we add a new flag (normalise, for example) and allow users to set if False if they want to maintain a specific order. Otherwise (if the flag is True or absent), any time the .kvks file is written out, the layers are in a specific order and all the keys within each layer are in a specific order.

**Comment by mcdurdin** [comment]
Do you mind if I close this as a won't-fix? This now seems to me to be tricky to resolve cleanly; some people do manually organise their KVKS files, others don't. I think adding an option would be hard to explain clearly, tricky to implement, and would add convolution to our visual keyboard editing code paths.

I am hoping that we can deprecate KVKS in a future version of Keyman in favour of the keyman-touch-layout format (which will then have a couple of additional tweaks for desktop layouts). That makes changing this somewhat less useful long-term. .keyman-touch-layout is always ordered spatially, so that resolves that part of the problem...

Of course, keyman-touch-layout suffers from being JSON format but perhaps we can expend effort in making it easier to work with rather than expending effort solving this?
