### ISSUE TITLE
bug(mac): Input Method Incorrect Symbol Replacement

### ISSUE THREAD

**Issue by dyacob** [keymanapp/keyman#9559]
### Describe the bug

This is particular to macOS and Micorosft Word , the issue does not occur on Windows with MS Word.

At the start of a line, or following a "Tab",  Keyman is failing to replace the initial character.  The initial character will then appear alongside the modified character.  To reproduce:

1. Open MS Word
2. Select the ግዕዝ (EMUFI) keyboard
3. Select the Ge'ez Manuscript Zemen font
4. At the start of a _new line_ type `1`, the Ethiopic `፩` will appear
5. Now type `TAB`  a horizontal menu of items appears, but `፩` remains on screen to the left
6.  Type a number to make a selection from the menu
7. The menu has gone away and the select appears alongside the initial `፩`

The above may be repeated where step 4 begins following a `TAB` symbol.

### Expected behavior

The initial symbol will not appear when the menu is shown, nor following the selection from the menu.

### Keyman apps

- [ ] Keyman for Android
- [ ] Keyman for iPhone and iPad
- [ ] Keyman for Linux
- [X] Keyman for macOS
- [ ] Keyman for Windows
- [ ] Keyman Developer
- [ ] KeymanWeb
- [ ] Other - give details at bottom of form

### Keyman version

16.0.141

### Operating system

macOS 13.5.2

### Device

Macbook

### Target application

Microsoft Word v16.77

### Keyboard name

gff_geez_emufi

### Keyboard version

1.0

### Language name

Ge'ez

**Comment by dyacob** [comment]
I've updated the recipe to reproduce the problem to reflect version v1.0.1 of the keyboard.

**Comment by sgschantz** [comment]
Expected behavior described in [gff_geez_emufi documentation](https://help.keyman.com/keyboard/gff_geez_emufi/1.0.1/gff_geez_emufi)

Numeral Variations
The specialized numerals can be entered by typing a regular number followed by the “Tab” key. Each number will have a selection “menu” available. Menus appear on screen in list within square brackets [ ] and an index number. Type the number that corresponds to the desired numeral form to select it. For example:

![](https://help.keyman.com/keyboard/gff_geez_emufi/1.0.1/images/Numeral-Input-List.png)

**Comment by sgschantz** [comment]
Fixed by #10066
