### ISSUE TITLE
[iOS] [Android]: Default EuroLatin2 keyboard

### ISSUE THREAD

**Issue by MayuraVerma** [keymanapp/keyman#957]
Hello,

EuroLatin2  English keyboard is installed in both iOS and Android by default. Also, there is no way we can uninstall it.

Please do not include this keyboard in keyman app to begin with.

**Comment by darcywong00** [comment]
> Also, there is no way we can uninstall it.

That is intentional to prevent the apps from uninstalling all the keyboards and having no known valid keyboard to revert to. If the default EuroLatin2 keyboard doesn't suit your needs, you are welcome to download the KMSample projects and modify them with your preferred default keyboard. (The KMSample projects include a default [tamil99m](https://keyman.com/keyboards/tamil99m) keyboard)

The KMSample1 project can be used to build an in-app keyboard (like the Keyman app without the branding). The KMSample2 project can be used to build a system keyboard (doesn't include a text field).

## Downloads
### iOS (keyman-engine-ios-10.0.[version].zip
https://downloads.keyman.com/ios/beta/

### Android (keyman-engine-android-10.0.[version].zip
https://downloads.keyman.com/android/beta/

## Guides
The iOS guides are incomplete at the moment, but you can follow the Android guide for what to do:
https://help.keyman.com/developer/engine/android/10.0/guides/
