### ISSUE TITLE
bug(linux): Fix version comparison in `keymanutil.c`

### ISSUE THREAD

**Issue by ermshiperete** [keymanapp/keyman#9593]
`keymanutil.c` contains at least one comparison of versions. This currently uses string comparison which doesn't work very well for version numbers, e.g. `1.9` and `1.10`.

One scenario where a user would notice this, is if he has version 1.9 of a keyboard installed in the shared area. He then installs version 1.10 (which adds language X) into the user area. Until this bug is fixed the keyboard won't show up as keyboard for X.

**Comment by mcdurdin** [comment]
I think this should be addressed sooner rather than later, because it has broken on other platforms in the past.

It should be relatively easy to fix, e.g. see: 
* Java: https://github.com/keymanapp/keyman/blob/c0ec8ba76c623be503e9050ff289f7db094ccf07/android/KMEA/app/src/main/java/com/keyman/engine/util/FileUtils.java#L277 
* Pascal: https://github.com/keymanapp/keyman/blob/58496402bba029acff7e33aa0270f4237a430691/common/windows/delphi/general/VersionInfo.pas#L139 
* Typescript: https://github.com/keymanapp/keyman/blob/7f0460172ed84243d9913a18912e8e3634919188/common/web/utils/src/version.ts#L85

They may not all be optimally written, but they do work.

Sample C++ implementation that uses standard libraries:
* https://stackoverflow.com/a/54067471/1836776
