### ISSUE TITLE
chore(common): S_Splash_Start string should not localize the name "Keyman" for Kannada

### ISSUE THREAD

**Issue by rc-swag** [keymanapp/keyman#9635]
> @darcywong00 Do we translate trademark names like "Keyman"

No, that should stay as 'Keyman', 'Windows' as 'Windows' etc.

_Originally posted by @mcdurdin in https://github.com/keymanapp/keyman/issues/9481#issuecomment-1720816693_

**Comment by darcywong00** [comment]
Currently in crowdin, the entire S_Splash_Start string `"Start Keyman"` gets localized.

You may need to change the S_Splash_Start string to `"Start %1$s"`.  And then format "Keyman" into the string.

**Comment by darcywong00** [comment]
From A17S23 sprint plan meeting, team decided this is low-priortity and just busy-work.

It would be preferable to have a way on crowdin to tell translators not to translate "Keyman"...

**Comment by rc-swag** [comment]
> It would be preferable to have a way on crowdin to tell translators not to translate "Keyman"...

Yes. Less important but, useful for Phone UI's is a away to set a maximum number of characters for the localisation.

**Comment by darcywong00** [comment]
While looking at this, I see there's also a string
`S_Splash_Name` for "Keyman".
Maybe we should designate this as not to translate too.

I've made the [fix/windows/crowdin-hide-strings](https://github.com/keymanapp/keyman/tree/fix/windows/crowdin-hide-strings) branch for @rc-swag to investigate using a new "S_Splash_Start_2" string instead of "SP_Splash_Start".
