### ISSUE TITLE
bug(web): warang_citi keyboard is not rendering correctly on the help site

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#9654]
See https://help.keyman.com/keyboard/warang_citi/1.1.1/warang_citi

![image](https://github.com/keymanapp/keyman/assets/4498365/39a6a669-4be5-4d0f-90a2-7c3507f56f3b)

(Put here, retriage if necessary)

**Comment by mcdurdin** [comment]
@DavidLRowe noted (via email) a similar issue with fv_dene_zhatie:

## Scrambled display of touch layout

Currently the default layer of the touch layout appears as:

![image](https://github.com/keymanapp/keyman/assets/4498365/376148fc-644c-499d-a69a-f9d919331d95)

In my local test copy, I changed the order of the layers in the .keyman-touch-layout file from shift|default|numeric to default|shift|numeric, recompiled and the result displayed correctly:

![image](https://github.com/keymanapp/keyman/assets/4498365/2116a9cd-20a6-4d1c-8d0f-54219e29af2b)

**Comment by jahorton** [comment]
The culprit:

https://github.com/keymanapp/keyman/blob/60725b2654a6445b4528140282f91db3342f231c/web/src/engine/osk/src/keyboard-layout/oskLayerGroup.ts#L50-L51

Note: "the first", not "the 'default' layer".

A call to `VisualKeyboard.updateState()` is enough to correct the displayed layer if added to the `buildDocumentationLayout` method near the bottom.

This is not necessary for primary-use KMW because of the following (17.0): 

https://github.com/keymanapp/keyman/blob/60725b2654a6445b4528140282f91db3342f231c/web/src/engine/osk/src/views/oskView.ts#L878-L885

The `present()` pathway is not utilized for doc keyboards, so the issue is never corrected.
