### ISSUE TITLE
[mac] Platform test should return 'macosx' not 'ios'

### ISSUE THREAD

**Issue by mcdurdin** [keymanapp/keyman#967]
From #896:

- [ ] Keyman Engine for macOS: Report `macosx` not `ios`

**Comment by tombogle** [comment]
Turns out the Mac implementation is already "correct", assuming the tokens are supposed to be lowercase and the comparison is supposed to be case-sensitive. If so, the problem is that the platform test keyboard is testing for iOS rather than ios. That said, it would probably be a reasonable thing to perform a case-insensitive match, since we'll certainly never create a spec that is expected to behave differently for two tokens that differ only by case.
Since the spec says to return true for any unrecognized token, the Mac engine implementation is returning true for iOS.

**Comment by tombogle** [comment]
I did notice another problem, however. It returns FALSE for all the browsers, even if the browser in question is in use. So that also needs to be tweaked.

**Comment by mcdurdin** [comment]
Two thoughts there:

1. I would like to discuss the spec saying `return true for unrecognized token` because IMO the spec author must be daft. (disclaimer: I am the spec author). Discuss at standup today.

2. The browser test is for KeymanWeb only - not for desktop apps running within a browser. That should be made explicit in the documentation...

**Comment by mcdurdin** [comment]
> assuming the tokens are supposed to be lowercase and the comparison is supposed to be case-sensitive

The spec is unclear on this. I agree case-sensitive doesn't make sense (iOS vs IOS notwithstanding!).

See #973 and #974.

We discussed the specification note of `return true for unrecognized token` and decided that is wrong. See #973 for the resolution and related issues arising. The basic answer is that unrecognized tokens should always return `false` now.

Long-Story-Short: All this should simplify the tests to simply being the set related to macOS:

* `hardware`
* 'macosx' (add `mac` and `macos` aliases)
* `desktop`
* `native`

These should be case insensitive, and any other test should return `FALSE`.
