### ISSUE TITLE
[ios] longpress of base character doesn't follow nextlayer

### ISSUE THREAD

**Issue by DavidLRowe** [keymanapp/keyman#999]
On touch layout for sil_bwe_karen, on the shift layer, pressing most keys takes you back to the default layer (using nextlayer). The "." key on the shift layer has "," and "?" as longpress keys and both of these take you back to the default layer, as does a simple press of the "." key. However (as tested on an iphone4s using Chrome browser) using the longpress "." that shows up for the "." key leaves you on the shift layer. 

Note: I'm not sure what governs if a key having one or more longpress keys displays the base key along with the longpress keys. I seem to have seen it both ways on different keyboards. As an example, see sil_bwe_karen.

**Comment by erros84** [comment]
Hi @DavidLRowe . 

As for longpress+nextlayer, the nextlayer() behavior is already MUCH better in KM10. This is one of the reasons I'm targeting KM10 with the Cameroon Keyboard.

I recently found the code that governs duplication of the base key (which I would prefer to be disabled, especially on small devices). It seems that platform("phone") adds it, and anything else doesn't add it. I'm not sure that it is intuitive, as you want to avoid fat-fingering, but also conserve screen real estate.

https://github.com/keymanapp/keyman/blob/102613e1b0a85716b90aa6691d617a6aeb5c58f5/web/source/kmwosk.ts#L600

It would be straightforward to make the option always go one way or the other, but building an &SHOWBASEKEY flag will take tinkering in many places (KMW, KMCompiler, and KMDev).

**Comment by mcdurdin** [comment]
The preview of the base key is there for phone-sized devices because your finger obscures it when typing. On tablet devices, you'll notice that there is no preview. Now, because the preview is present, the longpress menu "extends" the preview rather than replacing it, on phone devices. This design follows follow the iOS system keyboard design pattern.

There are arguments either way, but I don't think we'd want to make this a per-keyboard design decision (`&showbasekey`).

Now, in terms of the bug report, it seems that the base key added to the longpress menu loses its nextlayer property when copied to the menu. That should be easy enough to track down and resolve, I hope.

**Comment by erros84** [comment]
I just tested the duplication of the base character iOS and I see it. I was unfamiliar from this since I use Android's Gboard which doesn't do it. I'd still like to see the option as configurable If I coded the change, might you consider including it?
As far asd I can tell, I need to put a &SHOWBASEKEY check/entry in https://github.com/keymanapp/keyman/blob/master/windows/src/developer/TIKE/compile/CompileKeymanWeb.pas ,
a check in https://github.com/keymanapp/keyman/blob/102613e1b0a85716b90aa6691d617a6aeb5c58f5/web/source/kmwosk.ts#L600 ,
and write the text for the documentation, what am I missing?

**Comment by mcdurdin** [comment]
It's not about the complexity of the change so much as how it might constrain the design of Keyman into the future. Where does the option belong, if it exists? Is it per user? Is it device-level? Is it per keyboard? I think per keyboard is probably the worst of the three because that means that people using multiple keyboards on a single device have different behaviour between them.
